// Stateful Poly frontend core wrapper.
//
// This ties the integrated frontend core to an architectural frontend/PC state
// register. Fetch/decode inputs are driven from state, and retired commits,
// raw interrupt entry/restore, precise trap-vector delivery, and native
// return-cookie resumes update state.
module poly_frontend_stateful_core (
    input  logic        clk_i,
    input  logic        rst_ni,

    input  logic        init_i,
    input  logic [1:0]  init_frontend_i,
    input  logic [63:0] init_pc_i,

    input  logic        valid_i,
    input  logic [63:0] sp_i,
    input  logic [63:0] transition_return_pc_i,
    input  logic [31:0] transition_flags_i,

    input  logic        x86_fetch_valid_i,
    input  logic        x86_fetch_fault_i,
    input  logic [31:0] x86_fetch_word_i,
    input  logic [63:0] x86_fallthrough_pc_i,

    input  logic        raw_mem_resp_valid_i,
    input  logic        raw_mem_resp_fault_i,
    input  logic [31:0] raw_mem_resp_word_i,

    input  logic        older_fault_i,
    input  logic        execute_fault_i,
    input  logic        raw_branch_resolved_i,
    input  logic        raw_branch_taken_i,
    input  logic [63:0] raw_branch_target_i,
    input  logic        raw_memory_resolved_i,
    input  logic        raw_memory_fault_i,
    input  logic        memory_order_valid_i,
    input  logic        memory_load_i,
    input  logic        memory_store_i,
    input  logic        memory_atomic_i,
    input  logic        memory_barrier_i,
    input  logic        older_store_pending_i,
    input  logic        store_buffer_full_i,
    input  logic [1:0]  target_frontend_i,
    input  logic [63:0] target_pc_i,
    input  logic        signature_slot_valid_i,

    input  logic        transition_pop_i,

    input  logic        return_recover_valid_i,
    input  logic [63:0] return_target_pc_i,

    input  logic        interrupt_feature_enabled_i,
    input  logic        cpl3_i,
    input  logic        interrupt_i,
    input  logic        user_return_i,
    input  logic [63:0] user_return_pc_i,

    input  logic        trap_valid_i,
    input  logic        trap_monitor_enabled_i,
    input  logic [63:0] trap_monitor_packet_addr_i,
    input  logic        trap_vector_valid_i,
    input  logic [1:0]  trap_vector_frontend_i,
    input  logic [63:0] trap_vector_pc_i,
    input  logic [31:0] trap_reason_i,
    input  logic [31:0] trap_source_mode_i,
    input  logic [63:0] trap_number_i,
    input  logic [63:0] trap_selector_i,
    input  logic [63:0] trap_pc_i,
    input  logic [63:0] trap_resume_pc_i,
    input  logic [63:0] trap_arg0_i,
    input  logic [63:0] trap_arg1_i,
    input  logic [63:0] trap_arg2_i,
    input  logic [63:0] trap_arg3_i,
    input  logic [63:0] trap_arg4_i,
    input  logic [63:0] trap_arg5_i,
    input  logic [63:0] trap_arg6_i,
    input  logic [63:0] trap_arg7_i,
    input  logic        trap_mem_write_resp_valid_i,
    input  logic        trap_mem_write_fault_i,
    input  logic        trap_return_restore_valid_i,
    input  logic [1:0]  trap_return_restore_frontend_i,
    input  logic [63:0] trap_return_restore_pc_i,

    input  logic        abi_signature_set_i,
    input  logic [3:0]  abi_signature_set_slot_i,
    input  logic [7:0]  abi_signature_set_kind_i,
    input  logic [31:0] abi_signature_set_map_i,

    input  logic        cpuid_valid_i,
    input  logic [31:0] cpuid_leaf_i,
    input  logic [31:0] cpuid_subleaf_i,
    input  logic [7:0]  cycle_memory_response_cycles_i,

    output logic [1:0]  state_frontend_o,
    output logic [63:0] state_pc_o,
    output logic        state_update_o,
    output logic        state_hold_o,
    output logic        state_conflict_o,
    output logic        state_invalid_frontend_o,
    output logic        state_invalid_pc_o,
    output logic        state_error_o,
    output logic        redirect_valid_o,
    output logic [1:0]  redirect_frontend_o,
    output logic [63:0] redirect_pc_o,
    output logic [2:0]  redirect_reason_o,

    output logic        x86_fetch_req_valid_o,
    output logic [63:0] x86_fetch_req_addr_o,
    output logic [4:0]  x86_fetch_req_bytes_o,

    output logic        raw_mem_req_valid_o,
    output logic [63:0] raw_mem_req_addr_o,
    output logic [2:0]  raw_mem_req_bytes_o,

    output logic        wait_fetch_o,
    output logic        wait_execute_o,
    output logic        wait_retire_o,
    output logic        retire_o,
    output logic        commit_transition_o,
    output logic        commit_push_transition_o,
    output logic [1:0]  commit_frontend_o,
    output logic [63:0] commit_pc_o,
    output logic [6:0]  commit_signature_slot_o,

    output logic        transition_pop_valid_o,
    output logic [1:0]  transition_pop_frontend_o,
    output logic [63:0] transition_pop_pc_o,
    output logic [63:0] transition_pop_sp_o,
    output logic [31:0] transition_pop_flags_o,
    output logic        transition_stack_empty_o,
    output logic        transition_stack_full_o,
    output logic        transition_stack_overflow_o,
    output logic        transition_stack_underflow_o,
    output logic        transition_stack_conflict_o,
    output logic [3:0]  transition_stack_depth_o,
    output logic        transition_stack_unavailable_o,

    output logic        return_cookie_hit_o,
    output logic        return_recover_pop_o,
    output logic        return_resume_o,
    output logic [1:0]  return_resume_frontend_o,
    output logic [63:0] return_resume_pc_o,
    output logic [63:0] return_resume_sp_o,
    output logic [31:0] return_resume_flags_o,
    output logic        return_recover_error_o,
    output logic        return_recover_invalid_frontend_o,
    output logic        return_recover_missing_transition_o,
    output logic        return_recover_blocked_o,

    output logic        memory_retire_allowed_o,
    output logic        memory_enqueue_store_o,
    output logic        memory_wait_store_buffer_o,
    output logic        memory_wait_atomic_order_o,
    output logic        memory_barrier_noop_o,
    output logic        memory_aarch64_barrier_noop_o,
    output logic        memory_riscv_fence_noop_o,
    output logic        memory_weak_reorder_allowed_o,
    output logic        memory_invalid_frontend_o,
    output logic        memory_invalid_op_o,
    output logic        memory_fault_o,

    output logic        raw_data_mem_valid_o,
    output logic        raw_data_mem_load_o,
    output logic        raw_data_mem_store_o,
    output logic        raw_data_mem_atomic_o,
    output logic [3:0]  raw_data_mem_access_bytes_o,
    output logic        raw_data_mem_wait_o,
    output logic        raw_data_mem_fault_o,
    output logic        raw_branch_valid_o,
    output logic        raw_branch_unresolved_o,
    output logic        raw_branch_static_target_valid_o,
    output logic [63:0] raw_branch_static_target_o,
    output logic        raw_branch_wait_o,
    output logic        raw_branch_resolved_fault_o,

    output logic        interrupt_enter_x86_o,
    output logic        interrupt_save_interrupted_o,
    output logic [1:0]  interrupt_saved_frontend_o,
    output logic [63:0] interrupt_saved_pc_o,
    output logic        interrupt_restore_raw_o,
    output logic        interrupt_clear_interrupted_o,
    output logic [1:0]  interrupt_next_frontend_o,
    output logic [63:0] interrupt_next_pc_o,
    output logic        interrupted_valid_o,
    output logic [1:0]  interrupted_frontend_o,
    output logic [63:0] interrupted_pc_o,
    output logic        interrupt_error_o,
    output logic        interrupt_invalid_current_frontend_o,
    output logic        interrupt_invalid_current_pc_o,
    output logic        interrupt_invalid_interrupted_frontend_o,
    output logic        interrupt_invalid_interrupted_pc_o,

    output logic        trap_mem_write_valid_o,
    output logic [63:0] trap_mem_write_addr_o,
    output logic [7:0]  trap_mem_write_bytes_o,
    output logic [63:0] trap_mem_write_qword0_o,
    output logic [63:0] trap_mem_write_qword1_o,
    output logic [63:0] trap_mem_write_qword2_o,
    output logic [63:0] trap_mem_write_qword3_o,
    output logic [63:0] trap_mem_write_qword4_o,
    output logic [63:0] trap_mem_write_qword5_o,
    output logic [63:0] trap_mem_write_qword6_o,
    output logic [63:0] trap_mem_write_qword7_o,
    output logic [63:0] trap_mem_write_qword8_o,
    output logic [63:0] trap_mem_write_qword9_o,
    output logic [63:0] trap_mem_write_qword10_o,
    output logic [63:0] trap_mem_write_qword11_o,
    output logic [63:0] trap_mem_write_qword12_o,
    output logic [63:0] trap_mem_write_qword13_o,
    output logic [63:0] trap_mem_write_qword14_o,
    output logic [63:0] trap_mem_write_qword15_o,
    output logic        trap_wait_response_o,
    output logic        trap_packet_delivered_o,
    output logic        trap_fault_o,
    output logic        trap_encode_error_o,
    output logic        trap_packet_mem_fault_o,
    output logic        trap_monitor_disabled_o,
    output logic        trap_noncanonical_packet_o,
    output logic        trap_packet_align_fault_o,
    output logic        trap_packet_range_fault_o,
    output logic        trap_invalid_reason_o,
    output logic        trap_invalid_source_mode_o,
    output logic        trap_vector_apply_o,
    output logic [1:0]  trap_vector_frontend_o,
    output logic [63:0] trap_vector_pc_o,
    output logic        trap_return_decode_o,
    output logic        trap_return_restore_o,
    output logic [1:0]  trap_return_restore_frontend_o,
    output logic [63:0] trap_return_restore_pc_o,

    output logic        abi_signature_set_ok_o,
    output logic        abi_signature_set_error_o,
    output logic        abi_signature_apply_o,
    output logic        abi_signature_valid_o,
    output logic [7:0]  abi_signature_kind_o,
    output logic [6:0]  abi_signature_map_o,
    output logic        abi_signature_tls_base_o,

    output logic        cpuid_hit_o,
    output logic [31:0] cpuid_eax_o,
    output logic [31:0] cpuid_ebx_o,
    output logic [31:0] cpuid_ecx_o,
    output logic [31:0] cpuid_edx_o,

    output logic        cycle_budget_valid_o,
    output logic [7:0]  cycle_fixed_o,
    output logic [7:0]  cycle_variable_o,
    output logic [8:0]  cycle_total_o,
    output logic        cycle_few_cycle_fast_path_o,
    output logic        cycle_waits_for_memory_o,
    output logic        cycle_unsupported_o,
    output logic        cycle_invalid_op_o,
    output logic        cycle_blocked_o,

    output logic        fault_o,
    output logic [63:0] fault_pc_o,
    output logic        older_fault_o,
    output logic        fetch_fault_o,
    output logic        execute_fault_o,
    output logic        control_fault_o,
    output logic        invalid_frontend_o,
    output logic        x86_fetch_wait_o,
    output logic        x86_request_error_o,
    output logic        x86_mem_fault_o,
    output logic        x86_noncanonical_pc_o,
    output logic        x86_range_fault_o,

    output logic        poly_ctrl_o,
    output logic [6:0]  subop_o,
    output logic        raw_fetch_wait_o,
    output logic        raw_request_error_o,
    output logic        raw_mem_fault_o,
    output logic        raw_noncanonical_pc_o,
    output logic        raw_align_fault_o,
    output logic        raw_range_fault_o,
    output logic        invalid_subop_o,
    output logic        noncanonical_target_o,
    output logic        target_align_fault_o,
    output logic        invalid_signature_slot_o
);
  logic [1:0] state_frontend;
  logic [63:0] state_pc;
  logic state_interrupt_update;
  logic state_stall;
  logic raw_branch_target_valid;
  logic [63:0] raw_branch_target;
  logic [1:0] state_commit_frontend;
  logic [63:0] state_commit_pc;

  assign state_interrupt_update =
    interrupt_enter_x86_o || interrupt_restore_raw_o;
  assign state_stall = wait_fetch_o || wait_execute_o;
  assign state_commit_frontend =
    raw_branch_target_valid ? state_frontend : commit_frontend_o;
  assign state_commit_pc =
    raw_branch_target_valid ? raw_branch_target : commit_pc_o;
  assign state_frontend_o = state_frontend;
  assign state_pc_o = state_pc;

  poly_frontend_core frontend_core (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .valid_i(valid_i),
    .frontend_i(state_frontend),
    .pc_i(state_pc),
    .sp_i(sp_i),
    .transition_return_pc_i(transition_return_pc_i),
    .transition_flags_i(transition_flags_i),
    .x86_fetch_valid_i(x86_fetch_valid_i),
    .x86_fetch_fault_i(x86_fetch_fault_i),
    .x86_fetch_word_i(x86_fetch_word_i),
    .x86_fallthrough_pc_i(x86_fallthrough_pc_i),
    .raw_mem_resp_valid_i(raw_mem_resp_valid_i),
    .raw_mem_resp_fault_i(raw_mem_resp_fault_i),
    .raw_mem_resp_word_i(raw_mem_resp_word_i),
    .older_fault_i(older_fault_i),
    .execute_fault_i(execute_fault_i),
    .raw_branch_resolved_i(raw_branch_resolved_i),
    .raw_branch_taken_i(raw_branch_taken_i),
    .raw_branch_target_i(raw_branch_target_i),
    .raw_memory_resolved_i(raw_memory_resolved_i),
    .raw_memory_fault_i(raw_memory_fault_i),
    .memory_order_valid_i(memory_order_valid_i),
    .memory_load_i(memory_load_i),
    .memory_store_i(memory_store_i),
    .memory_atomic_i(memory_atomic_i),
    .memory_barrier_i(memory_barrier_i),
    .older_store_pending_i(older_store_pending_i),
    .store_buffer_full_i(store_buffer_full_i),
    .target_frontend_i(target_frontend_i),
    .target_pc_i(target_pc_i),
    .signature_slot_valid_i(signature_slot_valid_i),
    .transition_pop_i(transition_pop_i),
    .return_recover_valid_i(return_recover_valid_i),
    .return_target_pc_i(return_target_pc_i),
    .interrupt_feature_enabled_i(interrupt_feature_enabled_i),
    .cpl3_i(cpl3_i),
    .interrupt_i(interrupt_i),
    .user_return_i(user_return_i),
    .user_return_pc_i(user_return_pc_i),
    .trap_valid_i(trap_valid_i),
    .trap_monitor_enabled_i(trap_monitor_enabled_i),
    .trap_monitor_packet_addr_i(trap_monitor_packet_addr_i),
    .trap_vector_valid_i(trap_vector_valid_i),
    .trap_vector_frontend_i(trap_vector_frontend_i),
    .trap_vector_pc_i(trap_vector_pc_i),
    .trap_reason_i(trap_reason_i),
    .trap_source_mode_i(trap_source_mode_i),
    .trap_number_i(trap_number_i),
    .trap_selector_i(trap_selector_i),
    .trap_pc_i(trap_pc_i),
    .trap_resume_pc_i(trap_resume_pc_i),
    .trap_arg0_i(trap_arg0_i),
    .trap_arg1_i(trap_arg1_i),
    .trap_arg2_i(trap_arg2_i),
    .trap_arg3_i(trap_arg3_i),
    .trap_arg4_i(trap_arg4_i),
    .trap_arg5_i(trap_arg5_i),
    .trap_arg6_i(trap_arg6_i),
    .trap_arg7_i(trap_arg7_i),
    .trap_mem_write_resp_valid_i(trap_mem_write_resp_valid_i),
    .trap_mem_write_fault_i(trap_mem_write_fault_i),
    .trap_return_restore_valid_i(trap_return_restore_valid_i),
    .trap_return_restore_frontend_i(trap_return_restore_frontend_i),
    .trap_return_restore_pc_i(trap_return_restore_pc_i),
    .abi_signature_set_i(abi_signature_set_i),
    .abi_signature_set_slot_i(abi_signature_set_slot_i),
    .abi_signature_set_kind_i(abi_signature_set_kind_i),
    .abi_signature_set_map_i(abi_signature_set_map_i),
    .cpuid_valid_i(cpuid_valid_i),
    .cpuid_leaf_i(cpuid_leaf_i),
    .cpuid_subleaf_i(cpuid_subleaf_i),
    .cycle_memory_response_cycles_i(cycle_memory_response_cycles_i),
    .x86_fetch_req_valid_o(x86_fetch_req_valid_o),
    .x86_fetch_req_addr_o(x86_fetch_req_addr_o),
    .x86_fetch_req_bytes_o(x86_fetch_req_bytes_o),
    .raw_mem_req_valid_o(raw_mem_req_valid_o),
    .raw_mem_req_addr_o(raw_mem_req_addr_o),
    .raw_mem_req_bytes_o(raw_mem_req_bytes_o),
    .wait_fetch_o(wait_fetch_o),
    .wait_execute_o(wait_execute_o),
    .wait_retire_o(wait_retire_o),
    .retire_o(retire_o),
    .commit_transition_o(commit_transition_o),
    .commit_push_transition_o(commit_push_transition_o),
    .commit_frontend_o(commit_frontend_o),
    .commit_pc_o(commit_pc_o),
    .commit_signature_slot_o(commit_signature_slot_o),
    .transition_pop_valid_o(transition_pop_valid_o),
    .transition_pop_frontend_o(transition_pop_frontend_o),
    .transition_pop_pc_o(transition_pop_pc_o),
    .transition_pop_sp_o(transition_pop_sp_o),
    .transition_pop_flags_o(transition_pop_flags_o),
    .transition_stack_empty_o(transition_stack_empty_o),
    .transition_stack_full_o(transition_stack_full_o),
    .transition_stack_overflow_o(transition_stack_overflow_o),
    .transition_stack_underflow_o(transition_stack_underflow_o),
    .transition_stack_conflict_o(transition_stack_conflict_o),
    .transition_stack_depth_o(transition_stack_depth_o),
    .transition_stack_unavailable_o(transition_stack_unavailable_o),
    .return_cookie_hit_o(return_cookie_hit_o),
    .return_recover_pop_o(return_recover_pop_o),
    .return_resume_o(return_resume_o),
    .return_resume_frontend_o(return_resume_frontend_o),
    .return_resume_pc_o(return_resume_pc_o),
    .return_resume_sp_o(return_resume_sp_o),
    .return_resume_flags_o(return_resume_flags_o),
    .return_recover_error_o(return_recover_error_o),
    .return_recover_invalid_frontend_o(return_recover_invalid_frontend_o),
    .return_recover_missing_transition_o(return_recover_missing_transition_o),
    .return_recover_blocked_o(return_recover_blocked_o),
    .memory_retire_allowed_o(memory_retire_allowed_o),
    .memory_enqueue_store_o(memory_enqueue_store_o),
    .memory_wait_store_buffer_o(memory_wait_store_buffer_o),
    .memory_wait_atomic_order_o(memory_wait_atomic_order_o),
    .memory_barrier_noop_o(memory_barrier_noop_o),
    .memory_aarch64_barrier_noop_o(memory_aarch64_barrier_noop_o),
    .memory_riscv_fence_noop_o(memory_riscv_fence_noop_o),
    .memory_weak_reorder_allowed_o(memory_weak_reorder_allowed_o),
    .memory_invalid_frontend_o(memory_invalid_frontend_o),
    .memory_invalid_op_o(memory_invalid_op_o),
    .memory_fault_o(memory_fault_o),
    .raw_data_mem_valid_o(raw_data_mem_valid_o),
    .raw_data_mem_load_o(raw_data_mem_load_o),
    .raw_data_mem_store_o(raw_data_mem_store_o),
    .raw_data_mem_atomic_o(raw_data_mem_atomic_o),
    .raw_data_mem_access_bytes_o(raw_data_mem_access_bytes_o),
    .raw_data_mem_wait_o(raw_data_mem_wait_o),
    .raw_data_mem_fault_o(raw_data_mem_fault_o),
    .raw_branch_valid_o(raw_branch_valid_o),
    .raw_branch_unresolved_o(raw_branch_unresolved_o),
    .raw_branch_static_target_valid_o(raw_branch_static_target_valid_o),
    .raw_branch_static_target_o(raw_branch_static_target_o),
    .raw_branch_wait_o(raw_branch_wait_o),
    .raw_branch_resolved_fault_o(raw_branch_resolved_fault_o),
    .interrupt_enter_x86_o(interrupt_enter_x86_o),
    .interrupt_save_interrupted_o(interrupt_save_interrupted_o),
    .interrupt_saved_frontend_o(interrupt_saved_frontend_o),
    .interrupt_saved_pc_o(interrupt_saved_pc_o),
    .interrupt_restore_raw_o(interrupt_restore_raw_o),
    .interrupt_clear_interrupted_o(interrupt_clear_interrupted_o),
    .interrupt_next_frontend_o(interrupt_next_frontend_o),
    .interrupt_next_pc_o(interrupt_next_pc_o),
    .interrupted_valid_o(interrupted_valid_o),
    .interrupted_frontend_o(interrupted_frontend_o),
    .interrupted_pc_o(interrupted_pc_o),
    .interrupt_error_o(interrupt_error_o),
    .interrupt_invalid_current_frontend_o(interrupt_invalid_current_frontend_o),
    .interrupt_invalid_current_pc_o(interrupt_invalid_current_pc_o),
    .interrupt_invalid_interrupted_frontend_o(interrupt_invalid_interrupted_frontend_o),
    .interrupt_invalid_interrupted_pc_o(interrupt_invalid_interrupted_pc_o),
    .trap_mem_write_valid_o(trap_mem_write_valid_o),
    .trap_mem_write_addr_o(trap_mem_write_addr_o),
    .trap_mem_write_bytes_o(trap_mem_write_bytes_o),
    .trap_mem_write_qword0_o(trap_mem_write_qword0_o),
    .trap_mem_write_qword1_o(trap_mem_write_qword1_o),
    .trap_mem_write_qword2_o(trap_mem_write_qword2_o),
    .trap_mem_write_qword3_o(trap_mem_write_qword3_o),
    .trap_mem_write_qword4_o(trap_mem_write_qword4_o),
    .trap_mem_write_qword5_o(trap_mem_write_qword5_o),
    .trap_mem_write_qword6_o(trap_mem_write_qword6_o),
    .trap_mem_write_qword7_o(trap_mem_write_qword7_o),
    .trap_mem_write_qword8_o(trap_mem_write_qword8_o),
    .trap_mem_write_qword9_o(trap_mem_write_qword9_o),
    .trap_mem_write_qword10_o(trap_mem_write_qword10_o),
    .trap_mem_write_qword11_o(trap_mem_write_qword11_o),
    .trap_mem_write_qword12_o(trap_mem_write_qword12_o),
    .trap_mem_write_qword13_o(trap_mem_write_qword13_o),
    .trap_mem_write_qword14_o(trap_mem_write_qword14_o),
    .trap_mem_write_qword15_o(trap_mem_write_qword15_o),
    .trap_wait_response_o(trap_wait_response_o),
    .trap_packet_delivered_o(trap_packet_delivered_o),
    .trap_fault_o(trap_fault_o),
    .trap_encode_error_o(trap_encode_error_o),
    .trap_packet_mem_fault_o(trap_packet_mem_fault_o),
    .trap_monitor_disabled_o(trap_monitor_disabled_o),
    .trap_noncanonical_packet_o(trap_noncanonical_packet_o),
    .trap_packet_align_fault_o(trap_packet_align_fault_o),
    .trap_packet_range_fault_o(trap_packet_range_fault_o),
    .trap_invalid_reason_o(trap_invalid_reason_o),
    .trap_invalid_source_mode_o(trap_invalid_source_mode_o),
    .trap_vector_apply_o(trap_vector_apply_o),
    .trap_vector_frontend_o(trap_vector_frontend_o),
    .trap_vector_pc_o(trap_vector_pc_o),
    .trap_return_decode_o(trap_return_decode_o),
    .trap_return_restore_o(trap_return_restore_o),
    .trap_return_restore_frontend_o(trap_return_restore_frontend_o),
    .trap_return_restore_pc_o(trap_return_restore_pc_o),
    .abi_signature_set_ok_o(abi_signature_set_ok_o),
    .abi_signature_set_error_o(abi_signature_set_error_o),
    .abi_signature_apply_o(abi_signature_apply_o),
    .abi_signature_valid_o(abi_signature_valid_o),
    .abi_signature_kind_o(abi_signature_kind_o),
    .abi_signature_map_o(abi_signature_map_o),
    .abi_signature_tls_base_o(abi_signature_tls_base_o),
    .cpuid_hit_o(cpuid_hit_o),
    .cpuid_eax_o(cpuid_eax_o),
    .cpuid_ebx_o(cpuid_ebx_o),
    .cpuid_ecx_o(cpuid_ecx_o),
    .cpuid_edx_o(cpuid_edx_o),
    .cycle_budget_valid_o(cycle_budget_valid_o),
    .cycle_fixed_o(cycle_fixed_o),
    .cycle_variable_o(cycle_variable_o),
    .cycle_total_o(cycle_total_o),
    .cycle_few_cycle_fast_path_o(cycle_few_cycle_fast_path_o),
    .cycle_waits_for_memory_o(cycle_waits_for_memory_o),
    .cycle_unsupported_o(cycle_unsupported_o),
    .cycle_invalid_op_o(cycle_invalid_op_o),
    .cycle_blocked_o(cycle_blocked_o),
    .fault_o(fault_o),
    .fault_pc_o(fault_pc_o),
    .older_fault_o(older_fault_o),
    .fetch_fault_o(fetch_fault_o),
    .execute_fault_o(execute_fault_o),
    .control_fault_o(control_fault_o),
    .invalid_frontend_o(invalid_frontend_o),
    .x86_fetch_wait_o(x86_fetch_wait_o),
    .x86_request_error_o(x86_request_error_o),
    .x86_mem_fault_o(x86_mem_fault_o),
    .x86_noncanonical_pc_o(x86_noncanonical_pc_o),
    .x86_range_fault_o(x86_range_fault_o),
    .poly_ctrl_o(poly_ctrl_o),
    .subop_o(subop_o),
    .raw_branch_target_valid_o(raw_branch_target_valid),
    .raw_branch_target_o(raw_branch_target),
    .raw_fetch_wait_o(raw_fetch_wait_o),
    .raw_request_error_o(raw_request_error_o),
    .raw_mem_fault_o(raw_mem_fault_o),
    .raw_noncanonical_pc_o(raw_noncanonical_pc_o),
    .raw_align_fault_o(raw_align_fault_o),
    .raw_range_fault_o(raw_range_fault_o),
    .invalid_subop_o(invalid_subop_o),
    .noncanonical_target_o(noncanonical_target_o),
    .target_align_fault_o(target_align_fault_o),
    .invalid_signature_slot_o(invalid_signature_slot_o)
  );

  poly_frontend_state frontend_state (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .init_i(init_i),
    .init_frontend_i(init_frontend_i),
    .init_pc_i(init_pc_i),
    .commit_i(retire_o && !trap_return_restore_o),
    .commit_frontend_i(state_commit_frontend),
    .commit_pc_i(state_commit_pc),
    .interrupt_restore_i(state_interrupt_update),
    .interrupt_frontend_i(interrupt_next_frontend_o),
    .interrupt_pc_i(interrupt_next_pc_o),
    .return_resume_i(return_resume_o),
    .return_frontend_i(return_resume_frontend_o),
    .return_pc_i(return_resume_pc_o),
    .trap_vector_i(trap_vector_apply_o),
    .trap_frontend_i(trap_vector_frontend_o),
    .trap_pc_i(trap_vector_pc_o),
    .trap_return_i(trap_return_restore_o),
    .trap_return_frontend_i(trap_return_restore_frontend_o),
    .trap_return_pc_i(trap_return_restore_pc_o),
    .fault_i(fault_o),
    .stall_i(state_stall),
    .current_frontend_o(state_frontend),
    .current_pc_o(state_pc),
    .redirect_valid_o(redirect_valid_o),
    .redirect_frontend_o(redirect_frontend_o),
    .redirect_pc_o(redirect_pc_o),
    .redirect_reason_o(redirect_reason_o),
    .update_o(state_update_o),
    .hold_o(state_hold_o),
    .conflict_o(state_conflict_o),
    .invalid_frontend_o(state_invalid_frontend_o),
    .invalid_pc_o(state_invalid_pc_o),
    .error_o(state_error_o)
  );
endmodule
