#!/usr/bin/env python3
"""Integration checks for rtl/poly_frontend_fpga_top.sv."""

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RTL = ROOT / "rtl/poly_frontend_fpga_top.sv"
MAKEFILE = ROOT / "Makefile"


def main() -> int:
    text = RTL.read_text()
    makefile = MAKEFILE.read_text()

    required_fragments = [
        "module poly_frontend_fpga_top",
        "poly_frontend_stateful_core stateful_core",
        "instr_req_valid_o = x86_fetch_req_valid || raw_mem_req_valid",
        "instr_req_conflict_o = x86_fetch_req_valid && raw_mem_req_valid",
        "instr_req_frontend_o =",
        "instr_req_addr_o =",
        "instr_req_bytes_o =",
        "x86_resp_valid =",
        "raw_resp_valid =",
        "instr_resp_frontend_i == POLY_FRONTEND_X86",
        "instr_resp_frontend_i == POLY_FRONTEND_AARCH64",
        "instr_resp_frontend_i == POLY_FRONTEND_RISCV",
        "input  logic        raw_branch_resolved_i",
        "input  logic        raw_branch_taken_i",
        "input  logic [63:0] raw_branch_target_i",
        "input  logic [63:0] raw_data_mem_addr_i",
        "input  logic        raw_data_mem_resp_valid_i",
        "input  logic        raw_data_mem_resp_fault_i",
        "output logic        raw_data_mem_valid_o",
        "output logic [3:0]  raw_data_mem_access_bytes_o",
        "output logic        raw_data_mem_req_valid_o",
        "output logic [63:0] raw_data_mem_req_addr_o",
        "output logic [3:0]  raw_data_mem_req_bytes_o",
        "output logic        raw_data_mem_resp_wait_o",
        "output logic        raw_data_mem_resp_resolved_o",
        "output logic        raw_data_mem_resp_fault_o",
        "output logic        raw_branch_valid_o",
        "output logic        raw_branch_unresolved_o",
        "output logic        raw_branch_static_target_valid_o",
        "output logic [63:0] raw_branch_static_target_o",
        "output logic        raw_branch_wait_o",
        "output logic        raw_branch_resolved_fault_o",
        "output logic        abi_signature_set_ok_o",
        "output logic        abi_signature_set_error_o",
        "output logic        abi_signature_apply_o",
        "output logic        abi_signature_valid_o",
        "output logic [7:0]  abi_signature_kind_o",
        "output logic [6:0]  abi_signature_map_o",
        "output logic        abi_signature_tls_base_o",
        "output logic        cycle_budget_valid_o",
        "output logic [7:0]  cycle_fixed_o",
        "output logic [7:0]  cycle_variable_o",
        "output logic [8:0]  cycle_total_o",
        "output logic        cycle_few_cycle_fast_path_o",
        "output logic        cycle_waits_for_memory_o",
        "output logic        cycle_unsupported_o",
        "output logic        cycle_invalid_op_o",
        "output logic        cycle_blocked_o",
        "output logic        state_conflict_o",
        "output logic        state_invalid_frontend_o",
        "output logic        state_invalid_pc_o",
        "output logic        state_error_o",
        "output logic        transition_pop_valid_o",
        "output logic [1:0]  transition_pop_frontend_o",
        "output logic [63:0] transition_pop_pc_o",
        "output logic [63:0] transition_pop_sp_o",
        "output logic [31:0] transition_pop_flags_o",
        "output logic        transition_stack_overflow_o",
        "output logic        transition_stack_underflow_o",
        "output logic        transition_stack_conflict_o",
        "output logic        transition_stack_unavailable_o",
        "output logic [63:0] return_resume_sp_o",
        "output logic [31:0] return_resume_flags_o",
        "output logic        return_recover_error_o",
        "output logic        return_recover_invalid_frontend_o",
        "output logic        return_recover_missing_transition_o",
        "output logic        return_recover_blocked_o",
        "output logic        memory_retire_allowed_o",
        "output logic        memory_enqueue_store_o",
        "output logic        memory_wait_store_buffer_o",
        "output logic        memory_wait_atomic_order_o",
        "output logic        memory_barrier_noop_o",
        "output logic        memory_aarch64_barrier_noop_o",
        "output logic        memory_riscv_fence_noop_o",
        "output logic        memory_weak_reorder_allowed_o",
        "output logic        memory_invalid_frontend_o",
        "output logic        memory_invalid_op_o",
        "output logic        memory_fault_o",
        "output logic        older_fault_o",
        "output logic        x86_fetch_wait_o",
        "output logic        x86_request_error_o",
        "output logic        x86_mem_fault_o",
        "output logic        x86_noncanonical_pc_o",
        "output logic        x86_range_fault_o",
        "output logic        raw_fetch_wait_o",
        "output logic        raw_request_error_o",
        "output logic        raw_mem_fault_o",
        "output logic        raw_noncanonical_pc_o",
        "output logic        raw_align_fault_o",
        "output logic        raw_range_fault_o",
        "output logic        invalid_subop_o",
        "output logic        noncanonical_target_o",
        "output logic        target_align_fault_o",
        "output logic        invalid_signature_slot_o",
        "output logic        interrupt_enter_x86_o",
        "output logic        interrupt_save_interrupted_o",
        "output logic [1:0]  interrupt_saved_frontend_o",
        "output logic [63:0] interrupt_saved_pc_o",
        "output logic        interrupt_restore_raw_o",
        "output logic        interrupt_clear_interrupted_o",
        "output logic [1:0]  interrupt_next_frontend_o",
        "output logic [63:0] interrupt_next_pc_o",
        "output logic        interrupted_valid_o",
        "output logic [1:0]  interrupted_frontend_o",
        "output logic [63:0] interrupted_pc_o",
        "output logic        interrupt_error_o",
        "output logic        interrupt_invalid_current_frontend_o",
        "output logic        interrupt_invalid_current_pc_o",
        "output logic        interrupt_invalid_interrupted_frontend_o",
        "output logic        interrupt_invalid_interrupted_pc_o",
        "input  logic        trap_vector_valid_i",
        "input  logic [1:0]  trap_vector_frontend_i",
        "input  logic [63:0] trap_vector_pc_i",
        "output logic        trap_encode_error_o",
        "output logic [63:0] trap_mem_write_qword0_o",
        "output logic [63:0] trap_mem_write_qword1_o",
        "output logic [63:0] trap_mem_write_qword2_o",
        "output logic [63:0] trap_mem_write_qword3_o",
        "output logic [63:0] trap_mem_write_qword4_o",
        "output logic [63:0] trap_mem_write_qword5_o",
        "output logic [63:0] trap_mem_write_qword6_o",
        "output logic [63:0] trap_mem_write_qword7_o",
        "output logic [63:0] trap_mem_write_qword8_o",
        "output logic [63:0] trap_mem_write_qword9_o",
        "output logic [63:0] trap_mem_write_qword10_o",
        "output logic [63:0] trap_mem_write_qword11_o",
        "output logic [63:0] trap_mem_write_qword12_o",
        "output logic [63:0] trap_mem_write_qword13_o",
        "output logic [63:0] trap_mem_write_qword14_o",
        "output logic [63:0] trap_mem_write_qword15_o",
        "output logic        trap_packet_mem_fault_o",
        "output logic        trap_monitor_disabled_o",
        "output logic        trap_noncanonical_packet_o",
        "output logic        trap_packet_align_fault_o",
        "output logic        trap_packet_range_fault_o",
        "output logic        trap_invalid_reason_o",
        "output logic        trap_invalid_source_mode_o",
        "output logic        trap_vector_apply_o",
        "output logic [1:0]  trap_vector_frontend_o",
        "output logic [63:0] trap_vector_pc_o",
        "input  logic        trap_return_restore_valid_i",
        "input  logic [1:0]  trap_return_restore_frontend_i",
        "input  logic [63:0] trap_return_restore_pc_i",
        "output logic        trap_return_decode_o",
        "output logic        trap_return_restore_o",
        "output logic [1:0]  trap_return_restore_frontend_o",
        "output logic [63:0] trap_return_restore_pc_o",
        "poly_raw_data_mem_request raw_data_mem_request",
        "poly_raw_data_mem_response_stage raw_data_mem_response_stage",
        ".addr_i(raw_data_mem_addr_i)",
        ".request_valid_o(raw_data_mem_req_valid)",
        ".request_addr_o(raw_data_mem_req_addr)",
        ".request_bytes_o(raw_data_mem_req_bytes)",
        ".request_valid_i(raw_data_mem_req_valid)",
        ".request_error_i(raw_data_mem_req_error)",
        ".mem_resp_valid_i(raw_data_mem_resp_valid_i)",
        ".mem_resp_fault_i(raw_data_mem_resp_fault_i)",
        ".resolved_o(raw_memory_resolved)",
        ".fault_o(raw_memory_fault)",
        ".x86_fetch_valid_i(x86_resp_valid)",
        ".raw_mem_resp_valid_i(raw_resp_valid)",
        ".raw_branch_resolved_i(raw_branch_resolved_i)",
        ".raw_branch_taken_i(raw_branch_taken_i)",
        ".raw_branch_target_i(raw_branch_target_i)",
        ".raw_branch_valid_o(raw_branch_valid_o)",
        ".raw_branch_unresolved_o(raw_branch_unresolved_o)",
        ".raw_branch_static_target_valid_o(raw_branch_static_target_valid_o)",
        ".raw_branch_static_target_o(raw_branch_static_target_o)",
        ".raw_branch_wait_o(raw_branch_wait_o)",
        ".raw_branch_resolved_fault_o(raw_branch_resolved_fault_o)",
        ".abi_signature_set_ok_o(abi_signature_set_ok_o)",
        ".abi_signature_set_error_o(abi_signature_set_error_o)",
        ".abi_signature_apply_o(abi_signature_apply_o)",
        ".abi_signature_valid_o(abi_signature_valid_o)",
        ".abi_signature_kind_o(abi_signature_kind_o)",
        ".abi_signature_map_o(abi_signature_map_o)",
        ".abi_signature_tls_base_o(abi_signature_tls_base_o)",
        ".cycle_budget_valid_o(cycle_budget_valid_o)",
        ".cycle_fixed_o(cycle_fixed_o)",
        ".cycle_variable_o(cycle_variable_o)",
        ".cycle_total_o(cycle_total_o)",
        ".cycle_few_cycle_fast_path_o(cycle_few_cycle_fast_path_o)",
        ".cycle_waits_for_memory_o(cycle_waits_for_memory_o)",
        ".cycle_unsupported_o(cycle_unsupported_o)",
        ".cycle_invalid_op_o(cycle_invalid_op_o)",
        ".cycle_blocked_o(cycle_blocked_o)",
        ".state_conflict_o(state_conflict_o)",
        ".state_invalid_frontend_o(state_invalid_frontend_o)",
        ".state_invalid_pc_o(state_invalid_pc_o)",
        ".state_error_o(state_error_o)",
        ".transition_pop_valid_o(transition_pop_valid_o)",
        ".transition_pop_frontend_o(transition_pop_frontend_o)",
        ".transition_pop_pc_o(transition_pop_pc_o)",
        ".transition_pop_sp_o(transition_pop_sp_o)",
        ".transition_pop_flags_o(transition_pop_flags_o)",
        ".transition_stack_overflow_o(transition_stack_overflow_o)",
        ".transition_stack_underflow_o(transition_stack_underflow_o)",
        ".transition_stack_conflict_o(transition_stack_conflict_o)",
        ".transition_stack_unavailable_o(transition_stack_unavailable_o)",
        ".return_resume_sp_o(return_resume_sp_o)",
        ".return_resume_flags_o(return_resume_flags_o)",
        ".return_recover_error_o(return_recover_error_o)",
        ".return_recover_invalid_frontend_o(return_recover_invalid_frontend_o)",
        ".return_recover_missing_transition_o(return_recover_missing_transition_o)",
        ".return_recover_blocked_o(return_recover_blocked_o)",
        ".memory_retire_allowed_o(memory_retire_allowed_o)",
        ".memory_enqueue_store_o(memory_enqueue_store_o)",
        ".memory_wait_store_buffer_o(memory_wait_store_buffer_o)",
        ".memory_wait_atomic_order_o(memory_wait_atomic_order_o)",
        ".memory_barrier_noop_o(memory_barrier_noop_o)",
        ".memory_aarch64_barrier_noop_o(memory_aarch64_barrier_noop_o)",
        ".memory_riscv_fence_noop_o(memory_riscv_fence_noop_o)",
        ".memory_weak_reorder_allowed_o(memory_weak_reorder_allowed_o)",
        ".memory_invalid_frontend_o(memory_invalid_frontend_o)",
        ".memory_invalid_op_o(memory_invalid_op_o)",
        ".memory_fault_o(memory_fault_o)",
        ".older_fault_o(older_fault_o)",
        ".x86_fetch_wait_o(x86_fetch_wait_o)",
        ".x86_request_error_o(x86_request_error_o)",
        ".x86_mem_fault_o(x86_mem_fault_o)",
        ".x86_noncanonical_pc_o(x86_noncanonical_pc_o)",
        ".x86_range_fault_o(x86_range_fault_o)",
        ".raw_fetch_wait_o(raw_fetch_wait_o)",
        ".raw_request_error_o(raw_request_error_o)",
        ".raw_mem_fault_o(raw_mem_fault_o)",
        ".raw_noncanonical_pc_o(raw_noncanonical_pc_o)",
        ".raw_align_fault_o(raw_align_fault_o)",
        ".raw_range_fault_o(raw_range_fault_o)",
        ".invalid_subop_o(invalid_subop_o)",
        ".noncanonical_target_o(noncanonical_target_o)",
        ".target_align_fault_o(target_align_fault_o)",
        ".invalid_signature_slot_o(invalid_signature_slot_o)",
        ".interrupt_enter_x86_o(interrupt_enter_x86_o)",
        ".interrupt_save_interrupted_o(interrupt_save_interrupted_o)",
        ".interrupt_saved_frontend_o(interrupt_saved_frontend_o)",
        ".interrupt_saved_pc_o(interrupt_saved_pc_o)",
        ".interrupt_restore_raw_o(interrupt_restore_raw_o)",
        ".interrupt_clear_interrupted_o(interrupt_clear_interrupted_o)",
        ".interrupt_next_frontend_o(interrupt_next_frontend_o)",
        ".interrupt_next_pc_o(interrupt_next_pc_o)",
        ".interrupted_valid_o(interrupted_valid_o)",
        ".interrupted_frontend_o(interrupted_frontend_o)",
        ".interrupted_pc_o(interrupted_pc_o)",
        ".interrupt_error_o(interrupt_error_o)",
        ".interrupt_invalid_current_frontend_o(interrupt_invalid_current_frontend_o)",
        ".interrupt_invalid_current_pc_o(interrupt_invalid_current_pc_o)",
        ".interrupt_invalid_interrupted_frontend_o(interrupt_invalid_interrupted_frontend_o)",
        ".interrupt_invalid_interrupted_pc_o(interrupt_invalid_interrupted_pc_o)",
        ".trap_vector_valid_i(trap_vector_valid_i)",
        ".trap_vector_frontend_i(trap_vector_frontend_i)",
        ".trap_vector_pc_i(trap_vector_pc_i)",
        ".trap_mem_write_qword0_o(trap_mem_write_qword0_o)",
        ".trap_mem_write_qword1_o(trap_mem_write_qword1_o)",
        ".trap_mem_write_qword2_o(trap_mem_write_qword2_o)",
        ".trap_mem_write_qword3_o(trap_mem_write_qword3_o)",
        ".trap_mem_write_qword4_o(trap_mem_write_qword4_o)",
        ".trap_mem_write_qword5_o(trap_mem_write_qword5_o)",
        ".trap_mem_write_qword6_o(trap_mem_write_qword6_o)",
        ".trap_mem_write_qword7_o(trap_mem_write_qword7_o)",
        ".trap_mem_write_qword8_o(trap_mem_write_qword8_o)",
        ".trap_mem_write_qword9_o(trap_mem_write_qword9_o)",
        ".trap_mem_write_qword10_o(trap_mem_write_qword10_o)",
        ".trap_mem_write_qword11_o(trap_mem_write_qword11_o)",
        ".trap_mem_write_qword12_o(trap_mem_write_qword12_o)",
        ".trap_mem_write_qword13_o(trap_mem_write_qword13_o)",
        ".trap_mem_write_qword14_o(trap_mem_write_qword14_o)",
        ".trap_mem_write_qword15_o(trap_mem_write_qword15_o)",
        ".trap_encode_error_o(trap_encode_error_o)",
        ".trap_packet_mem_fault_o(trap_packet_mem_fault_o)",
        ".trap_monitor_disabled_o(trap_monitor_disabled_o)",
        ".trap_noncanonical_packet_o(trap_noncanonical_packet_o)",
        ".trap_packet_align_fault_o(trap_packet_align_fault_o)",
        ".trap_packet_range_fault_o(trap_packet_range_fault_o)",
        ".trap_invalid_reason_o(trap_invalid_reason_o)",
        ".trap_invalid_source_mode_o(trap_invalid_source_mode_o)",
        ".trap_vector_apply_o(trap_vector_apply_o)",
        ".trap_vector_frontend_o(trap_vector_frontend_o)",
        ".trap_vector_pc_o(trap_vector_pc_o)",
        ".trap_return_restore_valid_i(trap_return_restore_valid_i)",
        ".trap_return_restore_frontend_i(trap_return_restore_frontend_i)",
        ".trap_return_restore_pc_i(trap_return_restore_pc_i)",
        ".trap_return_decode_o(trap_return_decode_o)",
        ".trap_return_restore_o(trap_return_restore_o)",
        ".trap_return_restore_frontend_o(trap_return_restore_frontend_o)",
        ".trap_return_restore_pc_o(trap_return_restore_pc_o)",
        ".raw_memory_resolved_i(raw_memory_resolved)",
        ".raw_memory_fault_i(raw_memory_fault)",
        ".raw_data_mem_valid_o(raw_data_mem_valid)",
        ".raw_data_mem_access_bytes_o(raw_data_mem_access_bytes)",
        "assign raw_data_mem_valid_o = raw_data_mem_valid",
        "assign raw_data_mem_access_bytes_o = raw_data_mem_access_bytes",
        "assign raw_data_mem_req_valid_o = raw_data_mem_req_valid",
        "assign raw_data_mem_req_addr_o = raw_data_mem_req_addr",
        "assign raw_data_mem_req_bytes_o = raw_data_mem_req_bytes",
        "assign raw_data_mem_resp_resolved_o = raw_memory_resolved",
        "assign raw_data_mem_resp_fault_o = raw_memory_fault",
        ".x86_fetch_req_valid_o(x86_fetch_req_valid)",
        ".raw_mem_req_valid_o(raw_mem_req_valid)",
    ]
    for fragment in required_fragments:
        if fragment not in text:
            raise AssertionError(f"missing fpga-top wiring: {fragment}")

    forbidden_fragments = [
        "handle_poly_syscall",
        "libcall",
        "strlen",
        "memcpy",
        "#UD",
    ]
    lowered = text.lower()
    for fragment in forbidden_fragments:
        if fragment.lower() in lowered:
            raise AssertionError(f"fpga top should not contain policy fragment: {fragment}")

    assert "POLY_RTL_TOP ?= poly_frontend_fpga_top" in makefile
    assert "rtl/poly_frontend_fpga_top.sv" in makefile
    assert "rtl/poly_raw_data_mem_request.sv" in makefile
    assert "rtl/poly_raw_data_mem_response_stage.sv" in makefile
    assert "python3 rtl/test_poly_frontend_fpga_top.py" in makefile
    assert "python3 rtl/test_poly_raw_data_mem_request.py" in makefile
    assert "python3 rtl/test_poly_raw_data_mem_response_stage.py" in makefile

    print("POLY_RTL_FRONTEND_FPGA_TOP_OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
