#ifndef POLYCPUID_H
#define POLYCPUID_H

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#define POLY_AARCH64_CTRL_ENCODING(subop) \
  (0xd503201fU | (((uint32_t) (subop) & 0x7fU) << 5))
#define POLY_RISCV_CTRL_ENCODING(subop) \
  (0x0000700bU | (((uint32_t) (subop) & 0x7fU) << 25))

#define POLY_AARCH64_CTRL_X86_ESCAPE \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_X86_ESCAPE)
#define POLY_AARCH64_CTRL_TRAP_RETURN \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_TRAP_RETURN)
#define POLY_AARCH64_CTRL_SWITCH_MODE \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_SWITCH_MODE)
#define POLY_AARCH64_CTRL_CALL_MODE \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_CALL_MODE)
#define POLY_AARCH64_CTRL_CALL_SIG_MODE \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_CALL_SIG_MODE)
#define POLY_AARCH64_CTRL_CALL_SIG_IMM(slot) \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_CALL_SIG_IMM_BASE + \
    ((uint32_t) (slot)))
#define POLY_AARCH64_CTRL_TRAP_VECTOR_SET \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_TRAP_VECTOR_SET)
#define POLY_AARCH64_CTRL_TRAP_VECTOR_GET \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_TRAP_VECTOR_GET)
#define POLY_AARCH64_CTRL_TRAP_VECTOR_MODE_SET \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_TRAP_VECTOR_MODE_SET)
#define POLY_AARCH64_CTRL_TRAP_VECTOR_MODE_GET \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_TRAP_VECTOR_MODE_GET)
#define POLY_AARCH64_CTRL_MONITOR_PACKET_SET \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_MONITOR_PACKET_SET)
#define POLY_AARCH64_CTRL_MONITOR_PACKET_GET \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_MONITOR_PACKET_GET)
#define POLY_AARCH64_CTRL_STATE_KEY_SET \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_STATE_KEY_SET)
#define POLY_AARCH64_CTRL_STATE_KEY_GET \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_STATE_KEY_GET)
#define POLY_AARCH64_CTRL_LANDING \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_LANDING)
#define POLY_AARCH64_CTRL_ABI_SIGNATURE_SET \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_ABI_SIGNATURE_SET)
#define POLY_AARCH64_CTRL_ABI_SIGNATURE_GET \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_ABI_SIGNATURE_GET)
#define POLY_AARCH64_CTRL_LANDING_POLICY_SET \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_LANDING_POLICY_SET)
#define POLY_AARCH64_CTRL_LANDING_POLICY_GET \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_LANDING_POLICY_GET)

#define POLY_RISCV_CTRL_X86_ESCAPE \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_X86_ESCAPE)
#define POLY_RISCV_CTRL_TRAP_RETURN \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_TRAP_RETURN)
#define POLY_RISCV_CTRL_SWITCH_MODE \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_SWITCH_MODE)
#define POLY_RISCV_CTRL_CALL_MODE \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_CALL_MODE)
#define POLY_RISCV_CTRL_CALL_SIG_MODE \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_CALL_SIG_MODE)
#define POLY_RISCV_CTRL_CALL_SIG_IMM(slot) \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_CALL_SIG_IMM_BASE + \
    ((uint32_t) (slot)))
#define POLY_RISCV_CTRL_TRAP_VECTOR_SET \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_TRAP_VECTOR_SET)
#define POLY_RISCV_CTRL_TRAP_VECTOR_GET \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_TRAP_VECTOR_GET)
#define POLY_RISCV_CTRL_TRAP_VECTOR_MODE_SET \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_TRAP_VECTOR_MODE_SET)
#define POLY_RISCV_CTRL_TRAP_VECTOR_MODE_GET \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_TRAP_VECTOR_MODE_GET)
#define POLY_RISCV_CTRL_MONITOR_PACKET_SET \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_MONITOR_PACKET_SET)
#define POLY_RISCV_CTRL_MONITOR_PACKET_GET \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_MONITOR_PACKET_GET)
#define POLY_RISCV_CTRL_STATE_KEY_SET \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_STATE_KEY_SET)
#define POLY_RISCV_CTRL_STATE_KEY_GET \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_STATE_KEY_GET)
#define POLY_RISCV_CTRL_LANDING \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_LANDING)
#define POLY_RISCV_CTRL_ABI_SIGNATURE_SET \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_ABI_SIGNATURE_SET)
#define POLY_RISCV_CTRL_ABI_SIGNATURE_GET \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_ABI_SIGNATURE_GET)
#define POLY_RISCV_CTRL_LANDING_POLICY_SET \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_LANDING_POLICY_SET)
#define POLY_RISCV_CTRL_LANDING_POLICY_GET \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_LANDING_POLICY_GET)

#define POLY_X86_CTRL_ASM_BYTE(subop) ".byte 0x0f,0x3a,0xfc," #subop "\n"
#define POLY_X86_CTRL_PENTER_MODE_ASM POLY_X86_CTRL_ASM_BYTE(0x03)
#define POLY_X86_CTRL_PSWITCH_MODE_ASM POLY_X86_CTRL_ASM_BYTE(0x04)
#define POLY_X86_CTRL_LANDING_ASM POLY_X86_CTRL_ASM_BYTE(0x05)
#define POLY_X86_CTRL_IMPORT_RETURN_ASM POLY_X86_CTRL_ASM_BYTE(0x20)
#define POLY_X86_CTRL_PCALL_SIG_MODE_ASM POLY_X86_CTRL_ASM_BYTE(0x2d)
#define POLY_X86_CTRL_PCALL_SIG_IMM_SLOT0_ASM POLY_X86_CTRL_ASM_BYTE(0x30)
#define POLY_X86_CTRL_PCALL_SIG_IMM_X86_SYSV_REGS_ASM \
  POLY_X86_CTRL_ASM_BYTE(0x31)
#define POLY_X86_CTRL_PCALL_SIG_IMM_NATIVE_REGS_ASM \
  POLY_X86_CTRL_ASM_BYTE(0x33)
#define POLY_X86_CTRL_PCALL_SIG_IMM_NATIVE_REGS_FP64_ASM \
  POLY_X86_CTRL_ASM_BYTE(0x38)
#define POLY_X86_CTRL_PCALL_SIG_IMM_INVALID_SLOT_ASM \
  POLY_X86_CTRL_ASM_BYTE(0x3b)
#define POLY_X86_CTRL_SWITCH_COUNT_STATUS_ASM POLY_X86_CTRL_ASM_BYTE(0x40)
#define POLY_X86_CTRL_FOREIGN_INSN_COUNT_STATUS_ASM \
  POLY_X86_CTRL_ASM_BYTE(0x42)
#define POLY_X86_CTRL_FOREIGN_SYSCALL_COUNT_STATUS_ASM \
  POLY_X86_CTRL_ASM_BYTE(0x43)
#define POLY_X86_CTRL_FOREIGN_BREAK_COUNT_STATUS_ASM \
  POLY_X86_CTRL_ASM_BYTE(0x44)
#define POLY_X86_CTRL_FOREIGN_IMPORT_COUNT_STATUS_ASM \
  POLY_X86_CTRL_ASM_BYTE(0x45)
#define POLY_X86_CTRL_TRAP_VECTOR_SET_ASM POLY_X86_CTRL_ASM_BYTE(0x60)
#define POLY_X86_CTRL_TRAP_VECTOR_GET_ASM POLY_X86_CTRL_ASM_BYTE(0x61)
#define POLY_X86_CTRL_TRAP_RETURN_ASM POLY_X86_CTRL_ASM_BYTE(0x62)
#define POLY_X86_CTRL_TRAP_VECTOR_MODE_SET_ASM POLY_X86_CTRL_ASM_BYTE(0x63)
#define POLY_X86_CTRL_TRAP_VECTOR_MODE_GET_ASM POLY_X86_CTRL_ASM_BYTE(0x64)
#define POLY_X86_CTRL_STATE_KEY_SET_ASM POLY_X86_CTRL_ASM_BYTE(0x65)
#define POLY_X86_CTRL_STATE_KEY_GET_ASM POLY_X86_CTRL_ASM_BYTE(0x66)
#define POLY_X86_CTRL_STATE_EXPORT_ASM POLY_X86_CTRL_ASM_BYTE(0x67)
#define POLY_X86_CTRL_STATE_IMPORT_ASM POLY_X86_CTRL_ASM_BYTE(0x68)
#define POLY_X86_CTRL_ABI_SIGNATURE_SET_ASM POLY_X86_CTRL_ASM_BYTE(0x69)
#define POLY_X86_CTRL_ABI_SIGNATURE_GET_ASM POLY_X86_CTRL_ASM_BYTE(0x6a)
#define POLY_X86_CTRL_MONITOR_PACKET_SET_ASM POLY_X86_CTRL_ASM_BYTE(0x6b)
#define POLY_X86_CTRL_MONITOR_PACKET_GET_ASM POLY_X86_CTRL_ASM_BYTE(0x6c)
#define POLY_X86_CTRL_LANDING_POLICY_SET_ASM POLY_X86_CTRL_ASM_BYTE(0x6d)
#define POLY_X86_CTRL_LANDING_POLICY_GET_ASM POLY_X86_CTRL_ASM_BYTE(0x6e)
#define POLY_X86_CTRL_PCALL_SIG_IMM(slot) \
  (POLY_X86_CTRL_PCALL_SIG_IMM_BASE + ((uint32_t) (slot)))

enum {
  POLY_FRONTEND_X86 = 0,
  POLY_FRONTEND_AARCH64 = 1,
  POLY_FRONTEND_RISCV = 2,
  POLY_FRONTEND_COUNT = 3,
  POLY_MODE_X86 = 0,
  POLY_MODE_RAW_AARCH64 = POLY_FRONTEND_AARCH64,
  POLY_MODE_RAW_RISCV = POLY_FRONTEND_RISCV,
  POLY_TRAP_SYSCALL = 1,
  POLY_TRAP_BREAK = 2,
  POLY_TRAP_IMPORT = 3,
  POLY_TRAP_ILLEGAL = 4,
  POLY_CPUID_BASE = 0x40000000,
  POLY_CPUID_MAX = 0x40000009,
  POLY_CPUID_ABI_VERSION = 1,
  POLY_AARCH64_CTRL_SUBOP_CALL_SIG_IMM_BASE = 0x50,
  POLY_AARCH64_CTRL_SUBOP_TRAP_VECTOR_SET = 0x68,
  POLY_AARCH64_CTRL_SUBOP_TRAP_VECTOR_GET = 0x69,
  POLY_AARCH64_CTRL_SUBOP_TRAP_VECTOR_MODE_SET = 0x6a,
  POLY_AARCH64_CTRL_SUBOP_TRAP_VECTOR_MODE_GET = 0x6b,
  POLY_AARCH64_CTRL_SUBOP_MONITOR_PACKET_SET = 0x6c,
  POLY_AARCH64_CTRL_SUBOP_MONITOR_PACKET_GET = 0x6d,
  POLY_AARCH64_CTRL_SUBOP_STATE_KEY_SET = 0x6e,
  POLY_AARCH64_CTRL_SUBOP_STATE_KEY_GET = 0x6f,
  POLY_AARCH64_CTRL_SUBOP_X86_ESCAPE = 0x70,
  POLY_AARCH64_CTRL_SUBOP_TRAP_RETURN = 0x76,
  POLY_AARCH64_CTRL_SUBOP_SWITCH_MODE = 0x78,
  POLY_AARCH64_CTRL_SUBOP_CALL_MODE = 0x79,
  POLY_AARCH64_CTRL_SUBOP_CALL_SIG_MODE = 0x7a,
  POLY_AARCH64_CTRL_SUBOP_LANDING = 0x7b,
  POLY_AARCH64_CTRL_SUBOP_ABI_SIGNATURE_SET = 0x7c,
  POLY_AARCH64_CTRL_SUBOP_ABI_SIGNATURE_GET = 0x7d,
  POLY_AARCH64_CTRL_SUBOP_LANDING_POLICY_SET = 0x7e,
  POLY_AARCH64_CTRL_SUBOP_LANDING_POLICY_GET = 0x7f,
  POLY_RISCV_CTRL_SUBOP_X86_ESCAPE = 0,
  POLY_RISCV_CTRL_SUBOP_TRAP_RETURN = 6,
  POLY_RISCV_CTRL_SUBOP_SWITCH_MODE = 8,
  POLY_RISCV_CTRL_SUBOP_CALL_MODE = 9,
  POLY_RISCV_CTRL_SUBOP_CALL_SIG_MODE = 10,
  POLY_RISCV_CTRL_SUBOP_LANDING = 11,
  POLY_RISCV_CTRL_SUBOP_ABI_SIGNATURE_SET = 12,
  POLY_RISCV_CTRL_SUBOP_ABI_SIGNATURE_GET = 13,
  POLY_RISCV_CTRL_SUBOP_STATE_KEY_SET = 14,
  POLY_RISCV_CTRL_SUBOP_STATE_KEY_GET = 15,
  POLY_RISCV_CTRL_SUBOP_CALL_SIG_IMM_BASE = 32,
  POLY_RISCV_CTRL_SUBOP_TRAP_VECTOR_SET = 24,
  POLY_RISCV_CTRL_SUBOP_TRAP_VECTOR_GET = 25,
  POLY_RISCV_CTRL_SUBOP_TRAP_VECTOR_MODE_SET = 26,
  POLY_RISCV_CTRL_SUBOP_TRAP_VECTOR_MODE_GET = 27,
  POLY_RISCV_CTRL_SUBOP_MONITOR_PACKET_SET = 28,
  POLY_RISCV_CTRL_SUBOP_MONITOR_PACKET_GET = 29,
  POLY_RISCV_CTRL_SUBOP_LANDING_POLICY_SET = 30,
  POLY_RISCV_CTRL_SUBOP_LANDING_POLICY_GET = 31,
  POLY_X86_CTRL_PREFIX_0 = 0x0f,
  POLY_X86_CTRL_PREFIX_1 = 0x3a,
  POLY_X86_CTRL_PREFIX_2 = 0xfc,
  POLY_X86_CTRL_PENTER_MODE = 0x03,
  POLY_X86_CTRL_PSWITCH_MODE = 0x04,
  POLY_X86_CTRL_LANDING = 0x05,
  POLY_X86_CTRL_IMPORT_RETURN = 0x20,
  POLY_X86_CTRL_PCALL_SIG_MODE = 0x2d,
  POLY_X86_CTRL_PCALL_SIG_IMM_BASE = 0x30,
  POLY_X86_CTRL_SWITCH_COUNT_STATUS = 0x40,
  POLY_X86_CTRL_FOREIGN_INSN_COUNT_STATUS = 0x42,
  POLY_X86_CTRL_FOREIGN_SYSCALL_COUNT_STATUS = 0x43,
  POLY_X86_CTRL_FOREIGN_BREAK_COUNT_STATUS = 0x44,
  POLY_X86_CTRL_FOREIGN_IMPORT_COUNT_STATUS = 0x45,
  POLY_X86_CTRL_TRAP_VECTOR_SET = 0x60,
  POLY_X86_CTRL_TRAP_VECTOR_GET = 0x61,
  POLY_X86_CTRL_TRAP_RETURN = 0x62,
  POLY_X86_CTRL_TRAP_VECTOR_MODE_SET = 0x63,
  POLY_X86_CTRL_TRAP_VECTOR_MODE_GET = 0x64,
  POLY_X86_CTRL_STATE_KEY_SET = 0x65,
  POLY_X86_CTRL_STATE_KEY_GET = 0x66,
  POLY_X86_CTRL_STATE_EXPORT = 0x67,
  POLY_X86_CTRL_STATE_IMPORT = 0x68,
  POLY_X86_CTRL_ABI_SIGNATURE_SET = 0x69,
  POLY_X86_CTRL_ABI_SIGNATURE_GET = 0x6a,
  POLY_X86_CTRL_MONITOR_PACKET_SET = 0x6b,
  POLY_X86_CTRL_MONITOR_PACKET_GET = 0x6c,
  POLY_X86_CTRL_LANDING_POLICY_SET = 0x6d,
  POLY_X86_CTRL_LANDING_POLICY_GET = 0x6e,
  POLY_CPUID_FEATURE_RAW_AARCH64 = (1U << 0),
  POLY_CPUID_FEATURE_RAW_RISCV = (1U << 1),
  POLY_CPUID_FEATURE_NEUTRAL_SWITCH = (1U << 2),
  POLY_CPUID_FEATURE_NATIVE_RET = (1U << 3),
  POLY_CPUID_FEATURE_PCALL_SYSV = (1U << 4),
  POLY_CPUID_FEATURE_PCALL_SRET = (1U << 5),
  POLY_CPUID_FEATURE_FP_BRIDGE = (1U << 6),
  POLY_CPUID_FEATURE_TRAP_RECORDS = (1U << 7),
  POLY_CPUID_FEATURE_USER_RETURN_RESTORE = (1U << 8),
  POLY_CPUID_FEATURE_X86_TSO = (1U << 9),
  POLY_CPUID_FEATURE_PER_THREAD_STATE = (1U << 10),
  POLY_CPUID_FEATURE_GENERIC_FRONTEND_IDS = (1U << 11),
  POLY_CPUID_FEATURE_X86_POLY_OPCODES = (1U << 12),
  POLY_CPUID_FEATURE_FPAIR32_RET = (1U << 13),
  POLY_CPUID_FEATURE_FPAIR32_ARG = (1U << 14),
  POLY_CPUID_FEATURE_HETERO_U64_F64 = (1U << 15),
  POLY_CPUID_FEATURE_HETERO_F64_U64 = (1U << 16),
  POLY_CPUID_FEATURE_HETERO_U64_F32 = (1U << 17),
  POLY_CPUID_FEATURE_HETERO_F32_U64 = (1U << 18),
  POLY_CPUID_FEATURE_COMPACT_U32_F32 = (1U << 19),
  POLY_CPUID_FEATURE_COMPACT_F32_U32 = (1U << 20),
  POLY_CPUID_FEATURE_AARCH64_HFA32_ARGS = (1U << 21),
  POLY_CPUID_FEATURE_RESERVED_IMPORT_SELECTOR_TRAPS = (1U << 22),
  POLY_CPUID_FEATURE_HARDWARE_FP64_STACK_ARGS = (1U << 23),
  POLY_CPUID_FEATURE_HARDWARE_NEUTRAL_FP64_STACK = (1U << 24),
  POLY_CPUID_FEATURE_TRAP_VECTOR = (1U << 25),
  POLY_CPUID_FEATURE_STATE_KEY = (1U << 26),
  POLY_CPUID_FEATURE_VEC128_BRIDGE = (1U << 27),
  POLY_CPUID_FEATURE_AARCH64_HFA64_RET = (1U << 28),
  POLY_CPUID_FEATURE_AARCH64_HFA32_RET = (1U << 29),
  POLY_CPUID_FEATURE_LEGACY_AARCH64_HFA_ARGS = (1U << 30),
  POLY_CPUID_FEATURE_FOREIGN_PCALL_SIG_IMM = (1U << 31),
  POLY_CPUID_STATE_OVERLAP_GPRS = (1U << 0),
  POLY_CPUID_STATE_USER_RETURN_RESTORE = (1U << 5),
  POLY_CPUID_STATE_X86_TSO = (1U << 6),
  POLY_CPUID_STATE_XSAVE_VISIBLE = (1U << 7),
  POLY_CPUID_STATE_KEY_EXPLICIT = (1U << 8),
  POLY_CPUID_STATE_TRANSITION_FRAME_32 = (1U << 9),
  POLY_CPUID_STATE_EXPLICIT_SAVE_RESTORE = (1U << 10),
  POLY_CPUID_STATE_XSAVE_ARCH_CONTRACT = (1U << 11),
  POLY_CPUID_STATE_IMPORT_RETURN_XSAVE = (1U << 12),
  POLY_CPUID_STATE_ABI_SIGNATURE_XSAVE = (1U << 13),
  POLY_CPUID_STATE_MONITOR_PACKET_XSAVE = (1U << 14),
  POLY_CPUID_STATE_CROSS_RETURN_XSAVE = (1U << 15),
  POLY_CPUID_STATE_FRONTEND_TLS_XSAVE = (1U << 16),
  POLY_CPUID_STATE_LANDING_POLICY_XSAVE = (1U << 17),
  POLY_CPUID_STATE_STATE_KEY_XSAVE = (1U << 18),
  POLY_CPUID_STATE_TRAP_RESTORE_XSAVE = (1U << 19),
  POLY_CPUID_STATE_NATIVE_RETURN_XSAVE = (1U << 20),
  POLY_STATE_XSAVE_MAGIC = 0x31594c50, /* "PLY1" */
  POLY_STATE_XSAVE_COMPONENT_NONE = 0,
  POLY_STATE_XSAVE_BYTES_NONE = 0,
  POLY_STATE_XSAVE_COMPONENT_ARCH = 20,
  POLY_STATE_XSAVE_OFFSET_ARCH = 0x3000,
  POLY_STATE_XSAVE_BYTES_ARCH = 8192,
  POLY_STATE_XSAVE_ALIGN_ARCH = 64,
  POLY_STATE_XSAVE_LAYOUT_VERSION = 12,
  POLY_STATE_XSAVE_FLAG_XCR0_USER = (1U << 0),
  POLY_STATE_XSAVE_FLAG_OSXSAVE_REQUIRED = (1U << 1),
  POLY_STATE_XSAVE_FLAG_INTERRUPT_RESUME = (1U << 2),
  POLY_STATE_XSAVE_FLAG_TRAP_STATE = (1U << 3),
  POLY_STATE_XSAVE_FLAG_COMPLETE_BANK_EXPORT = (1U << 4),
  POLY_STATE_XSAVE_FLAG_IMPORT_RETURN = (1U << 5),
  POLY_STATE_XSAVE_FLAG_ABI_SIGNATURES = (1U << 6),
  POLY_STATE_XSAVE_FLAG_MONITOR_PACKET = (1U << 7),
  POLY_STATE_XSAVE_FLAG_CROSS_RETURN = (1U << 8),
  POLY_STATE_XSAVE_FLAG_FRONTEND_TLS = (1U << 9),
  POLY_STATE_XSAVE_FLAG_LANDING_POLICY = (1U << 10),
  POLY_STATE_XSAVE_FLAG_STATE_KEY = (1U << 11),
  POLY_STATE_XSAVE_FLAG_TRAP_RESTORE = (1U << 12),
  POLY_STATE_XSAVE_FLAG_NATIVE_RETURN = (1U << 13),
  POLY_NATIVE_RETURN_FRAME_FLAG_SRET = (1U << 0),
  POLY_NATIVE_RETURN_FRAME_FLAGS_SUPPORTED =
    POLY_NATIVE_RETURN_FRAME_FLAG_SRET,
  POLY_TRAP_RESTORE_FLAG_VALID = (1U << 0),
  POLY_TRAP_RESTORE_FLAG_AARCH64_STATE_VALID = (1U << 1),
  POLY_TRAP_RESTORE_FLAG_RISCV_STATE_VALID = (1U << 2),
  POLY_STATE_KEY_FLAG_EXPLICIT = (1U << 0),
  POLY_X86_RETURN_MAP_DEFAULT = 0,
  POLY_X86_RETURN_MAP_I128 = 1,
  POLY_X86_RETURN_MAP_FP128 = 2,
  POLY_X86_RETURN_MAP_FPAIR64 = 3,
  POLY_X86_RETURN_MAP_FPAIR32 = 4,
  POLY_X86_RETURN_MAP_VEC128 = 5,
  POLY_X86_RETURN_MAP_FP64 = 6,
  POLY_X86_RETURN_MAP_FP32 = 7,
  POLY_X86_RETURN_MAP_COMPACT_U32_F32 = 8,
  POLY_X86_RETURN_MAP_COMPACT_F32_U32 = 9,
  POLY_X86_RETURN_MAP_MAX = POLY_X86_RETURN_MAP_COMPACT_F32_U32,
  POLY_NATIVE_RETURN_KIND_DEFAULT = 0,
  POLY_NATIVE_RETURN_KIND_FPAIR32 = 1,
  POLY_NATIVE_RETURN_KIND_HETERO_U64_F64 = 2,
  POLY_NATIVE_RETURN_KIND_HETERO_F64_U64 = 3,
  POLY_NATIVE_RETURN_KIND_HETERO_U64_F32 = 4,
  POLY_NATIVE_RETURN_KIND_HETERO_F32_U64 = 5,
  POLY_NATIVE_RETURN_KIND_COMPACT_U32_F32 = 6,
  POLY_NATIVE_RETURN_KIND_COMPACT_F32_U32 = 7,
  POLY_NATIVE_RETURN_KIND_VEC128_U32 = 8,
  POLY_NATIVE_RETURN_KIND_AARCH64_HFA3_F64 = 9,
  POLY_NATIVE_RETURN_KIND_AARCH64_HFA4_F64 = 10,
  POLY_NATIVE_RETURN_KIND_AARCH64_HFA3_F32 = 11,
  POLY_NATIVE_RETURN_KIND_AARCH64_HFA4_F32 = 12,
  POLY_NATIVE_RETURN_KIND_FP64 = 13,
  POLY_NATIVE_RETURN_KIND_FP32 = 14,
  POLY_NATIVE_RETURN_KIND_FPAIR64 = 15,
  POLY_NATIVE_RETURN_KIND_MAX = POLY_NATIVE_RETURN_KIND_FPAIR64,
  POLY_STATE_XSAVE_HEADER_OFFSET = 0x000,
  POLY_STATE_XSAVE_HEADER_BYTES = 0x040,
  POLY_STATE_XSAVE_TRAP_PACKET_OFFSET = 0x040,
  POLY_STATE_XSAVE_TRAP_PACKET_BYTES = 0x040,
  POLY_STATE_XSAVE_TRAP_ARGS_OFFSET = 0x080,
  POLY_STATE_XSAVE_TRAP_ARGS_BYTES = 0x040,
  POLY_STATE_XSAVE_TRANSITION_OFFSET = 0x0c0,
  POLY_STATE_XSAVE_TRANSITION_BYTES = 0x040,
  POLY_STATE_XSAVE_AARCH64_GPR_OFFSET = 0x100,
  POLY_STATE_XSAVE_AARCH64_GPR_BYTES = 0x100,
  POLY_STATE_XSAVE_AARCH64_FP_OFFSET = 0x200,
  POLY_STATE_XSAVE_AARCH64_FP_BYTES = 0x200,
  POLY_STATE_XSAVE_AARCH64_STATUS_OFFSET = 0x400,
  POLY_STATE_XSAVE_AARCH64_STATUS_BYTES = 0x080,
  POLY_STATE_XSAVE_RISCV_GPR_OFFSET = 0x480,
  POLY_STATE_XSAVE_RISCV_GPR_BYTES = 0x100,
  POLY_STATE_XSAVE_RISCV_FP_OFFSET = 0x580,
  POLY_STATE_XSAVE_RISCV_FP_BYTES = 0x200,
  POLY_STATE_XSAVE_RISCV_STATUS_OFFSET = 0x780,
  POLY_STATE_XSAVE_RISCV_STATUS_BYTES = 0x080,
  POLY_STATE_XSAVE_IMPORT_RETURN_OFFSET = 0x800,
  POLY_STATE_XSAVE_IMPORT_RETURN_BYTES = 0x500,
  POLY_STATE_XSAVE_IMPORT_RETURN_DEPTH = 8,
  POLY_STATE_XSAVE_IMPORT_RETURN_FRAME_BYTES = 0x80,
  POLY_STATE_XSAVE_ABI_SIGNATURE_OFFSET = 0xd00,
  POLY_STATE_XSAVE_ABI_SIGNATURE_BYTES = 0x080,
  POLY_STATE_XSAVE_ABI_SIGNATURE_SLOTS_OFFSET =
    POLY_STATE_XSAVE_ABI_SIGNATURE_OFFSET + 0x10,
  POLY_STATE_XSAVE_CROSS_RETURN_OFFSET = 0xd80,
  POLY_STATE_XSAVE_CROSS_RETURN_BYTES = 0x120,
  POLY_STATE_XSAVE_CROSS_RETURN_DEPTH = 8,
  POLY_STATE_XSAVE_CROSS_RETURN_FRAME_BYTES = 0x20,
  POLY_STATE_XSAVE_FRONTEND_TLS_OFFSET = 0xea0,
  POLY_STATE_XSAVE_FRONTEND_TLS_BYTES = 0x040,
  POLY_STATE_XSAVE_LANDING_POLICY_OFFSET = 0xee0,
  POLY_STATE_XSAVE_LANDING_POLICY_BYTES = 0x040,
  POLY_STATE_XSAVE_STATE_KEY_OFFSET = 0xf20,
  POLY_STATE_XSAVE_STATE_KEY_BYTES = 0x040,
  POLY_STATE_XSAVE_TRAP_RESTORE_OFFSET = 0x1000,
  POLY_STATE_XSAVE_TRAP_RESTORE_BYTES = 0x800,
  POLY_STATE_XSAVE_NATIVE_RETURN_OFFSET = 0x1800,
  POLY_STATE_XSAVE_NATIVE_RETURN_BYTES = 0x280,
  POLY_STATE_XSAVE_NATIVE_RETURN_DEPTH = 8,
  POLY_STATE_XSAVE_NATIVE_RETURN_FRAME_BYTES = 0x40,
  POLY_STATE_XSAVE_RESERVED_OFFSET = 0x1a80,
  POLY_STATE_XSAVE_RESERVED_BYTES = 0x580,
  POLY_TRAP_PACKET_LAYOUT_VERSION = 2,
  POLY_TRAP_PACKET_HEADER_BYTES = 64,
  POLY_TRAP_PACKET_ARG_COUNT = 8,
  POLY_TRAP_PACKET_FLAG_VECTOR_DELIVERY = (1U << 0),
  POLY_TRAP_PACKET_FLAG_NO_VECTOR_X86_EXCEPTIONS = (1U << 1),
  POLY_TRAP_PACKET_FLAG_TRAP_RETURN_RESTORE = (1U << 2),
  POLY_TRAP_PACKET_FLAG_ALL_FRONTEND_HANDLERS = (1U << 3),
  POLY_TRAP_PACKET_FLAG_MONITOR_MEMORY = (1U << 5),
  POLY_TRAP_PACKET_REQUIRED_FLAGS =
    POLY_TRAP_PACKET_FLAG_VECTOR_DELIVERY |
    POLY_TRAP_PACKET_FLAG_NO_VECTOR_X86_EXCEPTIONS |
    POLY_TRAP_PACKET_FLAG_TRAP_RETURN_RESTORE |
    POLY_TRAP_PACKET_FLAG_ALL_FRONTEND_HANDLERS |
    POLY_TRAP_PACKET_FLAG_MONITOR_MEMORY,
  POLY_INTERRUPT_ABI_VERSION = 1,
  POLY_INTERRUPT_FLAG_RAW_CPL3_ONLY = (1U << 0),
  POLY_INTERRUPT_FLAG_STANDARD_X86_ENTRY = (1U << 1),
  POLY_INTERRUPT_FLAG_STATE_COMPONENT_SAVE = (1U << 2),
  POLY_INTERRUPT_FLAG_PRECISE_FOREIGN_PC = (1U << 3),
  POLY_INTERRUPT_FLAG_EVENT_CHECK_BETWEEN_INSNS = (1U << 4),
  POLY_INTERRUPT_RETURN_IRET64 = (1U << 0),
  POLY_INTERRUPT_RETURN_SYSRET = (1U << 1),
  POLY_INTERRUPT_RETURN_SYSEXIT = (1U << 2),
  POLY_INTERRUPT_RETURN_SIGNAL = (1U << 3),
  POLY_MEMORY_ABI_VERSION = 1,
  POLY_MEMORY_MODEL_X86_TSO = 1,
  POLY_MEMORY_FLAG_SHARED_X86_MEMORY = (1U << 0),
  POLY_MEMORY_FLAG_AARCH64_BARRIERS_NOOP = (1U << 1),
  POLY_MEMORY_FLAG_RISCV_FENCES_NOOP = (1U << 2),
  POLY_MEMORY_FLAG_ATOMICS_COHERENT = (1U << 3),
  POLY_MEMORY_FLAG_NO_WEAK_REORDERING = (1U << 4),
  POLY_TRANSITION_ABI_VERSION = 1,
  POLY_TRANSITION_FLAG_DECODED_X86_OPCODES = (1U << 0),
  POLY_TRANSITION_FLAG_NATIVE_RAW_ESCAPES = (1U << 1),
  POLY_TRANSITION_FLAG_PIPELINE_FLUSH = (1U << 2),
  POLY_TRANSITION_FLAG_BLOCK_BOUNDARY = (1U << 3),
  POLY_TRANSITION_FLAG_PRECISE_NEXT_PC = (1U << 4),
  POLY_TRANSITION_FLAG_NATIVE_FRONTEND_WIDTHS = (1U << 5),
  POLY_TRANSITION_FLAG_NEUTRAL_FOREIGN = (1U << 6),
  POLY_TRANSITION_FLAG_NATIVE_RETURN_COOKIE = (1U << 7),
  POLY_TRANSITION_FLAG_TRAP_RETURN = (1U << 8),
  POLY_TRANSITION_FLAG_INTERRUPTED_RAW = (1U << 9),
  POLY_TRANSITION_FLAG_LANDING_PADS = (1U << 10),
  POLY_TRANSITION_FLAG_LANDING_POLICY = (1U << 11),
  POLY_TRANSITION_AARCH64_ALIGN = 4,
  POLY_TRANSITION_RISCV_ALIGN = 2,
  POLY_ABI_BRIDGE_ABI_VERSION = 1,
  POLY_ABI_BRIDGE_FLAG_X86_SYSV_TO_AAPCS64 = (1U << 0),
  POLY_ABI_BRIDGE_FLAG_X86_SYSV_TO_RISCV = (1U << 1),
  POLY_ABI_BRIDGE_FLAG_SRET = (1U << 2),
  POLY_ABI_BRIDGE_FLAG_SCALAR_FP = (1U << 3),
  POLY_ABI_BRIDGE_FLAG_REGISTER_ONLY_AGGREGATES = (1U << 4),
  POLY_ABI_BRIDGE_FLAG_HARDWARE_STACK_ARGS = (1U << 5),
  POLY_ABI_BRIDGE_FLAG_HARDWARE_IMPORT_DESCRIPTORS = (1U << 6),
  POLY_ABI_BRIDGE_FLAG_TLS_BASE = (1U << 7),
  POLY_ABI_BRIDGE_FLAG_HARDWARE_USER_DESCRIPTORS = (1U << 8),
  POLY_ABI_BRIDGE_FLAG_NO_CPU_HELPER_FALLBACK = (1U << 9),
  POLY_ABI_BRIDGE_FLAG_ORDINARY_X86_RET = (1U << 10),
  POLY_ABI_BRIDGE_FLAG_VEC128 = (1U << 11),
  POLY_ABI_BRIDGE_FLAG_REGISTER_SIGNATURES = (1U << 12),
  POLY_ABI_BRIDGE_FLAG_NATIVE_I128_SIGNATURES = (1U << 13),
  POLY_ABI_BRIDGE_FLAG_REGISTER_MAP_SIGNATURES = (1U << 14),
  POLY_ABI_BRIDGE_GPR_ARG_COUNT = 8,
  POLY_ABI_BRIDGE_FP_ARG_COUNT = 8,
  POLY_ABI_BRIDGE_STACK_ALIGN = 16,
  POLY_ABI_SIGNATURE_SLOT_COUNT = 13,
  POLY_ABI_SIGNATURE_SLOT_EXCHANGE = 0,
  POLY_ABI_SIGNATURE_SLOT_X86_SYSV_REGS = 1,
  POLY_ABI_SIGNATURE_SLOT_X86_SYSV_REGS_I128 = 2,
  POLY_ABI_SIGNATURE_SLOT_NATIVE_REGS = 3,
  POLY_ABI_SIGNATURE_SLOT_NATIVE_REGS_I128 = 4,
  POLY_ABI_SIGNATURE_SLOT_NATIVE_REGS_VEC128_U32 = 5,
  POLY_ABI_SIGNATURE_SLOT_NATIVE_REGS_COMPACT_U32_F32 = 6,
  POLY_ABI_SIGNATURE_SLOT_NATIVE_REGS_COMPACT_F32_U32 = 7,
  POLY_ABI_SIGNATURE_SLOT_NATIVE_REGS_FP64 = 8,
  POLY_ABI_SIGNATURE_SLOT_NATIVE_REGS_FP32 = 9,
  POLY_ABI_SIGNATURE_SLOT_SRET_X86_SYSV_REGS = 10,
  POLY_ABI_SIGNATURE_SLOT_X86_SYSV_REGS_FP128_RET = 11,
  POLY_ABI_SIGNATURE_SLOT_NATIVE_SRET_REGS = 12,
  POLY_ABI_SIGNATURE_KIND_EXCHANGE = 0,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV = 1,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS = 2,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_I128 = 3,
  POLY_ABI_SIGNATURE_KIND_NATIVE_REGS = 4,
  POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_I128 = 5,
  POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_VEC128_U32 = 6,
  POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_COMPACT_U32_F32 = 7,
  POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_COMPACT_F32_U32 = 8,
  POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_FP64 = 9,
  POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_FP32 = 10,
  POLY_ABI_SIGNATURE_KIND_SRET_X86_SYSV_REGS = 11,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_FP128_RET = 12,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_FPAIR32_RET = 13,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_FPAIR32_ARG = 14,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_HETERO_U64_F64 = 15,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_HETERO_F64_U64 = 16,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_HETERO_U64_F32 = 17,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_HETERO_F32_U64 = 18,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_FPAIR64_RET = 19,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_FPAIR64_ARG = 20,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_MIXED_U64_FP64 = 21,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_AARCH64_HFA3_F32_RET = 22,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_AARCH64_HFA4_F32_RET = 23,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_AARCH64_HFA3_F32_ARG = 24,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_AARCH64_HFA4_F32_ARG = 25,
  POLY_ABI_SIGNATURE_KIND_NATIVE_SRET_REGS = 26,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_AARCH64_HFA3_F64_RET = 27,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_AARCH64_HFA4_F64_RET = 28,
  POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_TLS_BASE = 29,
  POLY_ABI_SIGNATURE_KIND_LAST_VALID =
    POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_TLS_BASE,
  POLY_ABI_SIGNATURE_KIND_INVALID_TEST =
    POLY_ABI_SIGNATURE_KIND_LAST_VALID + 1,
  POLY_ABI_REGISTER_MAP_EXCHANGE = 0,
  POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE = 1,
  POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_I128 = 2,
  POLY_ABI_REGISTER_MAP_NATIVE = 3,
  POLY_ABI_REGISTER_MAP_NATIVE_I128 = 4,
  POLY_ABI_REGISTER_MAP_NATIVE_VEC128_U32 = 5,
  POLY_ABI_REGISTER_MAP_NATIVE_COMPACT_U32_F32 = 6,
  POLY_ABI_REGISTER_MAP_NATIVE_COMPACT_F32_U32 = 7,
  POLY_ABI_REGISTER_MAP_NATIVE_FP64 = 8,
  POLY_ABI_REGISTER_MAP_NATIVE_FP32 = 9,
  POLY_ABI_REGISTER_MAP_SRET_X86_SYSV_TO_NATIVE = 10,
  POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_FP128_RET = 11,
  POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_FPAIR32_RET = 12,
  POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_FPAIR32_ARG = 13,
  POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_HETERO_U64_F64 = 14,
  POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_HETERO_F64_U64 = 15,
  POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_HETERO_U64_F32 = 16,
  POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_HETERO_F32_U64 = 17,
  POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_FPAIR64_RET = 18,
  POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_FPAIR64_ARG = 19,
  POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_MIXED_U64_FP64 = 20,
  POLY_ABI_REGISTER_MAP_X86_SYSV_TO_AARCH64_HFA3_F32_RET = 21,
  POLY_ABI_REGISTER_MAP_X86_SYSV_TO_AARCH64_HFA4_F32_RET = 22,
  POLY_ABI_REGISTER_MAP_X86_SYSV_TO_AARCH64_HFA3_F32_ARG = 23,
  POLY_ABI_REGISTER_MAP_X86_SYSV_TO_AARCH64_HFA4_F32_ARG = 24,
  POLY_ABI_REGISTER_MAP_NATIVE_SRET = 25,
  POLY_ABI_REGISTER_MAP_X86_SYSV_TO_AARCH64_HFA3_F64_RET = 26,
  POLY_ABI_REGISTER_MAP_X86_SYSV_TO_AARCH64_HFA4_F64_RET = 27,
  POLY_LANDING_POLICY_REQUIRE_SWITCH = (1ULL << 0),
  POLY_LANDING_POLICY_REQUIRE_CALL = (1ULL << 1),
  POLY_LANDING_POLICY_SUPPORTED = POLY_LANDING_POLICY_REQUIRE_SWITCH |
    POLY_LANDING_POLICY_REQUIRE_CALL,
  POLY_CROSS_BRIDGE_DEFAULT = 0,
  POLY_CROSS_BRIDGE_RESERVED_1 = 1,
  POLY_CROSS_BRIDGE_COMPACT_U32_F32 = 2,
  POLY_CROSS_BRIDGE_COMPACT_F32_U32 = 3,
  POLY_CROSS_BRIDGE_VEC128_U32 = 4,
  POLY_CROSS_BRIDGE_FP64 = 5,
  POLY_CROSS_BRIDGE_FP32 = 6,
  POLY_CROSS_BRIDGE_NATIVE_SRET = 7
};

static inline uint32_t poly_abi_signature_register_map(uint32_t kind) {
  switch (kind) {
  case POLY_ABI_SIGNATURE_KIND_EXCHANGE:
    return POLY_ABI_REGISTER_MAP_EXCHANGE;
  case POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS:
    return POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE;
  case POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_I128:
    return POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_I128;
  case POLY_ABI_SIGNATURE_KIND_NATIVE_REGS:
  case POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_TLS_BASE:
    return POLY_ABI_REGISTER_MAP_NATIVE;
  case POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_I128:
    return POLY_ABI_REGISTER_MAP_NATIVE_I128;
  case POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_VEC128_U32:
    return POLY_ABI_REGISTER_MAP_NATIVE_VEC128_U32;
  case POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_COMPACT_U32_F32:
    return POLY_ABI_REGISTER_MAP_NATIVE_COMPACT_U32_F32;
  case POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_COMPACT_F32_U32:
    return POLY_ABI_REGISTER_MAP_NATIVE_COMPACT_F32_U32;
  case POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_FP64:
    return POLY_ABI_REGISTER_MAP_NATIVE_FP64;
  case POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_FP32:
    return POLY_ABI_REGISTER_MAP_NATIVE_FP32;
  case POLY_ABI_SIGNATURE_KIND_SRET_X86_SYSV_REGS:
    return POLY_ABI_REGISTER_MAP_SRET_X86_SYSV_TO_NATIVE;
  case POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_FP128_RET:
    return POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_FP128_RET;
  case POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_FPAIR32_RET:
    return POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_FPAIR32_RET;
  case POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_FPAIR32_ARG:
    return POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_FPAIR32_ARG;
  case POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_HETERO_U64_F64:
    return POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_HETERO_U64_F64;
  case POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_HETERO_F64_U64:
    return POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_HETERO_F64_U64;
  case POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_HETERO_U64_F32:
    return POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_HETERO_U64_F32;
  case POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_HETERO_F32_U64:
    return POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_HETERO_F32_U64;
  case POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_FPAIR64_RET:
    return POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_FPAIR64_RET;
  case POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_FPAIR64_ARG:
    return POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_FPAIR64_ARG;
  case POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_MIXED_U64_FP64:
    return POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_MIXED_U64_FP64;
  case POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_AARCH64_HFA3_F32_RET:
    return POLY_ABI_REGISTER_MAP_X86_SYSV_TO_AARCH64_HFA3_F32_RET;
  case POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_AARCH64_HFA4_F32_RET:
    return POLY_ABI_REGISTER_MAP_X86_SYSV_TO_AARCH64_HFA4_F32_RET;
  case POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_AARCH64_HFA3_F32_ARG:
    return POLY_ABI_REGISTER_MAP_X86_SYSV_TO_AARCH64_HFA3_F32_ARG;
  case POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_AARCH64_HFA4_F32_ARG:
    return POLY_ABI_REGISTER_MAP_X86_SYSV_TO_AARCH64_HFA4_F32_ARG;
  case POLY_ABI_SIGNATURE_KIND_NATIVE_SRET_REGS:
    return POLY_ABI_REGISTER_MAP_NATIVE_SRET;
  case POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_AARCH64_HFA3_F64_RET:
    return POLY_ABI_REGISTER_MAP_X86_SYSV_TO_AARCH64_HFA3_F64_RET;
  case POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_AARCH64_HFA4_F64_RET:
    return POLY_ABI_REGISTER_MAP_X86_SYSV_TO_AARCH64_HFA4_F64_RET;
  default:
    return UINT32_MAX;
  }
}

static inline uint64_t poly_abi_signature_control_value(uint64_t kind) {
  if ((kind >> 32) != 0)
    return kind;
  uint32_t register_map = poly_abi_signature_register_map((uint32_t) kind);
  if (register_map == UINT32_MAX)
    return kind;
  return (uint32_t) kind | ((uint64_t) register_map << 32);
}

static const uint64_t POLY_IMPORT_CALL_BASE = 0xffffffffffffe000ULL;
static const uint64_t POLY_IMPORT_CALL_STRIDE = 0x10ULL;
enum {
  /* Architectural trap selector window. The CPU treats every selector here as
     opaque policy owned by the user-mode monitor/runtime. */
  POLY_IMPORT_SELECTOR_COUNT = 256
};

struct poly_cpuid_regs {
  uint32_t eax;
  uint32_t ebx;
  uint32_t ecx;
  uint32_t edx;
};

struct poly_u128 {
  uint64_t lo;
  uint64_t hi;
};

struct poly_xsave_header {
  uint32_t magic;
  uint16_t layout_version;
  uint16_t header_bytes;
  uint32_t total_bytes;
  uint32_t current_mode;
  uint64_t flags;
  uint64_t foreign_pc;
  uint64_t foreign_tls_base;
  uint64_t trap_vector_pc;
  uint32_t trap_vector_mode;
  uint32_t reserved0;
  uint64_t monitor_packet_addr;
};

struct poly_trap_packet {
  uint32_t reason;
  uint32_t source_mode;
  uint64_t number;
  uint64_t selector;
  uint64_t trap_pc;
  uint64_t resume_pc;
  uint64_t flags;
  uint64_t reserved[2];
};

struct poly_transition_frame {
  uint64_t return_pc;
  uint32_t caller_mode;
  uint32_t target_mode;
  uint16_t abi_kind;
  uint16_t flags;
  uint32_t reserved0;
  uint64_t cookie;
};

struct poly_xsave_transition_area {
  struct poly_transition_frame active;
  uint8_t reserved[POLY_STATE_XSAVE_TRANSITION_BYTES -
    sizeof(struct poly_transition_frame)];
};

struct poly_aarch64_status_state {
  uint64_t nzcv;
  uint64_t fpcr;
  uint64_t fpsr;
  uint64_t reservation_addr;
  uint64_t reservation_size;
  uint64_t reserved[11];
};

struct poly_riscv_status_state {
  uint64_t fcsr;
  uint64_t reservation_addr;
  uint64_t reservation_size;
  uint64_t reserved[13];
};

struct poly_import_return_frame {
  uint32_t source_mode;
  uint32_t alias_valid;
  uint64_t return_pc;
  uint64_t return_sp;
  uint64_t import_id;
  uint64_t return_map;
  uint64_t alias[6];
  uint64_t saved_x86_fsbase;
  uint64_t target_x86_fsbase;
  uint64_t saved_aarch64_tls_base;
  uint64_t saved_riscv_tls_base;
  uint64_t saved_source_reg2;
};

struct poly_import_return_state {
  uint64_t top;
  uint64_t depth;
  struct poly_import_return_frame
    frames[POLY_STATE_XSAVE_IMPORT_RETURN_DEPTH];
  uint8_t reserved[POLY_STATE_XSAVE_IMPORT_RETURN_BYTES - 16 -
    POLY_STATE_XSAVE_IMPORT_RETURN_DEPTH *
      sizeof(struct poly_import_return_frame)];
};

struct poly_cross_return_frame {
  uint64_t return_pc;
  uint64_t return_sp;
  uint32_t caller_mode;
  uint32_t target_mode;
  uint16_t abi_kind;
  uint16_t flags;
  uint32_t reserved0;
};

struct poly_cross_return_state {
  uint64_t top;
  uint64_t depth;
  struct poly_cross_return_frame
    frames[POLY_STATE_XSAVE_CROSS_RETURN_DEPTH];
  uint8_t reserved[POLY_STATE_XSAVE_CROSS_RETURN_BYTES - 16 -
    POLY_STATE_XSAVE_CROSS_RETURN_DEPTH *
      sizeof(struct poly_cross_return_frame)];
};

struct poly_native_return_frame {
  uint64_t return_pc;
  uint64_t return_sp;
  uint64_t sret_ptr;
  uint32_t target_mode;
  uint16_t return_kind;
  uint16_t flags;
  uint64_t reserved[4];
};

struct poly_native_return_state {
  uint64_t active_valid;
  uint64_t top;
  uint64_t depth;
  uint64_t supported_flags;
  struct poly_native_return_frame active;
  struct poly_native_return_frame
    frames[POLY_STATE_XSAVE_NATIVE_RETURN_DEPTH];
  uint8_t reserved[POLY_STATE_XSAVE_NATIVE_RETURN_BYTES - 32 -
    (POLY_STATE_XSAVE_NATIVE_RETURN_DEPTH + 1) *
      sizeof(struct poly_native_return_frame)];
};

struct poly_abi_signature_slot_state {
  uint32_t kind;
  uint32_t register_map;
};

struct poly_abi_signature_state {
  uint64_t slot_count;
  uint64_t flags;
  struct poly_abi_signature_slot_state
    slots[POLY_ABI_SIGNATURE_SLOT_COUNT];
  uint8_t reserved[POLY_STATE_XSAVE_ABI_SIGNATURE_BYTES - 16 -
    POLY_ABI_SIGNATURE_SLOT_COUNT *
      sizeof(struct poly_abi_signature_slot_state)];
};

struct poly_frontend_tls_state {
  uint64_t flags;
  uint64_t active_mode;
  uint64_t aarch64_tls_base;
  uint64_t riscv_tls_base;
  uint64_t reserved[4];
};

struct poly_landing_policy_state {
  uint64_t flags;
  uint64_t supported_flags;
  uint64_t reserved[6];
};

struct poly_state_key_state {
  uint64_t flags;
  uint64_t explicit_key;
  uint64_t supported_flags;
  uint64_t reserved[5];
};

struct poly_trap_restore_state {
  uint64_t flags;
  uint32_t mode;
  uint32_t reserved0;
  uint64_t x86_gpr[16];
  struct poly_u128 x86_xmm[16];
  uint64_t aarch64_gpr_valid_mask;
  uint64_t aarch64_gpr[32];
  struct poly_u128 aarch64_fp[32];
  uint64_t aarch64_nzcv;
  uint64_t aarch64_fpcr;
  uint64_t aarch64_fpsr;
  uint64_t aarch64_reserved;
  uint64_t riscv_gpr_valid_mask;
  uint64_t riscv_gpr[32];
  struct poly_u128 riscv_fp[32];
  uint64_t riscv_fcsr;
  uint64_t riscv_reserved[3];
  uint8_t reserved[32];
};

struct poly_xsave_state {
  struct poly_xsave_header header;
  struct poly_trap_packet trap;
  uint64_t trap_args[POLY_TRAP_PACKET_ARG_COUNT];
  struct poly_xsave_transition_area transition;
  uint64_t aarch64_gpr[32];
  struct poly_u128 aarch64_fp[32];
  struct poly_aarch64_status_state aarch64_status;
  uint64_t riscv_gpr[32];
  struct poly_u128 riscv_fp[32];
  struct poly_riscv_status_state riscv_status;
  struct poly_import_return_state import_return;
  struct poly_abi_signature_state abi_signature;
  struct poly_cross_return_state cross_return;
  struct poly_frontend_tls_state frontend_tls;
  struct poly_landing_policy_state landing_policy;
  struct poly_state_key_state state_key;
  uint8_t pre_trap_restore_reserved[
    POLY_STATE_XSAVE_TRAP_RESTORE_OFFSET -
    POLY_STATE_XSAVE_STATE_KEY_OFFSET -
    POLY_STATE_XSAVE_STATE_KEY_BYTES];
  struct poly_trap_restore_state trap_restore;
  struct poly_native_return_state native_return;
  uint8_t reserved[POLY_STATE_XSAVE_RESERVED_BYTES];
};

#define POLY_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)

POLY_STATIC_ASSERT(sizeof(struct poly_u128) == 16,
  "poly_u128 must be 16 bytes");
POLY_STATIC_ASSERT(sizeof(struct poly_xsave_header) ==
  POLY_STATE_XSAVE_HEADER_BYTES,
  "poly XSAVE header size must match CPUID contract");
POLY_STATIC_ASSERT(sizeof(struct poly_trap_packet) ==
  POLY_STATE_XSAVE_TRAP_PACKET_BYTES,
  "poly trap packet size must match CPUID contract");
POLY_STATIC_ASSERT(sizeof(struct poly_transition_frame) == 32,
  "poly transition frame must remain 32 bytes");
POLY_STATIC_ASSERT(sizeof(struct poly_xsave_transition_area) ==
  POLY_STATE_XSAVE_TRANSITION_BYTES,
  "poly transition area size must match XSAVE layout");
POLY_STATIC_ASSERT(sizeof(struct poly_aarch64_status_state) ==
  POLY_STATE_XSAVE_AARCH64_STATUS_BYTES,
  "poly AArch64 status area size must match XSAVE layout");
POLY_STATIC_ASSERT(sizeof(struct poly_riscv_status_state) ==
  POLY_STATE_XSAVE_RISCV_STATUS_BYTES,
  "poly RISC-V status area size must match XSAVE layout");
POLY_STATIC_ASSERT(sizeof(struct poly_import_return_frame) ==
  POLY_STATE_XSAVE_IMPORT_RETURN_FRAME_BYTES,
  "poly import return frame size must match XSAVE layout");
POLY_STATIC_ASSERT(sizeof(struct poly_import_return_state) ==
  POLY_STATE_XSAVE_IMPORT_RETURN_BYTES,
  "poly import return area size must match XSAVE layout");
POLY_STATIC_ASSERT(sizeof(struct poly_cross_return_frame) ==
  POLY_STATE_XSAVE_CROSS_RETURN_FRAME_BYTES,
  "poly cross-return frame size must match XSAVE layout");
POLY_STATIC_ASSERT(sizeof(struct poly_cross_return_state) ==
  POLY_STATE_XSAVE_CROSS_RETURN_BYTES,
  "poly cross-return area size must match XSAVE layout");
POLY_STATIC_ASSERT(sizeof(struct poly_abi_signature_state) ==
  POLY_STATE_XSAVE_ABI_SIGNATURE_BYTES,
  "poly ABI signature area size must match XSAVE layout");
POLY_STATIC_ASSERT(sizeof(struct poly_frontend_tls_state) ==
  POLY_STATE_XSAVE_FRONTEND_TLS_BYTES,
  "poly frontend TLS area size must match XSAVE layout");
POLY_STATIC_ASSERT(sizeof(struct poly_landing_policy_state) ==
  POLY_STATE_XSAVE_LANDING_POLICY_BYTES,
  "poly landing policy area size must match XSAVE layout");
POLY_STATIC_ASSERT(sizeof(struct poly_state_key_state) ==
  POLY_STATE_XSAVE_STATE_KEY_BYTES,
  "poly state-key area size must match XSAVE layout");
POLY_STATIC_ASSERT(sizeof(struct poly_trap_restore_state) ==
  POLY_STATE_XSAVE_TRAP_RESTORE_BYTES,
  "poly trap-restore area size must match XSAVE layout");
POLY_STATIC_ASSERT(sizeof(struct poly_native_return_frame) ==
  POLY_STATE_XSAVE_NATIVE_RETURN_FRAME_BYTES,
  "poly native-return frame size must match XSAVE layout");
POLY_STATIC_ASSERT(sizeof(struct poly_native_return_state) ==
  POLY_STATE_XSAVE_NATIVE_RETURN_BYTES,
  "poly native-return area size must match XSAVE layout");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, header) ==
  POLY_STATE_XSAVE_HEADER_OFFSET,
  "poly XSAVE header offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, trap) ==
  POLY_STATE_XSAVE_TRAP_PACKET_OFFSET,
  "poly trap packet offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, trap_args) ==
  POLY_STATE_XSAVE_TRAP_ARGS_OFFSET,
  "poly trap args offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, transition) ==
  POLY_STATE_XSAVE_TRANSITION_OFFSET,
  "poly transition area offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, aarch64_gpr) ==
  POLY_STATE_XSAVE_AARCH64_GPR_OFFSET,
  "poly AArch64 GPR offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, aarch64_fp) ==
  POLY_STATE_XSAVE_AARCH64_FP_OFFSET,
  "poly AArch64 FP offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, aarch64_status) ==
  POLY_STATE_XSAVE_AARCH64_STATUS_OFFSET,
  "poly AArch64 status offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, riscv_gpr) ==
  POLY_STATE_XSAVE_RISCV_GPR_OFFSET,
  "poly RISC-V GPR offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, riscv_fp) ==
  POLY_STATE_XSAVE_RISCV_FP_OFFSET,
  "poly RISC-V FP offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, riscv_status) ==
  POLY_STATE_XSAVE_RISCV_STATUS_OFFSET,
  "poly RISC-V status offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, import_return) ==
  POLY_STATE_XSAVE_IMPORT_RETURN_OFFSET,
  "poly import return offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, abi_signature) ==
  POLY_STATE_XSAVE_ABI_SIGNATURE_OFFSET,
  "poly ABI signature offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, cross_return) ==
  POLY_STATE_XSAVE_CROSS_RETURN_OFFSET,
  "poly cross-return offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, frontend_tls) ==
  POLY_STATE_XSAVE_FRONTEND_TLS_OFFSET,
  "poly frontend TLS offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, landing_policy) ==
  POLY_STATE_XSAVE_LANDING_POLICY_OFFSET,
  "poly landing policy offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, state_key) ==
  POLY_STATE_XSAVE_STATE_KEY_OFFSET,
  "poly state-key offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, trap_restore) ==
  POLY_STATE_XSAVE_TRAP_RESTORE_OFFSET,
  "poly trap-restore offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, native_return) ==
  POLY_STATE_XSAVE_NATIVE_RETURN_OFFSET,
  "poly native-return offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, reserved) ==
  POLY_STATE_XSAVE_RESERVED_OFFSET,
  "poly reserved area offset drifted");
POLY_STATIC_ASSERT(sizeof(struct poly_xsave_state) ==
  POLY_STATE_XSAVE_BYTES_ARCH,
  "poly XSAVE area size must match CPUID contract");

static inline struct poly_cpuid_regs poly_read_cpuid(uint32_t leaf,
    uint32_t subleaf) {
  struct poly_cpuid_regs regs;
  asm volatile("cpuid"
    : "=a"(regs.eax), "=b"(regs.ebx), "=c"(regs.ecx), "=d"(regs.edx)
    : "a"(leaf), "c"(subleaf)
    : "memory");
  return regs;
}

static inline uint32_t poly_cpuid_expected_mode_mask(void) {
  return (1U << POLY_MODE_X86) |
    (1U << POLY_MODE_RAW_AARCH64) |
    (1U << POLY_MODE_RAW_RISCV);
}

static inline uint32_t poly_cpuid_expected_frontend_mask(void) {
  return (1U << POLY_FRONTEND_X86) |
    (1U << POLY_FRONTEND_AARCH64) |
    (1U << POLY_FRONTEND_RISCV);
}

static inline uint32_t poly_cpuid_expected_feature_mask(void) {
  uint32_t mask = POLY_CPUID_FEATURE_RAW_AARCH64 |
    POLY_CPUID_FEATURE_RAW_RISCV |
    POLY_CPUID_FEATURE_NEUTRAL_SWITCH |
    POLY_CPUID_FEATURE_NATIVE_RET |
    POLY_CPUID_FEATURE_PCALL_SYSV |
    POLY_CPUID_FEATURE_PCALL_SRET |
    POLY_CPUID_FEATURE_FP_BRIDGE |
    POLY_CPUID_FEATURE_TRAP_RECORDS |
    POLY_CPUID_FEATURE_USER_RETURN_RESTORE |
    POLY_CPUID_FEATURE_X86_TSO |
    POLY_CPUID_FEATURE_PER_THREAD_STATE |
    POLY_CPUID_FEATURE_GENERIC_FRONTEND_IDS |
    POLY_CPUID_FEATURE_X86_POLY_OPCODES |
    POLY_CPUID_FEATURE_FPAIR32_RET |
    POLY_CPUID_FEATURE_FPAIR32_ARG |
    POLY_CPUID_FEATURE_HETERO_U64_F64 |
    POLY_CPUID_FEATURE_HETERO_F64_U64 |
    POLY_CPUID_FEATURE_HETERO_U64_F32 |
    POLY_CPUID_FEATURE_HETERO_F32_U64 |
    POLY_CPUID_FEATURE_COMPACT_U32_F32 |
    POLY_CPUID_FEATURE_COMPACT_F32_U32 |
    POLY_CPUID_FEATURE_AARCH64_HFA32_ARGS |
    POLY_CPUID_FEATURE_TRAP_VECTOR |
    POLY_CPUID_FEATURE_STATE_KEY |
    POLY_CPUID_FEATURE_VEC128_BRIDGE |
    POLY_CPUID_FEATURE_AARCH64_HFA64_RET |
    POLY_CPUID_FEATURE_AARCH64_HFA32_RET |
    POLY_CPUID_FEATURE_FOREIGN_PCALL_SIG_IMM;
  return mask;
}

static inline uint32_t poly_cpuid_forbidden_feature_mask(void) {
  return POLY_CPUID_FEATURE_RESERVED_IMPORT_SELECTOR_TRAPS |
    POLY_CPUID_FEATURE_HARDWARE_FP64_STACK_ARGS |
    POLY_CPUID_FEATURE_HARDWARE_NEUTRAL_FP64_STACK |
    POLY_CPUID_FEATURE_LEGACY_AARCH64_HFA_ARGS;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf0(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_AARCH64_CTRL_X86_ESCAPE;
  regs.ebx = 0;
  regs.ecx = POLY_RISCV_CTRL_X86_ESCAPE;
  regs.edx = 0;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf1(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_X86_CTRL_TRAP_VECTOR_SET;
  regs.ebx = POLY_X86_CTRL_TRAP_VECTOR_GET;
  regs.ecx = POLY_X86_CTRL_TRAP_VECTOR_MODE_SET;
  regs.edx = POLY_X86_CTRL_TRAP_VECTOR_MODE_GET;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf2(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_X86_CTRL_STATE_KEY_SET;
  regs.ebx = POLY_X86_CTRL_STATE_KEY_GET;
  regs.ecx = POLY_X86_CTRL_STATE_EXPORT;
  regs.edx = POLY_X86_CTRL_STATE_IMPORT;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf3(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_X86_CTRL_ABI_SIGNATURE_SET;
  regs.ebx = POLY_X86_CTRL_ABI_SIGNATURE_GET;
  regs.ecx = POLY_X86_CTRL_MONITOR_PACKET_SET;
  regs.edx = POLY_X86_CTRL_MONITOR_PACKET_GET;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf4(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_AARCH64_CTRL_TRAP_RETURN;
  regs.ebx = POLY_RISCV_CTRL_TRAP_RETURN;
  regs.ecx = POLY_AARCH64_CTRL_CALL_SIG_IMM(
    POLY_ABI_SIGNATURE_SLOT_NATIVE_REGS_VEC128_U32);
  regs.edx = POLY_RISCV_CTRL_CALL_SIG_IMM(
    POLY_ABI_SIGNATURE_SLOT_NATIVE_REGS_VEC128_U32);
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf5(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_X86_CTRL_PENTER_MODE;
  regs.ebx = POLY_X86_CTRL_PSWITCH_MODE;
  regs.ecx = POLY_X86_CTRL_PCALL_SIG_MODE;
  regs.edx = POLY_X86_CTRL_TRAP_RETURN;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf6(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_AARCH64_CTRL_SWITCH_MODE;
  regs.ebx = POLY_RISCV_CTRL_SWITCH_MODE;
  regs.ecx = POLY_AARCH64_CTRL_CALL_MODE;
  regs.edx = POLY_RISCV_CTRL_CALL_MODE;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf7(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_X86_CTRL_PCALL_SIG_IMM_BASE;
  regs.ebx = POLY_ABI_SIGNATURE_SLOT_COUNT;
  regs.ecx = POLY_ABI_SIGNATURE_SLOT_EXCHANGE |
    (POLY_ABI_SIGNATURE_SLOT_X86_SYSV_REGS << 8) |
    (POLY_ABI_SIGNATURE_SLOT_X86_SYSV_REGS_I128 << 16) |
    (POLY_ABI_SIGNATURE_SLOT_NATIVE_REGS << 24);
  regs.edx = POLY_ABI_SIGNATURE_KIND_EXCHANGE |
    (POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS << 8) |
    (POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_I128 << 16) |
    (POLY_ABI_SIGNATURE_KIND_NATIVE_REGS << 24);
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf8(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_AARCH64_CTRL_CALL_SIG_MODE;
  regs.ebx = POLY_RISCV_CTRL_CALL_SIG_MODE;
  regs.ecx = POLY_ABI_SIGNATURE_SLOT_COUNT;
  regs.edx = 0;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf9(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_X86_CTRL_LANDING;
  regs.ebx = POLY_AARCH64_CTRL_LANDING;
  regs.ecx = POLY_RISCV_CTRL_LANDING;
  regs.edx = POLY_X86_CTRL_IMPORT_RETURN;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf10(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_AARCH64_CTRL_ABI_SIGNATURE_SET;
  regs.ebx = POLY_AARCH64_CTRL_ABI_SIGNATURE_GET;
  regs.ecx = POLY_RISCV_CTRL_ABI_SIGNATURE_SET;
  regs.edx = POLY_RISCV_CTRL_ABI_SIGNATURE_GET;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf11(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_AARCH64_CTRL_CALL_SIG_IMM(0);
  regs.ebx = POLY_RISCV_CTRL_CALL_SIG_IMM(0);
  regs.ecx = POLY_ABI_SIGNATURE_SLOT_COUNT;
  regs.edx = POLY_X86_CTRL_PCALL_SIG_IMM(0);
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf12(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_AARCH64_CTRL_TRAP_VECTOR_SET;
  regs.ebx = POLY_AARCH64_CTRL_MONITOR_PACKET_SET;
  regs.ecx = POLY_RISCV_CTRL_TRAP_VECTOR_SET;
  regs.edx = POLY_RISCV_CTRL_MONITOR_PACKET_SET;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf13(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_AARCH64_CTRL_TRAP_VECTOR_GET;
  regs.ebx = POLY_AARCH64_CTRL_TRAP_VECTOR_MODE_SET;
  regs.ecx = POLY_AARCH64_CTRL_TRAP_VECTOR_MODE_GET;
  regs.edx = POLY_AARCH64_CTRL_MONITOR_PACKET_GET;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf14(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_RISCV_CTRL_TRAP_VECTOR_GET;
  regs.ebx = POLY_RISCV_CTRL_TRAP_VECTOR_MODE_SET;
  regs.ecx = POLY_RISCV_CTRL_TRAP_VECTOR_MODE_GET;
  regs.edx = POLY_RISCV_CTRL_MONITOR_PACKET_GET;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf15(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_X86_CTRL_LANDING_POLICY_SET;
  regs.ebx = POLY_X86_CTRL_LANDING_POLICY_GET;
  regs.ecx = POLY_AARCH64_CTRL_LANDING_POLICY_SET;
  regs.edx = POLY_AARCH64_CTRL_LANDING_POLICY_GET;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf16(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_RISCV_CTRL_LANDING_POLICY_SET;
  regs.ebx = POLY_RISCV_CTRL_LANDING_POLICY_GET;
  regs.ecx = (uint32_t) POLY_LANDING_POLICY_SUPPORTED;
  regs.edx = POLY_STATE_XSAVE_LANDING_POLICY_OFFSET;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf17(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_ABI_SIGNATURE_SLOT_NATIVE_REGS_I128;
  regs.ebx = POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_I128;
  regs.ecx = POLY_ABI_SIGNATURE_SLOT_NATIVE_REGS_VEC128_U32;
  regs.edx = POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_VEC128_U32;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf18(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_ABI_REGISTER_MAP_EXCHANGE |
    (POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE << 8) |
    (POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_I128 << 16) |
    (POLY_ABI_REGISTER_MAP_NATIVE << 24);
  regs.ebx = POLY_ABI_REGISTER_MAP_NATIVE_I128 |
    (POLY_ABI_REGISTER_MAP_NATIVE_VEC128_U32 << 8) |
    (POLY_ABI_REGISTER_MAP_NATIVE_COMPACT_U32_F32 << 16) |
    (POLY_ABI_REGISTER_MAP_NATIVE_COMPACT_F32_U32 << 24);
  regs.ecx = POLY_STATE_XSAVE_ABI_SIGNATURE_SLOTS_OFFSET;
  regs.edx = sizeof(struct poly_abi_signature_slot_state);
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf20(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_ABI_SIGNATURE_SLOT_NATIVE_REGS_COMPACT_U32_F32;
  regs.ebx = POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_COMPACT_U32_F32;
  regs.ecx = POLY_ABI_SIGNATURE_SLOT_NATIVE_REGS_COMPACT_F32_U32;
  regs.edx = POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_COMPACT_F32_U32;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf19(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_AARCH64_CTRL_STATE_KEY_SET;
  regs.ebx = POLY_AARCH64_CTRL_STATE_KEY_GET;
  regs.ecx = POLY_RISCV_CTRL_STATE_KEY_SET;
  regs.edx = POLY_RISCV_CTRL_STATE_KEY_GET;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf21(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_STATE_KEY_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_STATE_KEY_BYTES;
  regs.ecx = POLY_STATE_KEY_FLAG_EXPLICIT;
  regs.edx = 0;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf22(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_FP64;
  regs.ebx = POLY_ABI_REGISTER_MAP_NATIVE_FP64;
  regs.ecx = POLY_ABI_BRIDGE_FP_ARG_COUNT;
  regs.edx = POLY_ABI_SIGNATURE_SLOT_NATIVE_REGS_FP64;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf23(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_ABI_SIGNATURE_KIND_NATIVE_REGS_FP32;
  regs.ebx = POLY_ABI_REGISTER_MAP_NATIVE_FP32;
  regs.ecx = POLY_ABI_BRIDGE_FP_ARG_COUNT;
  regs.edx = POLY_ABI_SIGNATURE_SLOT_NATIVE_REGS_FP32;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf24(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_ABI_SIGNATURE_SLOT_SRET_X86_SYSV_REGS;
  regs.ebx = POLY_ABI_SIGNATURE_KIND_SRET_X86_SYSV_REGS;
  regs.ecx = POLY_ABI_REGISTER_MAP_SRET_X86_SYSV_TO_NATIVE;
  regs.edx = POLY_ABI_BRIDGE_GPR_ARG_COUNT;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf25(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_ABI_SIGNATURE_SLOT_X86_SYSV_REGS_FP128_RET;
  regs.ebx = POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_FP128_RET;
  regs.ecx = POLY_ABI_REGISTER_MAP_X86_SYSV_TO_NATIVE_FP128_RET;
  regs.edx = POLY_ABI_BRIDGE_GPR_ARG_COUNT;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf26(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_AARCH64_HFA3_F32_RET;
  regs.ebx = POLY_ABI_REGISTER_MAP_X86_SYSV_TO_AARCH64_HFA3_F32_RET;
  regs.ecx = POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_AARCH64_HFA4_F32_RET;
  regs.edx = POLY_ABI_REGISTER_MAP_X86_SYSV_TO_AARCH64_HFA4_F32_RET;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf27(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_AARCH64_HFA3_F32_ARG;
  regs.ebx = POLY_ABI_REGISTER_MAP_X86_SYSV_TO_AARCH64_HFA3_F32_ARG;
  regs.ecx = POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_AARCH64_HFA4_F32_ARG;
  regs.edx = POLY_ABI_REGISTER_MAP_X86_SYSV_TO_AARCH64_HFA4_F32_ARG;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf28(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_ABI_SIGNATURE_SLOT_NATIVE_SRET_REGS;
  regs.ebx = POLY_ABI_SIGNATURE_KIND_NATIVE_SRET_REGS;
  regs.ecx = POLY_ABI_REGISTER_MAP_NATIVE_SRET;
  regs.edx = POLY_ABI_BRIDGE_GPR_ARG_COUNT;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf29(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_AARCH64_HFA3_F64_RET;
  regs.ebx = POLY_ABI_REGISTER_MAP_X86_SYSV_TO_AARCH64_HFA3_F64_RET;
  regs.ecx = POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_AARCH64_HFA4_F64_RET;
  regs.edx = POLY_ABI_REGISTER_MAP_X86_SYSV_TO_AARCH64_HFA4_F64_RET;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_state_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_CPUID_STATE_OVERLAP_GPRS |
    POLY_CPUID_STATE_USER_RETURN_RESTORE |
    POLY_CPUID_STATE_X86_TSO |
    POLY_CPUID_STATE_XSAVE_VISIBLE |
    POLY_CPUID_STATE_KEY_EXPLICIT |
    POLY_CPUID_STATE_TRANSITION_FRAME_32 |
    POLY_CPUID_STATE_EXPLICIT_SAVE_RESTORE |
    POLY_CPUID_STATE_XSAVE_ARCH_CONTRACT |
    POLY_CPUID_STATE_IMPORT_RETURN_XSAVE |
    POLY_CPUID_STATE_ABI_SIGNATURE_XSAVE |
    POLY_CPUID_STATE_MONITOR_PACKET_XSAVE |
    POLY_CPUID_STATE_CROSS_RETURN_XSAVE |
    POLY_CPUID_STATE_FRONTEND_TLS_XSAVE |
    POLY_CPUID_STATE_LANDING_POLICY_XSAVE |
    POLY_CPUID_STATE_STATE_KEY_XSAVE |
    POLY_CPUID_STATE_TRAP_RESTORE_XSAVE |
    POLY_CPUID_STATE_NATIVE_RETURN_XSAVE;
  regs.ebx = 0;
  regs.ecx = POLY_STATE_XSAVE_COMPONENT_ARCH;
  regs.edx = POLY_STATE_XSAVE_BYTES_ARCH;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_arch_state_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_COMPONENT_ARCH;
  regs.ebx = (uint32_t) sizeof(struct poly_xsave_state);
  regs.ecx = POLY_STATE_XSAVE_LAYOUT_VERSION |
    (POLY_STATE_XSAVE_ALIGN_ARCH << 16);
  regs.edx = POLY_STATE_XSAVE_FLAG_XCR0_USER |
    POLY_STATE_XSAVE_FLAG_OSXSAVE_REQUIRED |
    POLY_STATE_XSAVE_FLAG_INTERRUPT_RESUME |
    POLY_STATE_XSAVE_FLAG_TRAP_STATE |
    POLY_STATE_XSAVE_FLAG_COMPLETE_BANK_EXPORT |
    POLY_STATE_XSAVE_FLAG_IMPORT_RETURN |
    POLY_STATE_XSAVE_FLAG_ABI_SIGNATURES |
    POLY_STATE_XSAVE_FLAG_MONITOR_PACKET |
    POLY_STATE_XSAVE_FLAG_CROSS_RETURN |
    POLY_STATE_XSAVE_FLAG_FRONTEND_TLS |
    POLY_STATE_XSAVE_FLAG_LANDING_POLICY |
    POLY_STATE_XSAVE_FLAG_STATE_KEY |
    POLY_STATE_XSAVE_FLAG_TRAP_RESTORE |
    POLY_STATE_XSAVE_FLAG_NATIVE_RETURN;
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_arch_state_header_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_HEADER_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_HEADER_BYTES;
  regs.ecx = POLY_STATE_XSAVE_MAGIC;
  regs.edx = POLY_STATE_XSAVE_LAYOUT_VERSION;
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_arch_state_trap_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_TRAP_PACKET_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_TRAP_PACKET_BYTES;
  regs.ecx = POLY_STATE_XSAVE_TRAP_ARGS_OFFSET;
  regs.edx = POLY_STATE_XSAVE_TRAP_ARGS_BYTES;
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_arch_state_aarch64_gpr_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_AARCH64_GPR_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_AARCH64_GPR_BYTES;
  regs.ecx = 32;
  regs.edx = (uint32_t) sizeof(uint64_t);
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_arch_state_aarch64_fp_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_AARCH64_FP_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_AARCH64_FP_BYTES;
  regs.ecx = 32;
  regs.edx = (uint32_t) sizeof(struct poly_u128);
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_arch_state_aarch64_status_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_AARCH64_STATUS_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_AARCH64_STATUS_BYTES;
  regs.ecx = (uint32_t) sizeof(struct poly_aarch64_status_state);
  regs.edx = 0;
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_arch_state_riscv_gpr_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_RISCV_GPR_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_RISCV_GPR_BYTES;
  regs.ecx = 32;
  regs.edx = (uint32_t) sizeof(uint64_t);
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_arch_state_riscv_fp_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_RISCV_FP_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_RISCV_FP_BYTES;
  regs.ecx = 32;
  regs.edx = (uint32_t) sizeof(struct poly_u128);
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_arch_state_riscv_status_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_RISCV_STATUS_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_RISCV_STATUS_BYTES;
  regs.ecx = (uint32_t) sizeof(struct poly_riscv_status_state);
  regs.edx = 0;
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_arch_state_abi_signature_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_ABI_SIGNATURE_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_ABI_SIGNATURE_BYTES;
  regs.ecx = POLY_ABI_SIGNATURE_SLOT_COUNT;
  regs.edx = (uint32_t) sizeof(struct poly_abi_signature_slot_state);
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_arch_state_frontend_tls_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_FRONTEND_TLS_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_FRONTEND_TLS_BYTES;
  regs.ecx = (uint32_t) sizeof(struct poly_frontend_tls_state);
  regs.edx = 0;
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_arch_state_landing_policy_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_LANDING_POLICY_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_LANDING_POLICY_BYTES;
  regs.ecx = (uint32_t) POLY_LANDING_POLICY_SUPPORTED;
  regs.edx = 0;
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_arch_state_state_key_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_STATE_KEY_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_STATE_KEY_BYTES;
  regs.ecx = (uint32_t) POLY_STATE_KEY_FLAG_EXPLICIT;
  regs.edx = 0;
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_arch_state_trap_restore_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_TRAP_RESTORE_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_TRAP_RESTORE_BYTES;
  regs.ecx = POLY_TRAP_RESTORE_FLAG_VALID |
    POLY_TRAP_RESTORE_FLAG_AARCH64_STATE_VALID |
    POLY_TRAP_RESTORE_FLAG_RISCV_STATE_VALID;
  regs.edx = 0;
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_arch_state_native_return_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_NATIVE_RETURN_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_NATIVE_RETURN_BYTES;
  regs.ecx = POLY_STATE_XSAVE_NATIVE_RETURN_DEPTH;
  regs.edx = POLY_STATE_XSAVE_NATIVE_RETURN_FRAME_BYTES;
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_arch_state_reserved_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_RESERVED_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_RESERVED_BYTES;
  regs.ecx = 0;
  regs.edx = 0;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_trap_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_TRAP_PACKET_LAYOUT_VERSION;
  regs.ebx = (uint32_t) sizeof(struct poly_trap_packet);
  regs.ecx = (uint32_t) (sizeof(((struct poly_xsave_state *) 0)->trap_args) /
    sizeof(((struct poly_xsave_state *) 0)->trap_args[0]));
  regs.edx = POLY_TRAP_PACKET_REQUIRED_FLAGS;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_interrupt_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_INTERRUPT_ABI_VERSION;
  regs.ebx = POLY_INTERRUPT_FLAG_RAW_CPL3_ONLY |
    POLY_INTERRUPT_FLAG_STANDARD_X86_ENTRY |
    POLY_INTERRUPT_FLAG_STATE_COMPONENT_SAVE |
    POLY_INTERRUPT_FLAG_PRECISE_FOREIGN_PC |
    POLY_INTERRUPT_FLAG_EVENT_CHECK_BETWEEN_INSNS;
  regs.ecx = POLY_INTERRUPT_RETURN_IRET64 |
    POLY_INTERRUPT_RETURN_SYSRET |
    POLY_INTERRUPT_RETURN_SYSEXIT |
    POLY_INTERRUPT_RETURN_SIGNAL;
  regs.edx = (1U << POLY_MODE_RAW_AARCH64) |
    (1U << POLY_MODE_RAW_RISCV);
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_memory_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_MEMORY_ABI_VERSION;
  regs.ebx = POLY_MEMORY_MODEL_X86_TSO;
  regs.ecx = POLY_MEMORY_FLAG_SHARED_X86_MEMORY |
    POLY_MEMORY_FLAG_AARCH64_BARRIERS_NOOP |
    POLY_MEMORY_FLAG_RISCV_FENCES_NOOP |
    POLY_MEMORY_FLAG_ATOMICS_COHERENT |
    POLY_MEMORY_FLAG_NO_WEAK_REORDERING;
  regs.edx = (1U << POLY_MODE_RAW_AARCH64) |
    (1U << POLY_MODE_RAW_RISCV);
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_transition_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_TRANSITION_ABI_VERSION;
  regs.ebx = POLY_TRANSITION_FLAG_DECODED_X86_OPCODES |
    POLY_TRANSITION_FLAG_NATIVE_RAW_ESCAPES |
    POLY_TRANSITION_FLAG_PIPELINE_FLUSH |
    POLY_TRANSITION_FLAG_BLOCK_BOUNDARY |
    POLY_TRANSITION_FLAG_PRECISE_NEXT_PC |
    POLY_TRANSITION_FLAG_NATIVE_FRONTEND_WIDTHS |
    POLY_TRANSITION_FLAG_NEUTRAL_FOREIGN |
    POLY_TRANSITION_FLAG_NATIVE_RETURN_COOKIE |
    POLY_TRANSITION_FLAG_TRAP_RETURN |
    POLY_TRANSITION_FLAG_INTERRUPTED_RAW |
    POLY_TRANSITION_FLAG_LANDING_PADS |
    POLY_TRANSITION_FLAG_LANDING_POLICY;
  regs.ecx = POLY_TRANSITION_AARCH64_ALIGN |
    (POLY_TRANSITION_RISCV_ALIGN << 16);
  regs.edx = poly_cpuid_expected_mode_mask();
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_transition_layout_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_TRANSITION_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_TRANSITION_BYTES;
  regs.ecx = (uint32_t) sizeof(struct poly_transition_frame);
  regs.edx = 0;
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_transition_cross_return_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_CROSS_RETURN_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_CROSS_RETURN_BYTES;
  regs.ecx = POLY_STATE_XSAVE_CROSS_RETURN_DEPTH;
  regs.edx = POLY_STATE_XSAVE_CROSS_RETURN_FRAME_BYTES;
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_transition_import_return_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_IMPORT_RETURN_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_IMPORT_RETURN_BYTES;
  regs.ecx = POLY_STATE_XSAVE_IMPORT_RETURN_DEPTH;
  regs.edx = POLY_STATE_XSAVE_IMPORT_RETURN_FRAME_BYTES;
  return regs;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_transition_native_return_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_NATIVE_RETURN_OFFSET;
  regs.ebx = POLY_STATE_XSAVE_NATIVE_RETURN_BYTES;
  regs.ecx = POLY_STATE_XSAVE_NATIVE_RETURN_DEPTH;
  regs.edx = POLY_STATE_XSAVE_NATIVE_RETURN_FRAME_BYTES;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_frontend_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_FRONTEND_X86;
  regs.ebx = POLY_FRONTEND_AARCH64;
  regs.ecx = POLY_FRONTEND_RISCV;
  regs.edx = poly_cpuid_expected_frontend_mask();
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_abi_bridge_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_ABI_BRIDGE_ABI_VERSION;
  regs.ebx = POLY_ABI_BRIDGE_FLAG_X86_SYSV_TO_AAPCS64 |
    POLY_ABI_BRIDGE_FLAG_X86_SYSV_TO_RISCV |
    POLY_ABI_BRIDGE_FLAG_SRET |
    POLY_ABI_BRIDGE_FLAG_SCALAR_FP |
    POLY_ABI_BRIDGE_FLAG_REGISTER_ONLY_AGGREGATES |
    POLY_ABI_BRIDGE_FLAG_TLS_BASE |
    POLY_ABI_BRIDGE_FLAG_NO_CPU_HELPER_FALLBACK |
    POLY_ABI_BRIDGE_FLAG_ORDINARY_X86_RET |
    POLY_ABI_BRIDGE_FLAG_VEC128 |
    POLY_ABI_BRIDGE_FLAG_REGISTER_SIGNATURES |
    POLY_ABI_BRIDGE_FLAG_NATIVE_I128_SIGNATURES |
    POLY_ABI_BRIDGE_FLAG_REGISTER_MAP_SIGNATURES;
  regs.ecx = POLY_ABI_BRIDGE_GPR_ARG_COUNT |
    (POLY_ABI_BRIDGE_FP_ARG_COUNT << 8) |
    (POLY_ABI_BRIDGE_STACK_ALIGN << 16);
  regs.edx = 0;
  return regs;
}

static inline uint32_t poly_cpuid_forbidden_abi_bridge_mask(void) {
  return POLY_ABI_BRIDGE_FLAG_HARDWARE_IMPORT_DESCRIPTORS |
    POLY_ABI_BRIDGE_FLAG_HARDWARE_STACK_ARGS |
    POLY_ABI_BRIDGE_FLAG_HARDWARE_USER_DESCRIPTORS;
}

struct poly_cpuid_contract_check {
  const char *name;
  uint32_t leaf;
  uint32_t subleaf;
  struct poly_cpuid_regs expected;
};

struct poly_cpuid_contract_failure {
  const char *name;
  uint32_t leaf;
  uint32_t subleaf;
  struct poly_cpuid_regs actual;
  struct poly_cpuid_regs expected;
};

static inline int poly_cpuid_arch_state_contract_check(size_t index,
    struct poly_cpuid_contract_check *check) {
  switch (index) {
  case 0:
    check->name = "poly state contract";
    check->leaf = POLY_CPUID_BASE + 3;
    check->subleaf = 0;
    check->expected = poly_cpuid_expected_state_leaf();
    return 1;
  case 1:
    check->name = "poly XSAVE state contract";
    check->leaf = POLY_CPUID_BASE + 4;
    check->subleaf = 0;
    check->expected = poly_cpuid_expected_arch_state_leaf();
    return 1;
  case 2:
    check->name = "poly XSAVE header layout";
    check->leaf = POLY_CPUID_BASE + 4;
    check->subleaf = 1;
    check->expected = poly_cpuid_expected_arch_state_header_leaf();
    return 1;
  case 3:
    check->name = "poly XSAVE trap layout";
    check->leaf = POLY_CPUID_BASE + 4;
    check->subleaf = 2;
    check->expected = poly_cpuid_expected_arch_state_trap_leaf();
    return 1;
  case 4:
    check->name = "poly AArch64 GPR layout";
    check->leaf = POLY_CPUID_BASE + 4;
    check->subleaf = 3;
    check->expected = poly_cpuid_expected_arch_state_aarch64_gpr_leaf();
    return 1;
  case 5:
    check->name = "poly AArch64 FP layout";
    check->leaf = POLY_CPUID_BASE + 4;
    check->subleaf = 4;
    check->expected = poly_cpuid_expected_arch_state_aarch64_fp_leaf();
    return 1;
  case 6:
    check->name = "poly AArch64 status layout";
    check->leaf = POLY_CPUID_BASE + 4;
    check->subleaf = 5;
    check->expected = poly_cpuid_expected_arch_state_aarch64_status_leaf();
    return 1;
  case 7:
    check->name = "poly RISC-V GPR layout";
    check->leaf = POLY_CPUID_BASE + 4;
    check->subleaf = 6;
    check->expected = poly_cpuid_expected_arch_state_riscv_gpr_leaf();
    return 1;
  case 8:
    check->name = "poly RISC-V FP layout";
    check->leaf = POLY_CPUID_BASE + 4;
    check->subleaf = 7;
    check->expected = poly_cpuid_expected_arch_state_riscv_fp_leaf();
    return 1;
  case 9:
    check->name = "poly RISC-V status layout";
    check->leaf = POLY_CPUID_BASE + 4;
    check->subleaf = 8;
    check->expected = poly_cpuid_expected_arch_state_riscv_status_leaf();
    return 1;
  case 10:
    check->name = "poly ABI signature layout";
    check->leaf = POLY_CPUID_BASE + 4;
    check->subleaf = 9;
    check->expected = poly_cpuid_expected_arch_state_abi_signature_leaf();
    return 1;
  case 11:
    check->name = "poly frontend TLS layout";
    check->leaf = POLY_CPUID_BASE + 4;
    check->subleaf = 10;
    check->expected = poly_cpuid_expected_arch_state_frontend_tls_leaf();
    return 1;
  case 12:
    check->name = "poly landing policy layout";
    check->leaf = POLY_CPUID_BASE + 4;
    check->subleaf = 11;
    check->expected = poly_cpuid_expected_arch_state_landing_policy_leaf();
    return 1;
  case 13:
    check->name = "poly state-key layout";
    check->leaf = POLY_CPUID_BASE + 4;
    check->subleaf = 12;
    check->expected = poly_cpuid_expected_arch_state_state_key_leaf();
    return 1;
  case 14:
    check->name = "poly trap-restore layout";
    check->leaf = POLY_CPUID_BASE + 4;
    check->subleaf = 13;
    check->expected = poly_cpuid_expected_arch_state_trap_restore_leaf();
    return 1;
  case 15:
    check->name = "poly native-return layout";
    check->leaf = POLY_CPUID_BASE + 4;
    check->subleaf = 14;
    check->expected = poly_cpuid_expected_arch_state_native_return_leaf();
    return 1;
  case 16:
    check->name = "poly XSAVE reserved layout";
    check->leaf = POLY_CPUID_BASE + 4;
    check->subleaf = 15;
    check->expected = poly_cpuid_expected_arch_state_reserved_leaf();
    return 1;
  case 17:
    check->name = "poly transition contract";
    check->leaf = POLY_CPUID_BASE + 8;
    check->subleaf = 0;
    check->expected = poly_cpuid_expected_transition_leaf();
    return 1;
  case 18:
    check->name = "poly transition frame layout";
    check->leaf = POLY_CPUID_BASE + 8;
    check->subleaf = 2;
    check->expected = poly_cpuid_expected_transition_layout_leaf();
    return 1;
  case 19:
    check->name = "poly cross-return layout";
    check->leaf = POLY_CPUID_BASE + 8;
    check->subleaf = 3;
    check->expected = poly_cpuid_expected_transition_cross_return_leaf();
    return 1;
  case 20:
    check->name = "poly import-return layout";
    check->leaf = POLY_CPUID_BASE + 8;
    check->subleaf = 4;
    check->expected = poly_cpuid_expected_transition_import_return_leaf();
    return 1;
  case 21:
    check->name = "poly native-return transition layout";
    check->leaf = POLY_CPUID_BASE + 8;
    check->subleaf = 5;
    check->expected = poly_cpuid_expected_transition_native_return_leaf();
    return 1;
  default:
    return 0;
  }
}

static inline int poly_cpuid_regs_match(const struct poly_cpuid_regs *actual,
    const struct poly_cpuid_regs *expected) {
  return actual->eax == expected->eax &&
    actual->ebx == expected->ebx &&
    actual->ecx == expected->ecx &&
    actual->edx == expected->edx;
}

static inline int poly_cpuid_xsave_leaf0_supports_arch_state(
    const struct poly_cpuid_regs *regs) {
  return (regs->eax & (1U << POLY_STATE_XSAVE_COMPONENT_ARCH)) != 0 &&
    regs->ecx >= POLY_STATE_XSAVE_OFFSET_ARCH + POLY_STATE_XSAVE_BYTES_ARCH;
}

static inline struct poly_cpuid_regs
poly_cpuid_expected_standard_xsave_arch_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_BYTES_ARCH;
  regs.ebx = POLY_STATE_XSAVE_OFFSET_ARCH;
  regs.ecx = 0x2;
  regs.edx = 0;
  return regs;
}

static inline int poly_cpuid_verify_arch_state_contract(
    struct poly_cpuid_contract_failure *failure) {
  struct poly_cpuid_contract_check check;
  for (size_t i = 0; poly_cpuid_arch_state_contract_check(i, &check); i++) {
    const struct poly_cpuid_regs actual =
      poly_read_cpuid(check.leaf, check.subleaf);
    if (!poly_cpuid_regs_match(&actual, &check.expected)) {
      failure->name = check.name;
      failure->leaf = check.leaf;
      failure->subleaf = check.subleaf;
      failure->actual = actual;
      failure->expected = check.expected;
      return 0;
    }
  }

  const struct poly_cpuid_regs xsave0 = poly_read_cpuid(0x0000000d, 0);
  if (!poly_cpuid_xsave_leaf0_supports_arch_state(&xsave0)) {
    struct poly_cpuid_regs expected;
    expected.eax = 1U << POLY_STATE_XSAVE_COMPONENT_ARCH;
    expected.ebx = 0;
    expected.ecx = POLY_STATE_XSAVE_OFFSET_ARCH + POLY_STATE_XSAVE_BYTES_ARCH;
    expected.edx = 0;
    failure->name = "standard XSAVE Poly component support";
    failure->leaf = 0x0000000d;
    failure->subleaf = 0;
    failure->actual = xsave0;
    failure->expected = expected;
    return 0;
  }

  const struct poly_cpuid_regs expected_xsave =
    poly_cpuid_expected_standard_xsave_arch_leaf();
  const struct poly_cpuid_regs xsave_poly =
    poly_read_cpuid(0x0000000d, POLY_STATE_XSAVE_COMPONENT_ARCH);
  if (!poly_cpuid_regs_match(&xsave_poly, &expected_xsave)) {
    failure->name = "standard XSAVE Poly component";
    failure->leaf = 0x0000000d;
    failure->subleaf = POLY_STATE_XSAVE_COMPONENT_ARCH;
    failure->actual = xsave_poly;
    failure->expected = expected_xsave;
    return 0;
  }

  return 1;
}

static inline void poly_cpuid_vendor_string(const struct poly_cpuid_regs *regs,
    char vendor[13]) {
  memcpy(vendor, &regs->ebx, 4);
  memcpy(vendor + 4, &regs->edx, 4);
  memcpy(vendor + 8, &regs->ecx, 4);
  vendor[12] = '\0';
}

static inline int poly_cpuid_vendor_matches(const struct poly_cpuid_regs *regs) {
  char vendor[13];
  poly_cpuid_vendor_string(regs, vendor);
  return strcmp(vendor, "PolyglotCPU!") == 0;
}

static inline int poly_cpuid_present(void) {
  struct poly_cpuid_regs regs = poly_read_cpuid(POLY_CPUID_BASE, 0);
  return regs.eax >= POLY_CPUID_MAX && poly_cpuid_vendor_matches(&regs);
}

#endif
