#ifndef POLYCPUID_H
#define POLYCPUID_H

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#define POLY_AARCH64_CTRL_ENCODING(subop) \
  (0xd503201fU | (((uint32_t) (subop) & 0x7fU) << 5))
#define POLY_RISCV_CTRL_ENCODING(subop) \
  (0x0000700bU | (((uint32_t) (subop) & 0x7fU) << 25))

#define POLY_AARCH64_CTRL_X86_ESCAPE \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_X86_ESCAPE)
#define POLY_AARCH64_CTRL_RISCV_SWITCH \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_RISCV_SWITCH)
#define POLY_AARCH64_CTRL_RISCV_CALL \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_RISCV_CALL)
#define POLY_AARCH64_CTRL_RISCV_CALL_COMPACT_U32_F32 \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_RISCV_CALL_COMPACT_U32_F32)
#define POLY_AARCH64_CTRL_RISCV_CALL_COMPACT_F32_U32 \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_RISCV_CALL_COMPACT_F32_U32)
#define POLY_AARCH64_CTRL_RISCV_CALL_FP64_STACK \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_RISCV_CALL_FP64_STACK)
#define POLY_AARCH64_CTRL_TRAP_RETURN \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_TRAP_RETURN)
#define POLY_AARCH64_CTRL_RISCV_CALL_VEC128_U32 \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_RISCV_CALL_VEC128_U32)
#define POLY_AARCH64_CTRL_SWITCH_MODE \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_SWITCH_MODE)
#define POLY_AARCH64_CTRL_CALL_MODE \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_CALL_MODE)
#define POLY_AARCH64_CTRL_CALL_SIG_MODE \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_CALL_SIG_MODE)
#define POLY_AARCH64_CTRL_CALL_SIG_IMM(slot) \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_CALL_SIG_IMM_BASE + \
    ((uint32_t) (slot) & 0x7U))
#define POLY_AARCH64_CTRL_LANDING \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_LANDING)
#define POLY_AARCH64_CTRL_ABI_SIGNATURE_SET \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_ABI_SIGNATURE_SET)
#define POLY_AARCH64_CTRL_ABI_SIGNATURE_GET \
  POLY_AARCH64_CTRL_ENCODING(POLY_AARCH64_CTRL_SUBOP_ABI_SIGNATURE_GET)

#define POLY_RISCV_CTRL_X86_ESCAPE \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_X86_ESCAPE)
#define POLY_RISCV_CTRL_AARCH64_SWITCH \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_AARCH64_SWITCH)
#define POLY_RISCV_CTRL_AARCH64_CALL \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_AARCH64_CALL)
#define POLY_RISCV_CTRL_AARCH64_CALL_COMPACT_U32_F32 \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_AARCH64_CALL_COMPACT_U32_F32)
#define POLY_RISCV_CTRL_AARCH64_CALL_COMPACT_F32_U32 \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_AARCH64_CALL_COMPACT_F32_U32)
#define POLY_RISCV_CTRL_AARCH64_CALL_FP64_STACK \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_AARCH64_CALL_FP64_STACK)
#define POLY_RISCV_CTRL_TRAP_RETURN \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_TRAP_RETURN)
#define POLY_RISCV_CTRL_AARCH64_CALL_VEC128_U32 \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_AARCH64_CALL_VEC128_U32)
#define POLY_RISCV_CTRL_SWITCH_MODE \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_SWITCH_MODE)
#define POLY_RISCV_CTRL_CALL_MODE \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_CALL_MODE)
#define POLY_RISCV_CTRL_CALL_SIG_MODE \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_CALL_SIG_MODE)
#define POLY_RISCV_CTRL_CALL_SIG_IMM(slot) \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_CALL_SIG_IMM_BASE + \
    ((uint32_t) (slot) & 0x7U))
#define POLY_RISCV_CTRL_LANDING \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_LANDING)
#define POLY_RISCV_CTRL_ABI_SIGNATURE_SET \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_ABI_SIGNATURE_SET)
#define POLY_RISCV_CTRL_ABI_SIGNATURE_GET \
  POLY_RISCV_CTRL_ENCODING(POLY_RISCV_CTRL_SUBOP_ABI_SIGNATURE_GET)

enum {
  POLY_FRONTEND_X86 = 0,
  POLY_FRONTEND_AARCH64 = 1,
  POLY_FRONTEND_RISCV = 2,
  POLY_FRONTEND_COUNT = 3,
  POLY_MODE_X86 = 0,
  POLY_MODE_RAW_AARCH64 = 3,
  POLY_MODE_RAW_RISCV = 4,
  POLY_TRAP_SYSCALL = 1,
  POLY_TRAP_BREAK = 2,
  POLY_TRAP_IMPORT = 3,
  POLY_TRAP_ILLEGAL = 4,
  POLY_CPUID_BASE = 0x40000000,
  POLY_CPUID_MAX = 0x40000009,
  POLY_CPUID_ABI_VERSION = 1,
  POLY_AARCH64_CTRL_SUBOP_CALL_SIG_IMM_BASE = 0x60,
  POLY_AARCH64_CTRL_SUBOP_X86_ESCAPE = 0x70,
  POLY_AARCH64_CTRL_SUBOP_RISCV_SWITCH = 0x71,
  POLY_AARCH64_CTRL_SUBOP_RISCV_CALL = 0x72,
  POLY_AARCH64_CTRL_SUBOP_RISCV_CALL_COMPACT_U32_F32 = 0x73,
  POLY_AARCH64_CTRL_SUBOP_RISCV_CALL_COMPACT_F32_U32 = 0x74,
  POLY_AARCH64_CTRL_SUBOP_RISCV_CALL_FP64_STACK = 0x75,
  POLY_AARCH64_CTRL_SUBOP_TRAP_RETURN = 0x76,
  POLY_AARCH64_CTRL_SUBOP_RISCV_CALL_VEC128_U32 = 0x77,
  POLY_AARCH64_CTRL_SUBOP_SWITCH_MODE = 0x78,
  POLY_AARCH64_CTRL_SUBOP_CALL_MODE = 0x79,
  POLY_AARCH64_CTRL_SUBOP_CALL_SIG_MODE = 0x7a,
  POLY_AARCH64_CTRL_SUBOP_LANDING = 0x7b,
  POLY_AARCH64_CTRL_SUBOP_ABI_SIGNATURE_SET = 0x7c,
  POLY_AARCH64_CTRL_SUBOP_ABI_SIGNATURE_GET = 0x7d,
  POLY_RISCV_CTRL_SUBOP_X86_ESCAPE = 0,
  POLY_RISCV_CTRL_SUBOP_AARCH64_SWITCH = 1,
  POLY_RISCV_CTRL_SUBOP_AARCH64_CALL = 2,
  POLY_RISCV_CTRL_SUBOP_AARCH64_CALL_COMPACT_U32_F32 = 3,
  POLY_RISCV_CTRL_SUBOP_AARCH64_CALL_COMPACT_F32_U32 = 4,
  POLY_RISCV_CTRL_SUBOP_AARCH64_CALL_FP64_STACK = 5,
  POLY_RISCV_CTRL_SUBOP_TRAP_RETURN = 6,
  POLY_RISCV_CTRL_SUBOP_AARCH64_CALL_VEC128_U32 = 7,
  POLY_RISCV_CTRL_SUBOP_SWITCH_MODE = 8,
  POLY_RISCV_CTRL_SUBOP_CALL_MODE = 9,
  POLY_RISCV_CTRL_SUBOP_CALL_SIG_MODE = 10,
  POLY_RISCV_CTRL_SUBOP_LANDING = 11,
  POLY_RISCV_CTRL_SUBOP_ABI_SIGNATURE_SET = 12,
  POLY_RISCV_CTRL_SUBOP_ABI_SIGNATURE_GET = 13,
  POLY_RISCV_CTRL_SUBOP_CALL_SIG_IMM_BASE = 16,
  POLY_X86_CTRL_LANDING = 0x05,
  POLY_X86_CTRL_PCALL_SIG_IMM_MODE = 0x2e,
  POLY_IMPORT_FUNC_X86_SLOT0 = 106,
  POLY_IMPORT_FUNC_X86_SLOT1 = 107,
  POLY_IMPORT_FUNC_X86_SLOT2 = 108,
  POLY_IMPORT_FUNC_X86_SLOT3 = 109,
  POLY_IMPORT_FUNC_X86_SLOT4 = 110,
  POLY_IMPORT_FUNC_X86_SLOT5 = 111,
  POLY_IMPORT_FUNC_X86_SLOT6 = 112,
  POLY_IMPORT_FUNC_X86_SLOT7 = 113,
  POLY_IMPORT_FUNC_X86_SUM10 = 144,
  POLY_IMPORT_FUNC_X86_FP64_SUM10 = 145,
  POLY_IMPORT_FUNC_X86_FPAIR64 = 146,
  POLY_IMPORT_FUNC_X86_FPAIR32 = 147,
  POLY_IMPORT_FUNC_X86_VEC128_U32 = 148,
  POLY_IMPORT_FUNC_X86_SRET_U64 = 149,
  POLY_IMPORT_FUNC_X86_SRET_U64_STACK = 150,
  POLY_IMPORT_FUNC_X86_SRET_U64_STACK10 = 151,
  POLY_IMPORT_FUNC_X86_SUM14 = 152,
  POLY_IMPORT_FUNC_X86_ALIGN14 = 153,
  POLY_IMPORT_FUNC_X86_I128 = 154,
  POLY_IMPORT_FUNC_QSORT = 155,
  POLY_IMPORT_FUNC_BSEARCH = 156,
  POLY_IMPORT_FUNC_QSORT_R = 157,
  POLY_IMPORT_FUNC_PTHREAD_ONCE = 158,
  POLY_IMPORT_FUNC_PTHREAD_KEY_CREATE = 159,
  POLY_IMPORT_FUNC_PTHREAD_KEY_DELETE = 160,
  POLY_IMPORT_FUNC_PTHREAD_GETSPECIFIC = 161,
  POLY_IMPORT_FUNC_PTHREAD_SETSPECIFIC = 162,
  POLY_IMPORT_FUNC_PTHREAD_MUTEX_INIT = 163,
  POLY_IMPORT_FUNC_PTHREAD_MUTEX_DESTROY = 164,
  POLY_IMPORT_FUNC_PTHREAD_MUTEX_LOCK = 165,
  POLY_IMPORT_FUNC_PTHREAD_MUTEX_TRYLOCK = 166,
  POLY_IMPORT_FUNC_PTHREAD_MUTEX_UNLOCK = 167,
  POLY_IMPORT_FUNC_PTHREAD_SELF = 168,
  POLY_IMPORT_FUNC_PTHREAD_EQUAL = 169,
  POLY_IMPORT_FUNC_PTHREAD_RWLOCK_INIT = 170,
  POLY_IMPORT_FUNC_PTHREAD_RWLOCK_DESTROY = 171,
  POLY_IMPORT_FUNC_PTHREAD_RWLOCK_RDLOCK = 172,
  POLY_IMPORT_FUNC_PTHREAD_RWLOCK_TRYRDLOCK = 173,
  POLY_IMPORT_FUNC_PTHREAD_RWLOCK_WRLOCK = 174,
  POLY_IMPORT_FUNC_PTHREAD_RWLOCK_TRYWRLOCK = 175,
  POLY_IMPORT_FUNC_PTHREAD_RWLOCK_UNLOCK = 176,
  POLY_IMPORT_FUNC_PTHREAD_MUTEXATTR_INIT = 177,
  POLY_IMPORT_FUNC_PTHREAD_MUTEXATTR_DESTROY = 178,
  POLY_IMPORT_FUNC_PTHREAD_MUTEXATTR_SETTYPE = 179,
  POLY_IMPORT_FUNC_PTHREAD_MUTEXATTR_GETTYPE = 180,
  POLY_IMPORT_FUNC_PTHREAD_SPIN_INIT = 181,
  POLY_IMPORT_FUNC_PTHREAD_SPIN_DESTROY = 182,
  POLY_IMPORT_FUNC_PTHREAD_SPIN_LOCK = 183,
  POLY_IMPORT_FUNC_PTHREAD_SPIN_TRYLOCK = 184,
  POLY_IMPORT_FUNC_PTHREAD_SPIN_UNLOCK = 185,
  POLY_IMPORT_FUNC_PTHREAD_COND_INIT = 186,
  POLY_IMPORT_FUNC_PTHREAD_COND_DESTROY = 187,
  POLY_IMPORT_FUNC_PTHREAD_COND_SIGNAL = 188,
  POLY_IMPORT_FUNC_PTHREAD_COND_BROADCAST = 189,
  POLY_IMPORT_FUNC_CLOCK_GETTIME = 190,
  POLY_IMPORT_FUNC_CLOCK_GETRES = 191,
  POLY_IMPORT_FUNC_TIME = 192,
  POLY_IMPORT_FUNC_GETTIMEOFDAY = 193,
  POLY_IMPORT_FUNC_CLOCK = 194,
  POLY_IMPORT_FUNC_ATOI = 195,
  POLY_IMPORT_FUNC_STRTOL = 196,
  POLY_IMPORT_FUNC_STRTOUL = 197,
  POLY_IMPORT_FUNC_STRTOLL = 198,
  POLY_IMPORT_FUNC_STRTOULL = 199,
  POLY_IMPORT_FUNC_COUNT = 200,
  POLY_IMPORT_X86_DESCRIPTOR_SIZE = 32,
  POLY_IMPORT_CALL_STRIDE = 16,
  POLY_IMPORT_X86_DESCRIPTOR_STACK_ARGS = (1U << 0),
  POLY_IMPORT_X86_DESCRIPTOR_RETURN_I128 = (1U << 1),
  POLY_IMPORT_X86_DESCRIPTOR_RETURN_FP128 = (1U << 2),
  POLY_IMPORT_X86_DESCRIPTOR_STACK_FROM_MEMORY = (1U << 3),
  POLY_IMPORT_X86_DESCRIPTOR_STACK_FROM_GPR0 = (1U << 4),
  POLY_IMPORT_X86_DESCRIPTOR_RETURN_FPAIR64 = (1U << 5),
  POLY_IMPORT_X86_DESCRIPTOR_RETURN_FPAIR32 = (1U << 6),
  POLY_IMPORT_X86_DESCRIPTOR_RETURN_VEC128 = (1U << 7),
  POLY_IMPORT_X86_DESCRIPTOR_VEC128_FROM_GPR_PAIRS = (1U << 8),
  POLY_IMPORT_X86_DESCRIPTOR_AARCH64_SRET_X8 = (1U << 9),
  POLY_CPUID_FEATURE_RAW_AARCH64 = (1U << 0),
  POLY_CPUID_FEATURE_RAW_RISCV = (1U << 1),
  POLY_CPUID_FEATURE_NEUTRAL_SWITCH = (1U << 2),
  POLY_CPUID_FEATURE_NATIVE_RET = (1U << 3),
  POLY_CPUID_FEATURE_PCALL_SYSV = (1U << 4),
  POLY_CPUID_FEATURE_PCALL_SRET = (1U << 5),
  POLY_CPUID_FEATURE_FP_BRIDGE = (1U << 6),
  POLY_CPUID_FEATURE_TRAP_RECORDS = (1U << 7),
  POLY_CPUID_FEATURE_USER_RETURN_RESTORE = (1U << 8),
  POLY_CPUID_FEATURE_X86_TSO = (1U << 9),
  POLY_CPUID_FEATURE_THREAD_BANKS = (1U << 10),
  POLY_CPUID_FEATURE_GENERIC_FRONTEND_IDS = (1U << 11),
  POLY_CPUID_FEATURE_X86_POLY_OPCODES = (1U << 12),
  POLY_CPUID_FEATURE_FPAIR32_RET = (1U << 13),
  POLY_CPUID_FEATURE_FPAIR32_ARG = (1U << 14),
  POLY_CPUID_FEATURE_HETERO_U64_F64 = (1U << 15),
  POLY_CPUID_FEATURE_HETERO_F64_U64 = (1U << 16),
  POLY_CPUID_FEATURE_HETERO_U64_F32 = (1U << 17),
  POLY_CPUID_FEATURE_HETERO_F32_U64 = (1U << 18),
  POLY_CPUID_FEATURE_COMPACT_U32_F32 = (1U << 19),
  POLY_CPUID_FEATURE_COMPACT_F32_U32 = (1U << 20),
  POLY_CPUID_FEATURE_NEUTRAL_COMPACT = (1U << 21),
  POLY_CPUID_FEATURE_X86_IMPORT_DESCRIPTORS = (1U << 22),
  POLY_CPUID_FEATURE_FP64_STACK_ARGS = (1U << 23),
  POLY_CPUID_FEATURE_NEUTRAL_FP64_STACK = (1U << 24),
  POLY_CPUID_FEATURE_TRAP_VECTOR = (1U << 25),
  POLY_CPUID_FEATURE_STATE_KEY = (1U << 26),
  POLY_CPUID_FEATURE_VEC128_BRIDGE = (1U << 27),
  POLY_CPUID_FEATURE_AARCH64_HFA64_RET = (1U << 28),
  POLY_CPUID_FEATURE_AARCH64_HFA32_RET = (1U << 29),
  POLY_CPUID_FEATURE_AARCH64_HFA_ARGS = (1U << 30),
  POLY_CPUID_FEATURE_FOREIGN_PCALL_SIG_IMM = (1U << 31),
  POLY_CPUID_STATE_OVERLAP_GPRS = (1U << 0),
  POLY_CPUID_STATE_SYNTHETIC_BANKS = (1U << 1),
  POLY_CPUID_STATE_KEY_CR3 = (1U << 2),
  POLY_CPUID_STATE_KEY_FSBASE = (1U << 3),
  POLY_CPUID_STATE_KEY_STACK_REGION = (1U << 4),
  POLY_CPUID_STATE_USER_RETURN_RESTORE = (1U << 5),
  POLY_CPUID_STATE_X86_TSO = (1U << 6),
  POLY_CPUID_STATE_XSAVE_VISIBLE = (1U << 7),
  POLY_CPUID_STATE_KEY_EXPLICIT = (1U << 8),
  POLY_CPUID_STATE_TRANSITION_FRAME_32 = (1U << 9),
  POLY_CPUID_STATE_EXPLICIT_SAVE_RESTORE = (1U << 10),
  POLY_CPUID_STATE_XSAVE_ARCH_CONTRACT = (1U << 11),
  POLY_CPUID_STATE_IMPORT_RETURN_XSAVE = (1U << 12),
  POLY_CPUID_STATE_ABI_SIGNATURE_XSAVE = (1U << 13),
  POLY_CPUID_STATE_MONITOR_PACKET_XSAVE = (1U << 14),
  POLY_STATE_STACK_KEY_SHIFT = 23,
  POLY_STATE_XSAVE_MAGIC = 0x31594c50, /* "PLY1" */
  POLY_STATE_XSAVE_COMPONENT_NONE = 0,
  POLY_STATE_XSAVE_BYTES_NONE = 0,
  POLY_STATE_XSAVE_COMPONENT_ARCH = 20,
  POLY_STATE_XSAVE_OFFSET_ARCH = 0x3000,
  POLY_STATE_XSAVE_BYTES_ARCH = 4096,
  POLY_STATE_XSAVE_ALIGN_ARCH = 64,
  POLY_STATE_XSAVE_LAYOUT_VERSION = 5,
  POLY_STATE_XSAVE_FLAG_XCR0_USER = (1U << 0),
  POLY_STATE_XSAVE_FLAG_OSXSAVE_REQUIRED = (1U << 1),
  POLY_STATE_XSAVE_FLAG_INTERRUPT_RESUME = (1U << 2),
  POLY_STATE_XSAVE_FLAG_TRAP_STATE = (1U << 3),
  POLY_STATE_XSAVE_FLAG_NO_HIDDEN_BANKS = (1U << 4),
  POLY_STATE_XSAVE_FLAG_IMPORT_RETURN = (1U << 5),
  POLY_STATE_XSAVE_FLAG_ABI_SIGNATURES = (1U << 6),
  POLY_STATE_XSAVE_FLAG_MONITOR_PACKET = (1U << 7),
  POLY_STATE_XSAVE_HEADER_OFFSET = 0x000,
  POLY_STATE_XSAVE_HEADER_BYTES = 0x040,
  POLY_STATE_XSAVE_TRAP_PACKET_OFFSET = 0x040,
  POLY_STATE_XSAVE_TRAP_PACKET_BYTES = 0x040,
  POLY_STATE_XSAVE_TRAP_ARGS_OFFSET = 0x080,
  POLY_STATE_XSAVE_TRAP_ARGS_BYTES = 0x040,
  POLY_STATE_XSAVE_TRANSITION_OFFSET = 0x0c0,
  POLY_STATE_XSAVE_TRANSITION_BYTES = 0x040,
  POLY_STATE_XSAVE_AARCH64_GPR_OFFSET = 0x100,
  POLY_STATE_XSAVE_AARCH64_GPR_BYTES = 0x100,
  POLY_STATE_XSAVE_AARCH64_FP_OFFSET = 0x200,
  POLY_STATE_XSAVE_AARCH64_FP_BYTES = 0x200,
  POLY_STATE_XSAVE_AARCH64_STATUS_OFFSET = 0x400,
  POLY_STATE_XSAVE_AARCH64_STATUS_BYTES = 0x080,
  POLY_STATE_XSAVE_RISCV_GPR_OFFSET = 0x480,
  POLY_STATE_XSAVE_RISCV_GPR_BYTES = 0x100,
  POLY_STATE_XSAVE_RISCV_FP_OFFSET = 0x580,
  POLY_STATE_XSAVE_RISCV_FP_BYTES = 0x200,
  POLY_STATE_XSAVE_RISCV_STATUS_OFFSET = 0x780,
  POLY_STATE_XSAVE_RISCV_STATUS_BYTES = 0x080,
  POLY_STATE_XSAVE_IMPORT_RETURN_OFFSET = 0x800,
  POLY_STATE_XSAVE_IMPORT_RETURN_BYTES = 0x500,
  POLY_STATE_XSAVE_IMPORT_RETURN_DEPTH = 8,
  POLY_STATE_XSAVE_IMPORT_RETURN_FRAME_BYTES = 0x80,
  POLY_STATE_XSAVE_ABI_SIGNATURE_OFFSET = 0xd00,
  POLY_STATE_XSAVE_ABI_SIGNATURE_BYTES = 0x080,
  POLY_STATE_XSAVE_ABI_SIGNATURE_SLOTS_OFFSET =
    POLY_STATE_XSAVE_ABI_SIGNATURE_OFFSET + 0x10,
  POLY_STATE_XSAVE_RESERVED_OFFSET = 0xd80,
  POLY_STATE_XSAVE_RESERVED_BYTES = 0x280,
  POLY_TRAP_PACKET_LAYOUT_VERSION = 2,
  POLY_TRAP_PACKET_HEADER_BYTES = 64,
  POLY_TRAP_PACKET_ARG_COUNT = 8,
  POLY_TRAP_PACKET_FLAG_VECTOR_DELIVERY = (1U << 0),
  POLY_TRAP_PACKET_FLAG_NO_VECTOR_X86_EXCEPTIONS = (1U << 1),
  POLY_TRAP_PACKET_FLAG_TRAP_RETURN_RESTORE = (1U << 2),
  POLY_TRAP_PACKET_FLAG_ALL_FRONTEND_HANDLERS = (1U << 3),
  POLY_TRAP_PACKET_FLAG_STATUS_OPS = (1U << 4),
  POLY_TRAP_PACKET_FLAG_MONITOR_MEMORY = (1U << 5),
  POLY_INTERRUPT_ABI_VERSION = 1,
  POLY_INTERRUPT_FLAG_RAW_CPL3_ONLY = (1U << 0),
  POLY_INTERRUPT_FLAG_STANDARD_X86_ENTRY = (1U << 1),
  POLY_INTERRUPT_FLAG_STATE_COMPONENT_SAVE = (1U << 2),
  POLY_INTERRUPT_FLAG_PRECISE_FOREIGN_PC = (1U << 3),
  POLY_INTERRUPT_FLAG_EVENT_CHECK_BETWEEN_INSNS = (1U << 4),
  POLY_INTERRUPT_RETURN_IRET64 = (1U << 0),
  POLY_INTERRUPT_RETURN_SYSRET = (1U << 1),
  POLY_INTERRUPT_RETURN_SYSEXIT = (1U << 2),
  POLY_INTERRUPT_RETURN_SIGNAL = (1U << 3),
  POLY_MEMORY_ABI_VERSION = 1,
  POLY_MEMORY_MODEL_X86_TSO = 1,
  POLY_MEMORY_FLAG_SHARED_X86_MEMORY = (1U << 0),
  POLY_MEMORY_FLAG_AARCH64_BARRIERS_NOOP = (1U << 1),
  POLY_MEMORY_FLAG_RISCV_FENCES_NOOP = (1U << 2),
  POLY_MEMORY_FLAG_ATOMICS_COHERENT = (1U << 3),
  POLY_MEMORY_FLAG_NO_WEAK_REORDERING = (1U << 4),
  POLY_TRANSITION_ABI_VERSION = 1,
  POLY_TRANSITION_FLAG_DECODED_X86_OPCODES = (1U << 0),
  POLY_TRANSITION_FLAG_NATIVE_RAW_ESCAPES = (1U << 1),
  POLY_TRANSITION_FLAG_PIPELINE_FLUSH = (1U << 2),
  POLY_TRANSITION_FLAG_BLOCK_BOUNDARY = (1U << 3),
  POLY_TRANSITION_FLAG_PRECISE_NEXT_PC = (1U << 4),
  POLY_TRANSITION_FLAG_FIXED_RAW_WIDTH = (1U << 5),
  POLY_TRANSITION_FLAG_NEUTRAL_FOREIGN = (1U << 6),
  POLY_TRANSITION_FLAG_NATIVE_RETURN_COOKIE = (1U << 7),
  POLY_TRANSITION_FLAG_TRAP_RETURN = (1U << 8),
  POLY_TRANSITION_FLAG_INTERRUPTED_RAW = (1U << 9),
  POLY_TRANSITION_FLAG_LANDING_PADS = (1U << 10),
  POLY_TRANSITION_AARCH64_ALIGN = 4,
  POLY_TRANSITION_RISCV_ALIGN = 2,
  POLY_ABI_BRIDGE_ABI_VERSION = 1,
  POLY_ABI_BRIDGE_FLAG_X86_SYSV_TO_AAPCS64 = (1U << 0),
  POLY_ABI_BRIDGE_FLAG_X86_SYSV_TO_RISCV = (1U << 1),
  POLY_ABI_BRIDGE_FLAG_SRET = (1U << 2),
  POLY_ABI_BRIDGE_FLAG_SCALAR_FP = (1U << 3),
  POLY_ABI_BRIDGE_FLAG_FOCUSED_AGGREGATES = (1U << 4),
  POLY_ABI_BRIDGE_FLAG_FP64_STACK = (1U << 5),
  POLY_ABI_BRIDGE_FLAG_DESCRIPTOR_IMPORTS = (1U << 6),
  POLY_ABI_BRIDGE_FLAG_TLS_BASE = (1U << 7),
  POLY_ABI_BRIDGE_FLAG_USER_DESCRIPTORS = (1U << 8),
  POLY_ABI_BRIDGE_FLAG_NO_CPU_HELPER_FALLBACK = (1U << 9),
  POLY_ABI_BRIDGE_FLAG_ORDINARY_X86_RET = (1U << 10),
  POLY_ABI_BRIDGE_FLAG_VEC128 = (1U << 11),
  POLY_ABI_BRIDGE_FLAG_REGISTER_SIGNATURES = (1U << 12),
  POLY_ABI_BRIDGE_GPR_ARG_COUNT = 8,
  POLY_ABI_BRIDGE_FP_ARG_COUNT = 8,
  POLY_ABI_BRIDGE_STACK_ALIGN = 16,
  POLY_ABI_SIGNATURE_SLOT_COUNT = 8,
  POLY_ABI_SIGNATURE_SLOT_EXCHANGE = 0,
  POLY_ABI_SIGNATURE_SLOT_X86_SYSV_REGS = 1,
  POLY_ABI_SIGNATURE_SLOT_X86_SYSV_REGS_I128 = 2,
  POLY_ABI_SIGNATURE_KIND_EXCHANGE = 0,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV = 1,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS = 2,
  POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_I128 = 3
};

static const uint64_t POLY_IMPORT_CALL_BASE = 0xffffffffffffe000ULL;

struct poly_cpuid_regs {
  uint32_t eax;
  uint32_t ebx;
  uint32_t ecx;
  uint32_t edx;
};

struct poly_u128 {
  uint64_t lo;
  uint64_t hi;
};

struct poly_xsave_header {
  uint32_t magic;
  uint16_t layout_version;
  uint16_t header_bytes;
  uint32_t total_bytes;
  uint32_t current_mode;
  uint64_t flags;
  uint64_t foreign_pc;
  uint64_t foreign_tls_base;
  uint64_t trap_vector_pc;
  uint32_t trap_vector_mode;
  uint32_t reserved0;
  uint64_t monitor_packet_addr;
};

struct poly_trap_packet {
  uint32_t reason;
  uint32_t source_mode;
  uint64_t number;
  uint64_t selector;
  uint64_t trap_pc;
  uint64_t resume_pc;
  uint64_t flags;
  uint64_t reserved[2];
};

struct poly_transition_frame {
  uint64_t return_pc;
  uint32_t caller_mode;
  uint32_t target_mode;
  uint16_t abi_kind;
  uint16_t flags;
  uint32_t reserved0;
  uint64_t cookie;
};

struct poly_xsave_transition_area {
  struct poly_transition_frame active;
  uint8_t reserved[POLY_STATE_XSAVE_TRANSITION_BYTES -
    sizeof(struct poly_transition_frame)];
};

struct poly_aarch64_status_state {
  uint64_t nzcv;
  uint64_t fpcr;
  uint64_t fpsr;
  uint64_t reservation_addr;
  uint64_t reservation_value;
  uint64_t reserved[11];
};

struct poly_riscv_status_state {
  uint64_t fcsr;
  uint64_t reservation_addr;
  uint64_t reservation_value;
  uint64_t reserved[13];
};

struct poly_import_return_frame {
  uint32_t source_mode;
  uint32_t alias_valid;
  uint64_t return_pc;
  uint64_t return_sp;
  uint64_t import_id;
  uint64_t descriptor_flags;
  uint64_t alias[6];
  uint64_t reserved[5];
};

struct poly_import_return_state {
  uint64_t top;
  uint64_t depth;
  struct poly_import_return_frame
    frames[POLY_STATE_XSAVE_IMPORT_RETURN_DEPTH];
  uint8_t reserved[POLY_STATE_XSAVE_IMPORT_RETURN_BYTES - 16 -
    POLY_STATE_XSAVE_IMPORT_RETURN_DEPTH *
      sizeof(struct poly_import_return_frame)];
};

struct poly_abi_signature_slot_state {
  uint32_t kind;
  uint32_t reserved;
};

struct poly_abi_signature_state {
  uint64_t slot_count;
  uint64_t flags;
  struct poly_abi_signature_slot_state
    slots[POLY_ABI_SIGNATURE_SLOT_COUNT];
  uint8_t reserved[POLY_STATE_XSAVE_ABI_SIGNATURE_BYTES - 16 -
    POLY_ABI_SIGNATURE_SLOT_COUNT *
      sizeof(struct poly_abi_signature_slot_state)];
};

struct poly_xsave_state {
  struct poly_xsave_header header;
  struct poly_trap_packet trap;
  uint64_t trap_args[POLY_TRAP_PACKET_ARG_COUNT];
  struct poly_xsave_transition_area transition;
  uint64_t aarch64_gpr[32];
  struct poly_u128 aarch64_fp[32];
  struct poly_aarch64_status_state aarch64_status;
  uint64_t riscv_gpr[32];
  struct poly_u128 riscv_fp[32];
  struct poly_riscv_status_state riscv_status;
  struct poly_import_return_state import_return;
  struct poly_abi_signature_state abi_signature;
  uint8_t reserved[POLY_STATE_XSAVE_RESERVED_BYTES];
};

#define POLY_STATIC_ASSERT(cond, msg) _Static_assert(cond, msg)

POLY_STATIC_ASSERT(sizeof(struct poly_u128) == 16,
  "poly_u128 must be 16 bytes");
POLY_STATIC_ASSERT(sizeof(struct poly_xsave_header) ==
  POLY_STATE_XSAVE_HEADER_BYTES,
  "poly XSAVE header size must match CPUID contract");
POLY_STATIC_ASSERT(sizeof(struct poly_trap_packet) ==
  POLY_STATE_XSAVE_TRAP_PACKET_BYTES,
  "poly trap packet size must match CPUID contract");
POLY_STATIC_ASSERT(sizeof(struct poly_transition_frame) == 32,
  "poly transition frame must remain 32 bytes");
POLY_STATIC_ASSERT(sizeof(struct poly_xsave_transition_area) ==
  POLY_STATE_XSAVE_TRANSITION_BYTES,
  "poly transition area size must match XSAVE layout");
POLY_STATIC_ASSERT(sizeof(struct poly_aarch64_status_state) ==
  POLY_STATE_XSAVE_AARCH64_STATUS_BYTES,
  "poly AArch64 status area size must match XSAVE layout");
POLY_STATIC_ASSERT(sizeof(struct poly_riscv_status_state) ==
  POLY_STATE_XSAVE_RISCV_STATUS_BYTES,
  "poly RISC-V status area size must match XSAVE layout");
POLY_STATIC_ASSERT(sizeof(struct poly_import_return_frame) ==
  POLY_STATE_XSAVE_IMPORT_RETURN_FRAME_BYTES,
  "poly import return frame size must match XSAVE layout");
POLY_STATIC_ASSERT(sizeof(struct poly_import_return_state) ==
  POLY_STATE_XSAVE_IMPORT_RETURN_BYTES,
  "poly import return area size must match XSAVE layout");
POLY_STATIC_ASSERT(sizeof(struct poly_abi_signature_state) ==
  POLY_STATE_XSAVE_ABI_SIGNATURE_BYTES,
  "poly ABI signature area size must match XSAVE layout");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, header) ==
  POLY_STATE_XSAVE_HEADER_OFFSET,
  "poly XSAVE header offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, trap) ==
  POLY_STATE_XSAVE_TRAP_PACKET_OFFSET,
  "poly trap packet offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, trap_args) ==
  POLY_STATE_XSAVE_TRAP_ARGS_OFFSET,
  "poly trap args offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, transition) ==
  POLY_STATE_XSAVE_TRANSITION_OFFSET,
  "poly transition area offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, aarch64_gpr) ==
  POLY_STATE_XSAVE_AARCH64_GPR_OFFSET,
  "poly AArch64 GPR offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, aarch64_fp) ==
  POLY_STATE_XSAVE_AARCH64_FP_OFFSET,
  "poly AArch64 FP offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, aarch64_status) ==
  POLY_STATE_XSAVE_AARCH64_STATUS_OFFSET,
  "poly AArch64 status offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, riscv_gpr) ==
  POLY_STATE_XSAVE_RISCV_GPR_OFFSET,
  "poly RISC-V GPR offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, riscv_fp) ==
  POLY_STATE_XSAVE_RISCV_FP_OFFSET,
  "poly RISC-V FP offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, riscv_status) ==
  POLY_STATE_XSAVE_RISCV_STATUS_OFFSET,
  "poly RISC-V status offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, import_return) ==
  POLY_STATE_XSAVE_IMPORT_RETURN_OFFSET,
  "poly import return offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, abi_signature) ==
  POLY_STATE_XSAVE_ABI_SIGNATURE_OFFSET,
  "poly ABI signature offset drifted");
POLY_STATIC_ASSERT(offsetof(struct poly_xsave_state, reserved) ==
  POLY_STATE_XSAVE_RESERVED_OFFSET,
  "poly reserved area offset drifted");
POLY_STATIC_ASSERT(sizeof(struct poly_xsave_state) ==
  POLY_STATE_XSAVE_BYTES_ARCH,
  "poly XSAVE area size must match CPUID contract");

static inline struct poly_cpuid_regs poly_read_cpuid(uint32_t leaf,
    uint32_t subleaf) {
  struct poly_cpuid_regs regs;
  asm volatile("cpuid"
    : "=a"(regs.eax), "=b"(regs.ebx), "=c"(regs.ecx), "=d"(regs.edx)
    : "a"(leaf), "c"(subleaf)
    : "memory");
  return regs;
}

static inline uint32_t poly_cpuid_expected_mode_mask(void) {
  return (1U << POLY_MODE_X86) |
    (1U << POLY_MODE_RAW_AARCH64) |
    (1U << POLY_MODE_RAW_RISCV);
}

static inline uint32_t poly_cpuid_expected_frontend_mask(void) {
  return (1U << POLY_FRONTEND_X86) |
    (1U << POLY_FRONTEND_AARCH64) |
    (1U << POLY_FRONTEND_RISCV);
}

static inline uint32_t poly_cpuid_expected_feature_mask(void) {
  uint32_t mask = POLY_CPUID_FEATURE_RAW_AARCH64 |
    POLY_CPUID_FEATURE_RAW_RISCV |
    POLY_CPUID_FEATURE_NEUTRAL_SWITCH |
    POLY_CPUID_FEATURE_NATIVE_RET |
    POLY_CPUID_FEATURE_PCALL_SYSV |
    POLY_CPUID_FEATURE_PCALL_SRET |
    POLY_CPUID_FEATURE_FP_BRIDGE |
    POLY_CPUID_FEATURE_TRAP_RECORDS |
    POLY_CPUID_FEATURE_USER_RETURN_RESTORE |
    POLY_CPUID_FEATURE_X86_TSO |
    POLY_CPUID_FEATURE_THREAD_BANKS |
    POLY_CPUID_FEATURE_GENERIC_FRONTEND_IDS |
    POLY_CPUID_FEATURE_X86_POLY_OPCODES |
    POLY_CPUID_FEATURE_FPAIR32_RET |
    POLY_CPUID_FEATURE_FPAIR32_ARG |
    POLY_CPUID_FEATURE_HETERO_U64_F64 |
    POLY_CPUID_FEATURE_HETERO_F64_U64 |
    POLY_CPUID_FEATURE_HETERO_U64_F32 |
    POLY_CPUID_FEATURE_HETERO_F32_U64 |
    POLY_CPUID_FEATURE_COMPACT_U32_F32 |
    POLY_CPUID_FEATURE_COMPACT_F32_U32 |
    POLY_CPUID_FEATURE_NEUTRAL_COMPACT |
    POLY_CPUID_FEATURE_FP64_STACK_ARGS |
    POLY_CPUID_FEATURE_NEUTRAL_FP64_STACK |
    POLY_CPUID_FEATURE_TRAP_VECTOR |
    POLY_CPUID_FEATURE_STATE_KEY |
    POLY_CPUID_FEATURE_VEC128_BRIDGE |
    POLY_CPUID_FEATURE_AARCH64_HFA64_RET |
    POLY_CPUID_FEATURE_AARCH64_HFA32_RET |
    POLY_CPUID_FEATURE_AARCH64_HFA_ARGS |
    POLY_CPUID_FEATURE_FOREIGN_PCALL_SIG_IMM;
  return mask;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf0(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_AARCH64_CTRL_X86_ESCAPE;
  regs.ebx = POLY_AARCH64_CTRL_RISCV_SWITCH;
  regs.ecx = POLY_RISCV_CTRL_X86_ESCAPE;
  regs.edx = POLY_RISCV_CTRL_AARCH64_SWITCH;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf1(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_AARCH64_CTRL_RISCV_CALL;
  regs.ebx = POLY_RISCV_CTRL_AARCH64_CALL;
  regs.ecx = POLY_AARCH64_CTRL_RISCV_CALL_COMPACT_U32_F32;
  regs.edx = POLY_RISCV_CTRL_AARCH64_CALL_COMPACT_U32_F32;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf2(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_IMPORT_FUNC_X86_SLOT0;
  regs.ebx = POLY_IMPORT_FUNC_X86_SLOT7 - POLY_IMPORT_FUNC_X86_SLOT0 + 1;
  regs.ecx = POLY_IMPORT_X86_DESCRIPTOR_SIZE;
  regs.edx = POLY_IMPORT_CALL_STRIDE;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf3(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_AARCH64_CTRL_RISCV_CALL_COMPACT_F32_U32;
  regs.ebx = POLY_RISCV_CTRL_AARCH64_CALL_COMPACT_F32_U32;
  regs.ecx = POLY_AARCH64_CTRL_RISCV_CALL_FP64_STACK;
  regs.edx = POLY_RISCV_CTRL_AARCH64_CALL_FP64_STACK;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf4(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_AARCH64_CTRL_TRAP_RETURN;
  regs.ebx = POLY_RISCV_CTRL_TRAP_RETURN;
  regs.ecx = POLY_AARCH64_CTRL_RISCV_CALL_VEC128_U32;
  regs.edx = POLY_RISCV_CTRL_AARCH64_CALL_VEC128_U32;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf5(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_IMPORT_FUNC_COUNT;
  regs.ebx = (uint32_t) POLY_IMPORT_CALL_BASE;
  regs.ecx = (uint32_t) (POLY_IMPORT_CALL_BASE >> 32);
  regs.edx = POLY_IMPORT_CALL_STRIDE;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf6(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_AARCH64_CTRL_SWITCH_MODE;
  regs.ebx = POLY_RISCV_CTRL_SWITCH_MODE;
  regs.ecx = POLY_AARCH64_CTRL_CALL_MODE;
  regs.edx = POLY_RISCV_CTRL_CALL_MODE;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf7(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_X86_CTRL_PCALL_SIG_IMM_MODE;
  regs.ebx = POLY_ABI_SIGNATURE_SLOT_COUNT;
  regs.ecx = POLY_ABI_SIGNATURE_SLOT_EXCHANGE |
    (POLY_ABI_SIGNATURE_SLOT_X86_SYSV_REGS << 8) |
    (POLY_ABI_SIGNATURE_SLOT_X86_SYSV_REGS_I128 << 16);
  regs.edx = POLY_ABI_SIGNATURE_KIND_EXCHANGE |
    (POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS << 8) |
    (POLY_ABI_SIGNATURE_KIND_X86_SYSV_REGS_I128 << 16);
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf8(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_AARCH64_CTRL_CALL_SIG_MODE;
  regs.ebx = POLY_RISCV_CTRL_CALL_SIG_MODE;
  regs.ecx = POLY_ABI_SIGNATURE_SLOT_COUNT;
  regs.edx = 0;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf9(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_X86_CTRL_LANDING;
  regs.ebx = POLY_AARCH64_CTRL_LANDING;
  regs.ecx = POLY_RISCV_CTRL_LANDING;
  regs.edx = 0;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf10(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_AARCH64_CTRL_ABI_SIGNATURE_SET;
  regs.ebx = POLY_AARCH64_CTRL_ABI_SIGNATURE_GET;
  regs.ecx = POLY_RISCV_CTRL_ABI_SIGNATURE_SET;
  regs.edx = POLY_RISCV_CTRL_ABI_SIGNATURE_GET;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_escape_leaf11(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_AARCH64_CTRL_CALL_SIG_IMM(0);
  regs.ebx = POLY_RISCV_CTRL_CALL_SIG_IMM(0);
  regs.ecx = POLY_ABI_SIGNATURE_SLOT_COUNT;
  regs.edx = 0;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_state_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_CPUID_STATE_OVERLAP_GPRS |
    POLY_CPUID_STATE_SYNTHETIC_BANKS |
    POLY_CPUID_STATE_KEY_CR3 |
    POLY_CPUID_STATE_KEY_FSBASE |
    POLY_CPUID_STATE_KEY_STACK_REGION |
    POLY_CPUID_STATE_USER_RETURN_RESTORE |
    POLY_CPUID_STATE_X86_TSO |
    POLY_CPUID_STATE_XSAVE_VISIBLE |
    POLY_CPUID_STATE_KEY_EXPLICIT |
    POLY_CPUID_STATE_TRANSITION_FRAME_32 |
    POLY_CPUID_STATE_EXPLICIT_SAVE_RESTORE |
    POLY_CPUID_STATE_XSAVE_ARCH_CONTRACT |
    POLY_CPUID_STATE_IMPORT_RETURN_XSAVE |
    POLY_CPUID_STATE_ABI_SIGNATURE_XSAVE |
    POLY_CPUID_STATE_MONITOR_PACKET_XSAVE;
  regs.ebx = POLY_STATE_STACK_KEY_SHIFT;
  regs.ecx = POLY_STATE_XSAVE_COMPONENT_ARCH;
  regs.edx = POLY_STATE_XSAVE_BYTES_ARCH;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_arch_state_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_STATE_XSAVE_COMPONENT_ARCH;
  regs.ebx = (uint32_t) sizeof(struct poly_xsave_state);
  regs.ecx = POLY_STATE_XSAVE_LAYOUT_VERSION |
    (POLY_STATE_XSAVE_ALIGN_ARCH << 16);
  regs.edx = POLY_STATE_XSAVE_FLAG_XCR0_USER |
    POLY_STATE_XSAVE_FLAG_OSXSAVE_REQUIRED |
    POLY_STATE_XSAVE_FLAG_INTERRUPT_RESUME |
    POLY_STATE_XSAVE_FLAG_TRAP_STATE |
    POLY_STATE_XSAVE_FLAG_NO_HIDDEN_BANKS |
    POLY_STATE_XSAVE_FLAG_IMPORT_RETURN |
    POLY_STATE_XSAVE_FLAG_ABI_SIGNATURES |
    POLY_STATE_XSAVE_FLAG_MONITOR_PACKET;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_trap_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_TRAP_PACKET_LAYOUT_VERSION;
  regs.ebx = (uint32_t) sizeof(struct poly_trap_packet);
  regs.ecx = (uint32_t) (sizeof(((struct poly_xsave_state *) 0)->trap_args) /
    sizeof(((struct poly_xsave_state *) 0)->trap_args[0]));
  regs.edx = POLY_TRAP_PACKET_FLAG_VECTOR_DELIVERY |
    POLY_TRAP_PACKET_FLAG_NO_VECTOR_X86_EXCEPTIONS |
    POLY_TRAP_PACKET_FLAG_TRAP_RETURN_RESTORE |
    POLY_TRAP_PACKET_FLAG_ALL_FRONTEND_HANDLERS |
    POLY_TRAP_PACKET_FLAG_STATUS_OPS |
    POLY_TRAP_PACKET_FLAG_MONITOR_MEMORY;
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_interrupt_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_INTERRUPT_ABI_VERSION;
  regs.ebx = POLY_INTERRUPT_FLAG_RAW_CPL3_ONLY |
    POLY_INTERRUPT_FLAG_STANDARD_X86_ENTRY |
    POLY_INTERRUPT_FLAG_STATE_COMPONENT_SAVE |
    POLY_INTERRUPT_FLAG_PRECISE_FOREIGN_PC |
    POLY_INTERRUPT_FLAG_EVENT_CHECK_BETWEEN_INSNS;
  regs.ecx = POLY_INTERRUPT_RETURN_IRET64 |
    POLY_INTERRUPT_RETURN_SYSRET |
    POLY_INTERRUPT_RETURN_SYSEXIT |
    POLY_INTERRUPT_RETURN_SIGNAL;
  regs.edx = (1U << POLY_MODE_RAW_AARCH64) |
    (1U << POLY_MODE_RAW_RISCV);
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_memory_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_MEMORY_ABI_VERSION;
  regs.ebx = POLY_MEMORY_MODEL_X86_TSO;
  regs.ecx = POLY_MEMORY_FLAG_SHARED_X86_MEMORY |
    POLY_MEMORY_FLAG_AARCH64_BARRIERS_NOOP |
    POLY_MEMORY_FLAG_RISCV_FENCES_NOOP |
    POLY_MEMORY_FLAG_ATOMICS_COHERENT |
    POLY_MEMORY_FLAG_NO_WEAK_REORDERING;
  regs.edx = (1U << POLY_MODE_RAW_AARCH64) |
    (1U << POLY_MODE_RAW_RISCV);
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_transition_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_TRANSITION_ABI_VERSION;
  regs.ebx = POLY_TRANSITION_FLAG_DECODED_X86_OPCODES |
    POLY_TRANSITION_FLAG_NATIVE_RAW_ESCAPES |
    POLY_TRANSITION_FLAG_PIPELINE_FLUSH |
    POLY_TRANSITION_FLAG_BLOCK_BOUNDARY |
    POLY_TRANSITION_FLAG_PRECISE_NEXT_PC |
    POLY_TRANSITION_FLAG_FIXED_RAW_WIDTH |
    POLY_TRANSITION_FLAG_NEUTRAL_FOREIGN |
    POLY_TRANSITION_FLAG_NATIVE_RETURN_COOKIE |
    POLY_TRANSITION_FLAG_TRAP_RETURN |
    POLY_TRANSITION_FLAG_INTERRUPTED_RAW |
    POLY_TRANSITION_FLAG_LANDING_PADS;
  regs.ecx = POLY_TRANSITION_AARCH64_ALIGN |
    (POLY_TRANSITION_RISCV_ALIGN << 16);
  regs.edx = poly_cpuid_expected_mode_mask();
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_frontend_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_FRONTEND_X86;
  regs.ebx = POLY_FRONTEND_AARCH64;
  regs.ecx = POLY_FRONTEND_RISCV;
  regs.edx = poly_cpuid_expected_frontend_mask();
  return regs;
}

static inline struct poly_cpuid_regs poly_cpuid_expected_abi_bridge_leaf(void) {
  struct poly_cpuid_regs regs;
  regs.eax = POLY_ABI_BRIDGE_ABI_VERSION;
  regs.ebx = POLY_ABI_BRIDGE_FLAG_X86_SYSV_TO_AAPCS64 |
    POLY_ABI_BRIDGE_FLAG_X86_SYSV_TO_RISCV |
    POLY_ABI_BRIDGE_FLAG_SRET |
    POLY_ABI_BRIDGE_FLAG_SCALAR_FP |
    POLY_ABI_BRIDGE_FLAG_FOCUSED_AGGREGATES |
    POLY_ABI_BRIDGE_FLAG_FP64_STACK |
    POLY_ABI_BRIDGE_FLAG_TLS_BASE |
    POLY_ABI_BRIDGE_FLAG_USER_DESCRIPTORS |
    POLY_ABI_BRIDGE_FLAG_NO_CPU_HELPER_FALLBACK |
    POLY_ABI_BRIDGE_FLAG_ORDINARY_X86_RET |
    POLY_ABI_BRIDGE_FLAG_VEC128 |
    POLY_ABI_BRIDGE_FLAG_REGISTER_SIGNATURES;
  regs.ecx = POLY_ABI_BRIDGE_GPR_ARG_COUNT |
    (POLY_ABI_BRIDGE_FP_ARG_COUNT << 8) |
    (POLY_ABI_BRIDGE_STACK_ALIGN << 16);
  regs.edx = POLY_IMPORT_X86_DESCRIPTOR_SIZE |
    (POLY_IMPORT_CALL_STRIDE << 16);
  return regs;
}

static inline void poly_cpuid_vendor_string(const struct poly_cpuid_regs *regs,
    char vendor[13]) {
  memcpy(vendor, &regs->ebx, 4);
  memcpy(vendor + 4, &regs->edx, 4);
  memcpy(vendor + 8, &regs->ecx, 4);
  vendor[12] = '\0';
}

static inline int poly_cpuid_vendor_matches(const struct poly_cpuid_regs *regs) {
  char vendor[13];
  poly_cpuid_vendor_string(regs, vendor);
  return strcmp(vendor, "PolyglotCPU!") == 0;
}

static inline int poly_cpuid_present(void) {
  struct poly_cpuid_regs regs = poly_read_cpuid(POLY_CPUID_BASE, 0);
  return regs.eax >= POLY_CPUID_MAX && poly_cpuid_vendor_matches(&regs);
}

#endif
