#ifndef POLY_PROCESS_BRIDGE_KIND_H
#define POLY_PROCESS_BRIDGE_KIND_H

enum poly_process_bridge_kind {
  POLY_PROCESS_BRIDGE_DEFAULT = 0,
  POLY_PROCESS_BRIDGE_VEC128_U32 = 1,
  POLY_PROCESS_BRIDGE_COMPACT_U32_F32 = 2,
  POLY_PROCESS_BRIDGE_COMPACT_F32_U32 = 3,
  POLY_PROCESS_BRIDGE_U64_STACK9 = 4,
  POLY_PROCESS_BRIDGE_FP64 = 5,
  POLY_PROCESS_BRIDGE_FP32 = 6,
  POLY_PROCESS_BRIDGE_AARCH64_HFA3_F32_RET = 7,
  POLY_PROCESS_BRIDGE_AARCH64_HFA4_F32_RET = 8,
  POLY_PROCESS_BRIDGE_FPAIR32_ARG = 9,
  POLY_PROCESS_BRIDGE_FPAIR64_ARG = 10,
  POLY_PROCESS_BRIDGE_FPAIR32_RET = 11,
  POLY_PROCESS_BRIDGE_FPAIR64_RET = 12,
  POLY_PROCESS_BRIDGE_AARCH64_HFA3_F32_ARG = 13,
  POLY_PROCESS_BRIDGE_AARCH64_HFA4_F32_ARG = 14,
  POLY_PROCESS_BRIDGE_SRET_X86_SYSV = 15,
  POLY_PROCESS_BRIDGE_NATIVE_SRET = 16,
  POLY_PROCESS_BRIDGE_AARCH64_HFA3_F64_RET = 17,
  POLY_PROCESS_BRIDGE_AARCH64_HFA4_F64_RET = 18,
  POLY_PROCESS_BRIDGE_AARCH64_HFA3_F64_ARG = 19,
  POLY_PROCESS_BRIDGE_AARCH64_HFA4_F64_ARG = 20
};

#define POLY_PROCESS_BRIDGE_KIND_COUNT 21

#endif
