#!/bin/busybox sh
set -eu

path="${1:-}"
if [ -z "$path" ]; then
  echo "POLYBINFMT_FAIL: missing foreign ELF path" >&2
  exit 2
fi
shift

expected=""
entry=""
runner="polyexec"
call_prefix=""
process_mode=0

set_polycall() {
  expected="$1"
  entry="${2:-#poly_entry}"
  runner="polycall"
  call_prefix="${3:-}"
}

case "$path" in
  */aarch64-add.elf) expected=132 ;;
  */aarch64-regadd.elf) expected=123 ;;
  */aarch64-movwide.elf) expected=0xffff6543edcb5678 ;;
  */aarch64-mul.elf) expected=42 ;;
  */aarch64-logical.elf) expected=60 ;;
  */aarch64-shifted.elf) expected=123 ;;
  */aarch64-regmix.elf) expected=12 ;;
  */aarch64-branch.elf) expected=42 ;;
  */aarch64-condbranch.elf) expected=91 ;;
  */aarch64-loop.elf) expected=0 ;;
  */aarch64-ret.elf) expected=55 ;;
  */aarch64-mem.elf) expected=77 ;;
  */aarch64-memwidth.elf) expected=0x100001324 ;;
  */aarch64-pair-frame.elf) expected=35 ;;
  */aarch64-hints.elf) expected=27 ;;
  */aarch64-prfm.elf) expected=27 ;;
  */aarch64-pcall-split-load.elf) expected=123 ;;
  */aarch64-process-argv-envp-real.elf) expected=42; process_mode=1 ;;
  */aarch64-process-syscall-real.elf) expected=42; process_mode=1 ;;
  */aarch64-process-reloc-real.elf) expected=42; process_mode=1 ;;
  */aarch64-polyexec-gnu-hash-real.so) expected=45; entry="#poly_entry" ;;
  */aarch64-pcall-dynrel.elf) expected=123; entry="#poly_entry" ;;
  */aarch64-pcall-rel.elf) expected=123; entry="#poly_entry" ;;
  */aarch64-pcall-relr.elf) expected=123; entry="#poly_entry" ;;
  */aarch64-pcall-relr-bitmap.elf) expected=123; entry="#poly_entry" ;;
  */aarch64-pcall-irelative.elf) expected=123; entry="#poly_entry" ;;
  */aarch64-pcall-jumprel.elf) expected=123 ;;
  */aarch64-pcall-rel-jumprel.elf) expected=123 ;;
  */aarch64-strlen.elf) expected=0x4c000301 ;;
  */aarch64-memfill.elf) expected=0x4c000302 ;;
  */aarch64-memcmp.elf) expected=0x4c000303 ;;
  */aarch64-memcpy.elf) expected=0x4c000304 ;;
  */aarch64-eventfd2.elf) expected=0 ;;
  */aarch64-inotify-init1.elf) expected=0 ;;
  */aarch64-inotify-add-watch.elf) expected=1 ;;
  */aarch64-inotify-rm-watch.elf) expected=0 ;;
  */aarch64-dup3.elf) expected=8 ;;
  */aarch64-read.elf) expected=4 ;;
  */aarch64-write.elf) expected=5 ;;
  */aarch64-openat.elf) expected=3 ;;
  */aarch64-openat-lseek.elf) expected=7 ;;
  */aarch64-openat-read.elf) expected=4 ;;
  */aarch64-openat-read-close.elf) expected=0 ;;
  */aarch64-real-openat-read-close.elf) expected=0 ;;
  */aarch64-real-newfstatat.elf) expected=0 ;;
  */aarch64-real-fstat0.elf) expected=0 ;;
  */aarch64-real-statx.elf) expected=0 ;;
  */aarch64-clock-gettime.elf) expected=0 ;;
  */aarch64-real-clock-getres.elf) expected=0 ;;
  */aarch64-real-gettimeofday.elf) expected=0 ;;
  */aarch64-getpgid.elf) expected=pgid ;;
  */aarch64-getsid.elf) expected=sid ;;
  */aarch64-getrlimit.elf) expected=stackrlim ;;
  */aarch64-getrusage.elf) expected=321 ;;
  */aarch64-getcpu.elf) expected=12 ;;
  */aarch64-gettimeofday.elf) expected=246 ;;
  */aarch64-sysinfo.elf) expected=98765 ;;
  */aarch64-mmap.elf) expected=0 ;;
  */aarch64-mmap6.elf) expected=65 ;;
  */aarch64-mmap-store.elf) expected=77 ;;
  */aarch64-mmap-real-store.elf) expected=77 ;;
  */aarch64-real-mprotect.elf) expected=0 ;;
  */aarch64-real-munmap.elf) expected=0 ;;
  */aarch64-real-write-zero.elf) expected=0 ;;
  */aarch64-getpid.elf) expected=4242 ;;
  */aarch64-getppid.elf) expected=4241 ;;
  */aarch64-getuid.elf) expected=1000 ;;
  */aarch64-geteuid.elf) expected=1000 ;;
  */aarch64-getgid.elf) expected=1000 ;;
  */aarch64-getegid.elf) expected=1000 ;;
  */aarch64-gettid.elf) expected=4243 ;;
  */aarch64-getcwd.elf) expected=6 ;;
  */aarch64-fp-int-move.elf) expected=0x41400000 ;;
  */aarch64-fp32-to-int.elf) expected=12 ;;
  */aarch64-fp32-to-int64.elf) expected=12 ;;
  */aarch64-uname.elf) expected=0 ;;
  */aarch64-exit.elf) expected=7 ;;
  */aarch64-brk.elf) expected=0x4c000305 ;;
  */aarch64-svc.elf) expected=0xffffffffffffffda ;;
  */aarch64-pcall-needed-real.so) expected=397; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-lib-needed-real.so) expected=945; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-many-needed-real.so) expected=4545; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-needed-tls-real.so) expected=545; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-needed-ifunc-real.so) expected=845; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-needed-dt-init-real.so) expected=945; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-libc-import-real.so) expected=201721; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-qsort-real.so) set_polycall 128 ;;
  */aarch64-pcall-bsearch-real.so) set_polycall 136 ;;
  */aarch64-pcall-qsort-r-real.so) set_polycall 194 ;;
  */aarch64-pcall-pthread-once-real.so) set_polycall 77 ;;
  */aarch64-pcall-pthread-key-real.so) set_polycall 91 ;;
  */aarch64-pcall-pthread-mutex-real.so) set_polycall 98 ;;
  */aarch64-pcall-pthread-self-real.so) set_polycall 109 ;;
  */aarch64-pcall-pthread-rwlock-real.so) set_polycall 123 ;;
  */aarch64-pcall-pthread-mutexattr-real.so) set_polycall 132 ;;
  */aarch64-pcall-pthread-spin-real.so) set_polycall 141 ;;
  */aarch64-pcall-pthread-cond-real.so) set_polycall 152 ;;
  */aarch64-pcall-time-real.so) set_polycall 176 ;;
  */aarch64-pcall-stack-protector-real.so) expected=49; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-getauxval-real.so) expected=45; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-errno-real.so) expected=29; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-env-real.so) expected=53; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-alloc-real.so) expected=90; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-snprintf-real.so) expected=706; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-integer-parse-real.so) expected=1508; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-ctype-real.so) expected=1540; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-abs-real.so) expected=1524; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-atol-real.so) expected=1532; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-ffs-real.so) expected=1564; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-strtod-real.so) expected=1376; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-strtof-real.so) expected=1384; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-fabsf-real.so) expected=1396; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-fabs-real.so) expected=1404; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-sqrtf-real.so) expected=1420; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-sqrt-real.so) expected=1412; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-rounding-real.so) expected=1496; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-string-search-real.so) expected=1468; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-strdup-real.so) expected=911; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-atexit-real.so) expected=1122; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cxa-guard-real.so) expected=101; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cxx-static-guard-real.so) expected=113; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cxx-virtual-real.so) expected=246; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-fp64-real.so) expected=0x4026800000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fp64:" ;;
  */aarch64-pcall-fp64-stack-real.so) expected=0x4061100000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fp64stack:" ;;
  */aarch64-pcall-fpair-real.so) expected=0x40268000400b0000; entry="#poly_entry"; runner="polycall"; call_prefix="fpair:" ;;
  */aarch64-pcall-fpair32-real.so) expected=0x40d8000040700000; entry="#poly_entry"; runner="polycall"; call_prefix="fpair32:" ;;
  */aarch64-pcall-fpair-arg-real.so) expected=0x4026800000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fpairarg:" ;;
  */aarch64-pcall-fpair32-arg-real.so) expected=0x41340000; entry="#poly_entry"; runner="polycall"; call_prefix="fpair32arg:" ;;
  */aarch64-pcall-hfa3-real.so) expected=0x0000400e40154016; entry="#poly_entry"; runner="polycall"; call_prefix="hfa3f64:" ;;
  */aarch64-pcall-hfa4-real.so) expected=0x400e401540164021; entry="#poly_entry"; runner="polycall"; call_prefix="hfa4f64:" ;;
  */aarch64-pcall-hfa3-f32-real.so) expected=0x0000407040a840b0; entry="#poly_entry"; runner="polycall"; call_prefix="hfa3f32:" ;;
  */aarch64-pcall-hfa4-f32-real.so) expected=0x407040a840b0410c; entry="#poly_entry"; runner="polycall"; call_prefix="hfa4f32:" ;;
  */aarch64-pcall-hfa-arg-real.so) expected=0x00003ff840024008; entry="#poly_hfa3_f64_arg"; runner="polycall"; call_prefix="hfa3f64arg:" ;;
  */aarch64-pcall-vec128-real.so) expected=0x002c00210016000b; entry="#poly_entry"; runner="polycall"; call_prefix="vec128u32:" ;;
  */aarch64-pcall-mixed-args-real.so) expected=0x40a9320000000000; entry="#poly_entry"; runner="polycall"; call_prefix="mixedargs:" ;;
  */aarch64-pcall-hetero-real.so) expected=0x0008401d00000000; entry="#poly_entry"; runner="polycall"; call_prefix="hetero:" ;;
  */aarch64-pcall-hetero-rev-real.so) expected=0x0008401d00000000; entry="#poly_entry"; runner="polycall"; call_prefix="heterorev:" ;;
  */aarch64-pcall-hetero32-real.so) expected=0x0000000840e80000; entry="#poly_entry"; runner="polycall"; call_prefix="heterof32:" ;;
  */aarch64-pcall-hetero32-rev-real.so) expected=0x0000000840e80000; entry="#poly_entry"; runner="polycall"; call_prefix="heterof32rev:" ;;
  */aarch64-pcall-hetero-u32-real.so) expected=0x0008401d00000000; entry="#poly_entry"; runner="polycall"; call_prefix="heterou32:" ;;
  */aarch64-pcall-hetero-u32-rev-real.so) expected=0x0008401d00000000; entry="#poly_entry"; runner="polycall"; call_prefix="heterou32rev:" ;;
  */aarch64-pcall-hetero-u32-f32-real.so) expected=0x40e8000000000008; entry="#poly_entry"; runner="polycall"; call_prefix="heterou32f32:" ;;
  */aarch64-pcall-hetero-f32-u32-real.so) expected=0x0000000840e80000; entry="#poly_entry"; runner="polycall"; call_prefix="heterof32u32:" ;;
  */aarch64-pcall-cross-needed-real.so) expected=536; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cross-needed-transitive-real.so) expected=1770; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cross-compact-real.so) expected=0x426d00d642020070; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cross-ifunc-compact-real.so) expected=0x431f020242a50138; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cross-ifunc-fp64-stack-real.so) expected=0x4061100000000000; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cross-ifunc-vec128-real.so) expected=0x01bc014d00de006f; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cross-fp64-stack-real.so) expected=0x4061100000000000; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cross-vec128-real.so) expected=0x01bc014d00de006f; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cross-root-compact-real.so) expected=0x415c019d41b0013d; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cross-root-ifunc-compact-real.so) expected=0x4355026d42d7019f; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cross-root-ifunc-fp64-stack-real.so) expected=0x4061100000000000; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cross-root-ifunc-vec128-real.so) expected=0x01bc014d00de006f; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cross-root-fp64-stack-real.so) expected=0x4061100000000000; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cross-root-vec128-real.so) expected=0x01bc014d00de006f; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cross-root-tls-real.so) expected=2348; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cross-root-ifunc-real.so) expected=2045; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-cross-needed-tls-external-real.so) expected=1045; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-x86-sret-import-real.so) expected=0x000b00160021002e; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-x86-sret-stack-import-real.so) expected=0x000b001600210042; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-x86-sret-callee-stack-import-real.so) expected=7356; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-x86-sum8-import-real.so) expected=236; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-x86-sum10-import-real.so) expected=255; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-x86-sum14-import-real.so) expected=305; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-x86-align14-import-real.so) expected=305; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-x86-i128-import-real.so) expected=0x22421121; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-x86-i128-callee-import-real.so) expected=7201; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-x86-callee-import-real.so) expected=7386; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-x86-callee-stack-import-real.so) expected=7455; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-x86-sum8-post-import-real.so) expected=245; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-x86-fp64-import-real.so) expected=0x4069e80000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fp64:" ;;
  */aarch64-pcall-x86-fp64-sum8-import-real.so) expected=0x406da80000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fp64:" ;;
  */aarch64-pcall-x86-fp64-sum10-import-real.so) expected=0x4070040000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fp64:" ;;
  */aarch64-pcall-x86-fp64-callee-import-real.so) expected=0x40993e0000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fp64:" ;;
  */aarch64-pcall-x86-fp64-callee-stack-import-real.so) expected=0x409a0e0000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fp64:" ;;
  */aarch64-pcall-x86-fpair64-import-real.so) expected=0x405ad0004069e800; entry="#poly_entry"; runner="polycall"; call_prefix="fpair:" ;;
  */aarch64-pcall-x86-fpair64-fp64-callee-import-real.so) expected=0x409ae50000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fp64:" ;;
  */aarch64-pcall-x86-fpair32-import-real.so) expected=0x41da0000418a0000; entry="#poly_entry"; runner="polycall"; call_prefix="fpair32:" ;;
  */aarch64-pcall-x86-fpair32-fp32-callee-import-real.so) expected=0x44b56800; entry="#poly_entry"; runner="polycall"; call_prefix="fp32:" ;;
  */aarch64-pcall-x86-vec128-import-real.so) expected=0x01e4016b00f20079; entry="#poly_entry"; runner="polycall"; call_prefix="vec128u32:" ;;
  */aarch64-pcall-x86-vec128-fp64-callee-import-real.so) expected=0x0208018f0116009d; entry="#poly_entry"; runner="polycall"; call_prefix="vec128u32:" ;;
  */aarch64-pcall-x86-sret-stack10-import-real.so) expected=0x000b00160021008c; entry="#poly_entry"; runner="polycall"; call_prefix="sret10:" ;;
  */aarch64-pcall-x86-sret-fp64-callee-stack-import-real.so) expected=0x4099450000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fp64:" ;;
  */aarch64-pcall-x86-mixed-u64-fp64-import-real.so) expected=0x406aa80000000000; entry="#poly_entry"; runner="polycall"; call_prefix="mixedargs:" ;;
  */aarch64-pcall-x86-mixed-u64-fp64-callee-import-real.so) expected=0x40b2f1c000000000; entry="#poly_entry"; runner="polycall"; call_prefix="mixedargs:" ;;
  */aarch64-pcall-x86-mixed-u64-fp64-stack-import-real.so) expected=0x40788c0000000000; entry="#poly_entry"; runner="polycall"; call_prefix="mixedstack:" ;;
  */aarch64-pcall-x86-fp32-import-real.so) expected=0x434f4000; entry="#poly_entry"; runner="polycall"; call_prefix="fp32:" ;;
  */aarch64-pcall-abs-runpath-real.so) expected=945; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-rpath-real.so) expected=945; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-rpath-inherit-real.so) expected=745; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-colon-runpath-real.so) expected=945; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-lib-runpath-real.so) expected=945; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-platform-runpath-real.so) expected=945; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-runpath-prefer-real.so) expected=945; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-needed-relro-real.so) expected=745; entry="#poly_entry"; runner="polycall" ;;
  */aarch64-pcall-relro-real.so) expected=745; entry="#poly_entry"; runner="polycall" ;;
  */riscv-add.elf) expected=27 ;;
  */riscv-compressed.elf) expected=27 ;;
  */riscv-compressed-half.elf) expected=27 ;;
  */riscv-compressed-jalr.elf) expected=27 ;;
  */riscv-compressed-word.elf) expected=27 ;;
  */riscv-compressed-alu.elf) expected=42 ;;
  */riscv-compressed-fp.elf) expected=64 ;;
  */riscv-compressed-sdsp.elf) expected=27 ;;
  */riscv-compressed-hints.elf) expected=27 ;;
  */riscv-fp-int-move.elf) expected=0xffffffff8000002a ;;
  */riscv-fp-class.elf) expected=32 ;;
  */riscv-fp32-to-int.elf) expected=12 ;;
  */riscv-upper.elf) expected=0x1234567c ;;
  */riscv-immops.elf) expected=42 ;;
  */riscv-wordops.elf) expected=42 ;;
  */riscv-shiftcmp.elf) expected=31 ;;
  */riscv-divrem.elf) expected=16 ;;
  */riscv-shifts.elf) expected=32 ;;
  */riscv-srai.elf) expected=0xfffffffffffffffc ;;
  */riscv-regadd.elf) expected=123 ;;
  */riscv-mul.elf) expected=42 ;;
  */riscv-logical.elf) expected=60 ;;
  */riscv-regmix.elf) expected=12 ;;
  */riscv-branch.elf) expected=42 ;;
  */riscv-jal.elf) expected=9 ;;
  */riscv-jalr.elf) expected=5 ;;
  */riscv-branchcmp.elf) expected=127 ;;
  */riscv-condbranch.elf) expected=91 ;;
  */riscv-loop.elf) expected=0 ;;
  */riscv-ret.elf) expected=55 ;;
  */riscv-mem.elf) expected=77 ;;
  */riscv-memwidth.elf) expected=0x1000000e0 ;;
  */riscv-pair-frame.elf) expected=35 ;;
  */riscv-pcall-split-load.elf) expected=123 ;;
  */riscv-process-argv-envp-real.elf) expected=42; process_mode=1 ;;
  */riscv-process-syscall-real.elf) expected=42; process_mode=1 ;;
  */riscv-process-reloc-real.elf) expected=42; process_mode=1 ;;
  */riscv-polyexec-gnu-hash-real.so) expected=45; entry="#poly_entry" ;;
  */riscv-polyexec-gnu-hash-rv64gc.so) expected=45; entry="#poly_entry" ;;
  */riscv-pcall-dynrel.elf) expected=123; entry="#poly_entry" ;;
  */riscv-pcall-rel.elf) expected=123; entry="#poly_entry" ;;
  */riscv-pcall-relr.elf) expected=123; entry="#poly_entry" ;;
  */riscv-pcall-relr-bitmap.elf) expected=123; entry="#poly_entry" ;;
  */riscv-pcall-irelative.elf) expected=123; entry="#poly_entry" ;;
  */riscv-pcall-jumprel.elf) expected=123 ;;
  */riscv-pcall-rel-jumprel.elf) expected=123 ;;
  */riscv-strlen.elf) expected=0x4c000401 ;;
  */riscv-memfill.elf) expected=0x4c000402 ;;
  */riscv-memcmp.elf) expected=0x4c000403 ;;
  */riscv-memcpy.elf) expected=0x4c000404 ;;
  */riscv-eventfd2.elf) expected=0 ;;
  */riscv-inotify-init1.elf) expected=0 ;;
  */riscv-inotify-add-watch.elf) expected=1 ;;
  */riscv-inotify-rm-watch.elf) expected=0 ;;
  */riscv-dup3.elf) expected=8 ;;
  */riscv-read.elf) expected=4 ;;
  */riscv-write.elf) expected=5 ;;
  */riscv-openat.elf) expected=3 ;;
  */riscv-openat-lseek.elf) expected=7 ;;
  */riscv-openat-read.elf) expected=4 ;;
  */riscv-openat-read-close.elf) expected=0 ;;
  */riscv-real-openat-read-close.elf) expected=0 ;;
  */riscv-real-newfstatat.elf) expected=0 ;;
  */riscv-real-fstat0.elf) expected=0 ;;
  */riscv-real-statx.elf) expected=0 ;;
  */riscv-clock-gettime.elf) expected=0 ;;
  */riscv-real-clock-getres.elf) expected=0 ;;
  */riscv-real-gettimeofday.elf) expected=0 ;;
  */riscv-getpgid.elf) expected=pgid ;;
  */riscv-getsid.elf) expected=sid ;;
  */riscv-getrlimit.elf) expected=stackrlim ;;
  */riscv-getrusage.elf) expected=321 ;;
  */riscv-getcpu.elf) expected=12 ;;
  */riscv-gettimeofday.elf) expected=246 ;;
  */riscv-sysinfo.elf) expected=98765 ;;
  */riscv-mmap.elf) expected=0 ;;
  */riscv-mmap6.elf) expected=65 ;;
  */riscv-mmap-store.elf) expected=77 ;;
  */riscv-mmap-real-store.elf) expected=77 ;;
  */riscv-real-mprotect.elf) expected=0 ;;
  */riscv-real-munmap.elf) expected=0 ;;
  */riscv-real-write-zero.elf) expected=0 ;;
  */riscv-getpid.elf) expected=4242 ;;
  */riscv-getppid.elf) expected=4241 ;;
  */riscv-getuid.elf) expected=1000 ;;
  */riscv-geteuid.elf) expected=1000 ;;
  */riscv-getgid.elf) expected=1000 ;;
  */riscv-getegid.elf) expected=1000 ;;
  */riscv-gettid.elf) expected=4243 ;;
  */riscv-getcwd.elf) expected=6 ;;
  */riscv-uname.elf) expected=0 ;;
  */riscv-exit.elf) expected=7 ;;
  */riscv-ebreak.elf) expected=0x4c000405 ;;
  */riscv-compressed-ebreak.elf) expected=0x4c000405 ;;
  */riscv-ecall.elf) expected=0xffffffffffffffda ;;
  */riscv-pcall-needed-real.so) expected=397; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-lib-needed-real.so) expected=945; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-many-needed-real.so) expected=4545; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-needed-tls-real.so) expected=545; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-needed-ifunc-real.so) expected=845; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-needed-dt-init-real.so) expected=945; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-libc-import-real.so) expected=201721; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-qsort-real.so) set_polycall 128 ;;
  */riscv-pcall-bsearch-real.so) set_polycall 136 ;;
  */riscv-pcall-qsort-r-real.so) set_polycall 194 ;;
  */riscv-pcall-pthread-once-real.so) set_polycall 77 ;;
  */riscv-pcall-pthread-key-real.so) set_polycall 91 ;;
  */riscv-pcall-pthread-mutex-real.so) set_polycall 98 ;;
  */riscv-pcall-pthread-self-real.so) set_polycall 109 ;;
  */riscv-pcall-pthread-rwlock-real.so) set_polycall 123 ;;
  */riscv-pcall-pthread-mutexattr-real.so) set_polycall 132 ;;
  */riscv-pcall-pthread-spin-real.so) set_polycall 141 ;;
  */riscv-pcall-pthread-cond-real.so) set_polycall 152 ;;
  */riscv-pcall-time-real.so) set_polycall 176 ;;
  */riscv-pcall-stack-protector-real.so) expected=49; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-getauxval-real.so) expected=45; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-errno-real.so) expected=29; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-env-real.so) expected=53; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-alloc-real.so) expected=90; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-snprintf-real.so) expected=706; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-integer-parse-real.so) expected=1508; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-ctype-real.so) expected=1540; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-abs-real.so) expected=1524; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-atol-real.so) expected=1532; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-ffs-real.so) expected=1564; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-strtod-real.so) expected=1376; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-strtof-real.so) expected=1384; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-fabsf-real.so) expected=1396; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-fabs-real.so) expected=1404; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-sqrtf-real.so) expected=1420; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-sqrt-real.so) expected=1412; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-rounding-real.so) expected=1496; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-string-search-real.so) expected=1468; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-strdup-real.so) expected=911; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-atexit-real.so) expected=1122; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cxa-guard-real.so) expected=101; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cxx-static-guard-real.so) expected=113; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cxx-virtual-real.so) expected=246; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-fp64-real.so) expected=0x4026800000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fp64:" ;;
  */riscv-pcall-fp64-stack-real.so) expected=0x4061100000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fp64stack:" ;;
  */riscv-pcall-fpair-real.so) expected=0x40268000400b0000; entry="#poly_entry"; runner="polycall"; call_prefix="fpair:" ;;
  */riscv-pcall-fpair32-real.so) expected=0x40d8000040700000; entry="#poly_entry"; runner="polycall"; call_prefix="fpair32:" ;;
  */riscv-pcall-fpair-arg-real.so) expected=0x4026800000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fpairarg:" ;;
  */riscv-pcall-fpair32-arg-real.so) expected=0x41340000; entry="#poly_entry"; runner="polycall"; call_prefix="fpair32arg:" ;;
  */riscv-pcall-mixed-args-real.so) expected=0x40a9320000000000; entry="#poly_entry"; runner="polycall"; call_prefix="mixedargs:" ;;
  */riscv-pcall-hetero-real.so) expected=0x0008401d00000000; entry="#poly_entry"; runner="polycall"; call_prefix="hetero:" ;;
  */riscv-pcall-hetero-rev-real.so) expected=0x0008401d00000000; entry="#poly_entry"; runner="polycall"; call_prefix="heterorev:" ;;
  */riscv-pcall-hetero32-real.so) expected=0x0000000840e80000; entry="#poly_entry"; runner="polycall"; call_prefix="heterof32:" ;;
  */riscv-pcall-hetero32-rev-real.so) expected=0x0000000840e80000; entry="#poly_entry"; runner="polycall"; call_prefix="heterof32rev:" ;;
  */riscv-pcall-hetero-u32-real.so) expected=0x0008401d00000000; entry="#poly_entry"; runner="polycall"; call_prefix="heterou32:" ;;
  */riscv-pcall-hetero-u32-rev-real.so) expected=0x0008401d00000000; entry="#poly_entry"; runner="polycall"; call_prefix="heterou32rev:" ;;
  */riscv-pcall-hetero-u32-f32-real.so) expected=0x40e8000000000008; entry="#poly_entry"; runner="polycall"; call_prefix="heterou32f32:" ;;
  */riscv-pcall-hetero-f32-u32-real.so) expected=0x0000000840e80000; entry="#poly_entry"; runner="polycall"; call_prefix="heterof32u32:" ;;
  */riscv-pcall-cross-needed-real.so) expected=536; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cross-needed-transitive-real.so) expected=1770; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cross-compact-real.so) expected=0x426d00d642020070; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cross-ifunc-compact-real.so) expected=0x431f020242a50138; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cross-ifunc-fp64-stack-real.so) expected=0x4061100000000000; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cross-ifunc-vec128-real.so) expected=0x01bc014d00de006f; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cross-fp64-stack-real.so) expected=0x4061100000000000; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cross-vec128-real.so) expected=0x01bc014d00de006f; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cross-root-compact-real.so) expected=0x415c019d41b0013d; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cross-root-ifunc-compact-real.so) expected=0x4355026d42d7019f; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cross-root-ifunc-fp64-stack-real.so) expected=0x4061100000000000; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cross-root-ifunc-vec128-real.so) expected=0x01bc014d00de006f; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cross-root-fp64-stack-real.so) expected=0x4061100000000000; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cross-root-vec128-real.so) expected=0x01bc014d00de006f; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cross-root-tls-real.so) expected=2348; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cross-root-ifunc-real.so) expected=2045; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-cross-needed-tls-external-real.so) expected=1045; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-x86-sret-import-real.so) expected=0x000b00160021002e; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-x86-sret-stack-import-real.so) expected=0x000b001600210042; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-x86-sret-callee-stack-import-real.so) expected=7356; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-x86-sum8-import-real.so) expected=236; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-x86-sum10-import-real.so) expected=255; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-x86-sum14-import-real.so) expected=305; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-x86-align14-import-real.so) expected=305; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-x86-i128-import-real.so) expected=0x22421121; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-x86-i128-callee-import-real.so) expected=7201; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-x86-callee-import-real.so) expected=7386; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-x86-callee-stack-import-real.so) expected=7455; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-x86-sum8-post-import-real.so) expected=245; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-x86-fp64-import-real.so) expected=0x4069e80000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fp64:" ;;
  */riscv-pcall-x86-fp64-sum8-import-real.so) expected=0x406da80000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fp64:" ;;
  */riscv-pcall-x86-fp64-sum10-import-real.so) expected=0x4070040000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fp64:" ;;
  */riscv-pcall-x86-fp64-callee-import-real.so) expected=0x40993e0000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fp64:" ;;
  */riscv-pcall-x86-fp64-callee-stack-import-real.so) expected=0x409a0e0000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fp64:" ;;
  */riscv-pcall-x86-fpair64-import-real.so) expected=0x405ad0004069e800; entry="#poly_entry"; runner="polycall"; call_prefix="fpair:" ;;
  */riscv-pcall-x86-fpair64-fp64-callee-import-real.so) expected=0x409ae50000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fp64:" ;;
  */riscv-pcall-x86-fpair32-import-real.so) expected=0x41da0000418a0000; entry="#poly_entry"; runner="polycall"; call_prefix="fpair32:" ;;
  */riscv-pcall-x86-fpair32-fp32-callee-import-real.so) expected=0x44b56800; entry="#poly_entry"; runner="polycall"; call_prefix="fp32:" ;;
  */riscv-pcall-x86-vec128-import-real.so) expected=0x01e4016b00f20079; entry="#poly_entry"; runner="polycall"; call_prefix="vec128u32:" ;;
  */riscv-pcall-x86-vec128-fp64-callee-import-real.so) expected=0x0208018f0116009d; entry="#poly_entry"; runner="polycall"; call_prefix="vec128u32:" ;;
  */riscv-pcall-x86-sret-stack10-import-real.so) expected=0x000b00160021008c; entry="#poly_entry"; runner="polycall"; call_prefix="sret10:" ;;
  */riscv-pcall-x86-sret-fp64-callee-stack-import-real.so) expected=0x4099450000000000; entry="#poly_entry"; runner="polycall"; call_prefix="fp64:" ;;
  */riscv-pcall-x86-mixed-u64-fp64-import-real.so) expected=0x406aa80000000000; entry="#poly_entry"; runner="polycall"; call_prefix="mixedargs:" ;;
  */riscv-pcall-x86-mixed-u64-fp64-callee-import-real.so) expected=0x40b2f1c000000000; entry="#poly_entry"; runner="polycall"; call_prefix="mixedargs:" ;;
  */riscv-pcall-x86-mixed-u64-fp64-stack-import-real.so) expected=0x40788c0000000000; entry="#poly_entry"; runner="polycall"; call_prefix="mixedstack:" ;;
  */riscv-pcall-x86-fp32-import-real.so) expected=0x434f4000; entry="#poly_entry"; runner="polycall"; call_prefix="fp32:" ;;
  */riscv-pcall-abs-runpath-real.so) expected=945; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-rpath-real.so) expected=945; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-rpath-inherit-real.so) expected=745; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-colon-runpath-real.so) expected=945; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-lib-runpath-real.so) expected=945; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-platform-runpath-real.so) expected=945; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-runpath-prefer-real.so) expected=945; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-needed-relro-real.so) expected=745; entry="#poly_entry"; runner="polycall" ;;
  */riscv-pcall-relro-real.so) expected=745; entry="#poly_entry"; runner="polycall" ;;
esac

target="${call_prefix}${path}${entry}"
if [ "$process_mode" = "1" ] && [ "${1:-}" = "$path" ]; then
  shift
fi
echo "POLYBINFMT_EXEC: path=$path entry=${entry:-none} expected=${expected:-none} runner=$runner call_prefix=${call_prefix:-none} process=$process_mode argc=$#"
if [ "$process_mode" = "1" ]; then
  if [ -n "$expected" ]; then
    exec "/usr/bin/$runner" --process "$target=$expected" "$@"
  fi
  exec "/usr/bin/$runner" --process "$target" "$@"
fi
if [ -n "$expected" ]; then
  exec "/usr/bin/$runner" "$target=$expected"
fi
exec "/usr/bin/$runner" "$target"
